SELECT
	 MemberID
	,EnrollmentStartDate
	,DisEnrollmentDate
	,DentalBenefit
	,DrugBenefit
	,MentalHealthBenefitInpatient
	,MentalHealthBenefitIntensiveOutpatient
	,MentalHealthBenefitOutpatient
	,ChemDepBenefitInpatient
	,ChemDepBenefitIntensiveOutpatient
	,ChemDepBenefitOutpatientED
	,MedicalBenefit
	,InstitutionalLTSSBenefit
	,HomeandCommunityLTSSBenefit
	,Payer
	,HealthPlanEmployeedependantFlag
	,Indicator
	,PrimaryEnrollmentFlag
	,ProductID
	,ReportingID
	,MemberGroupCode
	,AdditionalColumn1
	,AdditionalColumn2
	,AdditionalColumn3
	,AdditionalColumn4
	,AdditionalColumn5
	,Filler
FROM Q360MemberEnrollment