SELECT
	ContractNumber
	,RunDate
	,PaymentDate
	,BeneficiaryID
	,Surname
	,FirstInitial
	,GenderCode
	,DateOfBirth
	,Filler
	,StateCountyCode 
	,OutOfAreaIndicator
	,PartAEntitlement
	,PartBEntitlement
	,Hospice
	,Esrd
	,AgedDisabledMsp
	,Filler1
	,Filler2
	,NewMedicareBeneficiaryMedicaidStatusFlag
	,LTIFlag
	,MedicaidAddOnFactorIndicator 
	,Filler3
	,DefaultRiskFactorCode
	,RiskAdjustmentFactorA
	,RiskAdjustmentFactorB
	,NumberOfPaymentAdjustmentMonthsPartA
	,NumberOfPaymentAdjustmentMonthsPartB
	,AdjustmentReasonCode
	,PaymentAdjustmentStartDate
	,PaymentAdjustmentEndDate
	,Filler4
	,Filler5
	,MonthlyRiskAdjustedAmountPartA
	,MonthlyRiskAdjustedAmountPartB
	,LisPremiumSubsidy
	,ESRDMSPFlag
	,MedicationTherapyManagementAddOn 
	,Filler6
	,MedicaidFullPartialNondual
	,RiskAdjustmentAgeGroup
	,Filler7
	,Filler8
	,Filler9
	,PlanBenefitPackageID
	,Filler10
	,RiskAdjustmentFactorTypeCode
	,FrailtyIndicator
	,OriginalReasonForEntitlementCode
	,Filler11
	,SegmentNumber
	,Filler12
	,EGHPFlag
	,PartCBasicPremiumPartAAmount
	,PartCBasicPremiumPartBAmount
	,RebateForPartACostSharingReduction
	,RebateForPartBCostSharingReduction
	,RebateForOtherPartAMandatorySupplementalBenefits
	,RebateForOtherPartBMandatorySupplementalBenefits
	,RebateForPartBPremiumReductionPartAAmount
	,RebateForPartBPremiumReductionPartBAmount
	,RebateForPartDSupplementalBenefitsPartAAmount
	,RebateForPartDSupplementalBenefitsPartBAmount
	,TotalPartAMAPayment
	,TotalPartBMAPayment
	,TotalMAPaymentAmount
	,PartDRAFactor
	,PartDLowIncomeIndicator
	,PartDLowIncomeMultiplier
	,PartDLongTermInstitutionalIndicator
	,PartDLongTermInstitutionalMultiplier
	,RebateForPartDBasicPremiumReduction
	,PartDBasicPremiumAmount
	,PartDDirectSubsidyMonthlyPaymentAmount
	,ReinsuranceSubsidyAmount
	,LowIncomeSubsidyCostSharingAmount
	,TotalPartDPayment
	,NumberOfPaymentAdjustmentMonthsPartD
	,PACEPremiumAddOn
	,PACECostSharingAddOn
	,PartCFrailtyScoreFactor
	,MSPFactor
	,MSPReductionReductionAdjustmentAmountPartA
	,MSPReductionReductionAdjustmentAmountPartB
	,MedicaidDualStatusCode
	,PartDCoverageGapDiscountAmount
	,PartDRiskAdjustmentFactorType
	,DefaultPartDRiskAdjustmentFactorCode
	,PartARiskAdjustedMonthlyRateAmountForPaymentAdjustment
	,PartBRiskAdjustedMonthlyRateAmountForPaymentAdjustment
	,PartDDirectSubsidyMonthlyRateAmountForPaymentAdjustment
	,CleanupID
FROM Q360MonthlyMembershipDetail