SELECT
	 MemberID
	,Gender
	,DateofBirth
	,MemberLastName
	,MemberFirstName
	,MemberMiddleInitial
	,SubscriberID
	,Address1
	,Address2
	,City
	,State
	,Zip
	,TelephoneNumber
	,CaretakerFirstName
	,CaretakerMiddleInitial
	,CaretakerLastName
	,SpokenLanguage 
	,SpokenLanguageSource
	,WrittenLanguage
	,WrittenLanguageSource
	,OtherLanguage
	,OtherLanguageSource
	,MBI
	,ContractID
	,Race
	,Ethnicity
	,RaceDataSource
	,EthnicityDataSource
	,QHPIssuerLegalName
	,EnrolleeEducation
	,EnrolleeEmployment
	,IssuerID
	,QHPState
	,MetalLevel
	,VariantID
	,APTCEligibilityFlag
	,PlanMarketingName
	,MedicaidExpansionQHPEnrollee
	,ReportingStatus
	,EnrolleeEmailAddress
	,EnrolleePhone2
	,TotalEnrollment
	,CaretakerEmailAddress
	,DeceasedDate
	,AdditionalColumn1
	,AdditionalColumn2
	,AdditionalColumn3
	,AdditionalColumn4
	,AdditionalColumn5
	,Filler
FROM Q360Membership