SELECT
	ProviderID
	,PCPFlag
	,OBGYNFlag
	,MHProviderFlag
	,EyeCareProviderFlag
	,DentistFlag
	,NephrologistFlag
	,AnesthesiologistFlag
	,NPRProviderFlag
	,PASProviderFlag
	,ProviderPrescribingPrivilegesFlag
	,ClinicalPharmacistFlag
	,HospitalFlag
	,SNFFlag
	,SurgeonFlag
	,RegisteredNurseFlag
	,PediatricianFlag
	,DiabetologistFlag
	,DieticianFlag
	,PhysiotherapistFlag
	,NutritionistFlag
	,Endocrinologist
	,Urologist
	,Cardiologist
	,Radiologist
	,Oncologist
	,PainSpecialist
	,MedicalLabTechnician
	,ClinicalLabTechnician
	,ProviderNPI
	,AdditionalColumn1
	,AdditionalColumn2
	,AdditionalColumn3
	,AdditionalColumn4
	,AdditionalColumn5
	,Filler
FROM Q360Provider