with source as (

    select * from {{ source('public', 'service_line') }}

),

renamed as (

    select
        id,
        claim_number,
        line_number,
        procedure_qualifier,
        procedure_code,
        modifier_1,
        modifier_2,
        modifier_3,
        modifier_4,
        procedure_description,
        line_charge_amount,
        unit_measurement_code,
        service_unit_count,
        place_of_service_code,
        service_type_code,
        diagnosis_code_pointer_1,
        diagnosis_code_pointer_2,
        diagnosis_code_pointer_3,
        diagnosis_code_pointer_4,
        emergency_indicator,
        multiple_procedure_code,
        epsdt_indicator,
        family_planning_indicator,
        review_code,
        national_or_local_assigned_review_value,
        copay_status_code,
        health_care_professional_shortage_area_code,
        reference_identification,
        postal_code,
        revenue_code,
        sv2_procedure_qualifier,
        sv2_procedure_code,
        sv2_modifier_1,
        sv2_line_charge_amount,
        sv2_unit_measurement_code,
        sv2_service_unit_count,
        sv2_non_covered_charge_amount,
        sv2_blood_deductible_pints,
        sv2_measurement_code,
        sv3_procedure_qualifier,
        sv3_procedure_code,
        sv3_line_charge_amount,
        sv3_facility_code_qualifier,
        sv3_facility_code,
        sv3_oral_cavity_designation_1,
        sv3_oral_cavity_designation_2,
        sv3_oral_cavity_designation_3,
        sv3_oral_cavity_designation_4,
        sv3_oral_cavity_designation_5,
        sv3_prosthesis_crown_onlay_code,
        sv3_tooth_number,
        sv3_tooth_surface_code_1,
        sv3_tooth_surface_code_2,
        sv3_tooth_surface_code_3,
        sv3_tooth_surface_code_4,
        sv3_tooth_surface_code_5,
        service_date_qualifier,
        service_date_format,
        service_date,
        line_ref_qualifier_1,
        line_ref_id_1,
        prior_auth_qualifier,
        prior_auth_number,
        line_item_control_number_qualifier,
        line_item_control_number,
        repriced_line_ref_qualifier,
        repriced_line_ref_id,
        mammography_certification_qualifier,
        mammography_certification_number,
        clia_ref_qualifier,
        clia_ref_number,
        line_note_reference_code,
        line_note_text,
        line_pricing_methodology,
        line_repriced_allowed_amount,
        line_repriced_saving_amount,
        line_repriced_org_id,
        line_reject_reason_code,
        line_policy_compliance_code,
        line_exception_code,
        created_at

    from source

)

select * from renamed