CREATE TABLE [devidap1].[gold_ma_riskbymember]
( 
	 [clientCode] nvarchar(20) NULL
	,[snapshotdate] date NULL
	,[reportMonth] nvarchar(12) NULL
	,[serviceYear] int NULL
	,[beneficiaryID] nvarchar(60) NULL
	,[planMemberID] nvarchar(100) NULL
	,[MemberClientKey] nvarchar(20) NULL
	,[memberGender] nvarchar(20) NULL
	,[memberAGE] nvarchar(20) NULL
	,[lowIncomeSubsidy] nvarchar(20) NULL
	,[memberEnrollmentStartDate] date NULL
	,[memberEnrollmentEndDate] date NULL
	,[poCode] nvarchar(20) NULL
	,[lobid] nvarchar(20) NULL
	,[planID] nvarchar(100) NULL
	,[PlanDescription] nvarchar(200) NULL
	,[memberZIPCode] nvarchar(20) NULL
	,[memberState] nvarchar(40) NULL
	,[memberCounty] nvarchar(100) NULL
	,[attributedProviderID] nvarchar(100) NULL
	,[attributedProviderTIN] varchar(25) NULL
	,[memberDOB] date NULL
	,[memberDemographicRiskScore] float NULL
	,[memberCodedRiskScore] nvarchar(100) NULL
	,[opportunityRiskScore] nvarchar(100) NULL
	,[memberMonths] float NULL
	,[incurredEndDate] date NULL
	,[paidThroughDate] date NULL
	,[hospiceind] nvarchar(2) NULL
	,[esrdInd] nvarchar(2) NULL
	,[inHomeAssessmentInd] nvarchar(20) NULL
	,[inHomeAssessmentDOS] nvarchar(20) NULL
	,[specialistonlyInd] nvarchar(2) NULL
	,[selfManagingInd] nvarchar(2) NULL
	,[polyChronicInd] nvarchar(2) NULL
	,[annualWellnessVisitDate] nvarchar(20) NULL
	,[annualWellnessVisitProviderID] nvarchar(50) NULL
	,[annualWellnessVisitProviderTIN] nvarchar(50) NULL
	,[memberModelStatus] nvarchar(100) NULL
) 