CREATE TABLE [devidap1].[gold_ma_membership]
( 
	ClientCode	nvarchar(20) NULL
	,SnapshotDate 	date NULL
	,ReportMonth	nvarchar(10) NULL
	,ServiceYear	int NULL
	,MemberID	nvarchar(20) NULL
	,EnrollmentStartDate	date NULL
	,EnrollmentEndDate	date NULL
	,MemberDOB	date NULL
	,MemberGender	nvarchar(20) NULL
	,BeneficiaryID	nvarchar(60) NULL
	,CMSContractnumber	nvarchar(100) NULL
	,PlanDescription	nvarchar(200) NULL
	,MemberFirstName	nvarchar(200) NULL
	,MemberLastName	nvarchar(200) NULL
	,ProviderID	nvarchar(50) NULL
	,ProviderEffectiveStartDate	date NULL
	,ProviderEffectiveEndDate	date NULL
	,MemberAge	int
	,PermanentAddressLine1	nvarchar(200) NULL
	,PermanentAddressLine2	nvarchar(200) NULL
	,PermanentAddressLine3	nvarchar(200) NULL
	,PermanentCity	nvarchar(200) NULL
	,PermanentCounty	nvarchar(20) NULL
	,PermanentState	nvarchar(50) NULL
	,PermanentZIPCode	nvarchar(20) NULL
	,PBP	nvarchar(50) NULL
	,ProviderNPI	nvarchar(50) NULL
	,ProviderName	nvarchar(500) NULL
	,ProviderTIN	nvarchar(50) NULL
	,ProviderOrganization	nvarchar(100) NULL
	,PracticeUnit	nvarchar(250) NULL
	,PoolID	nvarchar(100) NULL
	,Rafactortypecode	nvarchar(30) NULL
	,RafactortypecodeDrived	nvarchar(30) NULL
	,DefaultIndicator	nvarchar(30) NULL
	,MedicaidDualStatusCode	nvarchar(40) NULL
	,MedicaidIndicator  	nvarchar(20) NULL
	,OriginalReasonforEntitlement	nvarchar(20) NULL
	,RiskAdjusterFactorA	nvarchar(20) NULL
	,RiskAdjusterFactorB 	nvarchar(20) NULL
	,Hospice	nvarchar(50) NULL
	,ESRD	nvarchar(50) NULL
	,LowIncomeSubsidyMMRNonzero	nvarchar(20) NULL
	,LowIncomeSubsidy	nvarchar(20) NULL
	,MinimumEffectiveDate	date NULL
	,TotalMemberMonths	int NULL
	,Segment	nvarchar(30) NULL
	,Memberstatus	nvarchar(20) NULL
	,IsLatest	bit NULL
	,MinimumStartDate	date NULL
	,MaximumEndDate	date NULL
	,AttributedProviderOffice	nvarchar(250) NULL
	,DemographicRiskAdjustmentFactor	nvarchar(20) NULL
) 