CREATE TABLE [devidap1].[gold_ma_pcpattribution]
( 
 	[FileLayoutID] int NULL
	,[BISInternalPersonID] nvarchar(255) NULL
	,[uniquePersonKey] nvarchar(50) NULL
	,[planMemberID] nvarchar(50) NULL
	,[beneficiaryID] nvarchar(30) NULL
	,[medicaidID] nvarchar(30) NULL
	,[startDate] date NULL
	,[endDate] date NULL
	,[additionalSpanValue] nvarchar(20) NULL
	,[providerID] nvarchar(50) NULL
	,[altPCPReporting1] nvarchar(255) NULL
	,[altPCPReporting2] nvarchar(255) NULL
	,[altPCPReporting3] nvarchar(255) NULL
	,[altPCPReporting4] nvarchar(255) NULL
	,[altPCPReporting5] nvarchar(255) NULL
	,[altPCPReporting6] nvarchar(255) NULL
	,[altPCPReporting7] nvarchar(255) NULL
	,[altPCPReporting8] nvarchar(255) NULL
	,[altPCPReporting9] nvarchar(255) NULL
	,[altPCPReporting10] nvarchar(255) NULL
	,[subscriberID] nvarchar(50) NULL
	,[providerAddressSuffix] nvarchar(25) NULL
	,[providerEffDate] date NULL
	,[providerFirstName] nvarchar(100) NULL
	,[providerLastName] nvarchar(100) NULL
	,[providerMiddleIntial] nvarchar(2) NULL
	,[memberFirstName] nvarchar(100) NULL
	,[memberLastName] nvarchar(100) NULL
	,[memberMiddleIntial] nvarchar(2) NULL
	,[memberDOB] date NULL
	,[contractNumber] nvarchar(20) NULL
	,[providerNPI] nvarchar(20) NULL
	,[providerTaxonomy] nvarchar(20) NULL
	,[providerTIN] nvarchar(20) NULL
	,[providerAddress1] nvarchar(100) NULL
	,[providerAddress2] nvarchar(100) NULL
	,[providerCity] nvarchar(100) NULL
	,[providerState] nvarchar(2) NULL
	,[providerZip] nvarchar(15) NULL
	,[providerCounty] nvarchar(15) NULL
	,[providerPhone] nvarchar(50) NULL
	,[providerFax] nvarchar(50) NULL
	,[providerEmail] nvarchar(100) NULL
	,[billingProviderID] nvarchar(50) NULL
	,[billingProviderLastName] nvarchar(100) NULL
	,[billingProviderMiddleInitial] nvarchar(2) NULL
	,[billingProviderFirstName] nvarchar(100) NULL
	,[billingProviderNPI] nvarchar(20) NULL
	,[billingProviderTIN] nvarchar(20) NULL
	,[billingProviderAddressLine1] nvarchar(100) NULL
	,[billingProviderAddressLine2] nvarchar(100) NULL
	,[billingProviderCity] nvarchar(50) NULL
	,[billingProviderState] nvarchar(2) NULL
	,[billingProviderZipCode] nvarchar(10) NULL
	,[billingProviderCountyCode] nvarchar(5) NULL
	,[billingProviderPhoneNumber] nvarchar(15) NULL
	,[billingProviderFaxNumber] nvarchar(15) NULL
	,[billingProviderEmail] nvarchar(100) NULL
	,[source] nvarchar(20) NULL
	,[isActive] bit NULL
	,[errorVoidStatus] nvarchar(20) NULL
	,[fileGenerationDateTime] datetime2(7) NULL
) 

