CREATE TABLE [devidap1].[gold_ma_mamembershipstars]
( 
	 [yearMonth] int NULL
	,[planMemberID] nvarchar(100) NULL
	,[beneficiaryID] nvarchar(60) NULL
	,[memberLastName] nvarchar(200) NULL
	,[memberFirstName] nvarchar(200) NULL
	,[memberGender] nvarchar(20) NULL
	,[memberDOB] date NULL
	,[memberDOD] date NULL
	,[memberDeathInd] int NULL
	,[memberAddress1] nvarchar(200) NULL
	,[memberAddress2] nvarchar(200) NULL
	,[memberCity] nvarchar(200) NULL
	,[memberState] nvarchar(40) NULL
	,[memberZip] nvarchar(20) NULL
	,[memberCounty] nvarchar(100) NULL
	,[memberPhone] nvarchar(60) NULL
	,[memberEmail] nvarchar(200) NULL
	,[planID] nvarchar(100) NULL
	,[productName] nvarchar(100) NULL
	,[pbp] nvarchar(50) NULL
	,[memberGroupNumber] nvarchar(100) NULL
	,[memberGroupName] nvarchar(300) NULL
	,[memberGroupCategory] nvarchar(200) NULL
	,[attributionClass] nvarchar(200) NULL
	,[enrlMinBeginDate] date NULL
	,[enrlBeginDate] date NULL
	,[enrlEndDate] date NULL
	,[hospiceInd] int NULL
	,[esrdInd] int NULL
	,[instlInd] int NULL
	,[riskScoreCMMR] float NULL
	,[lisInd] int NULL
	,[rxFlag] int NULL
	,[poCode] nvarchar(100) NULL
	,[poName] nvarchar(510) NULL
	,[practiceCode] nvarchar(100) NULL
	,[practiceName] nvarchar(510) NULL
	,[providerID] nvarchar(100) NULL
	,[providerNPI] nvarchar(100) NULL
	,[providerTIN] nvarchar(100) NULL
	,[providerLastName] nvarchar(200) NULL
	,[providerFirstName] nvarchar(200) NULL
	,[providerAddress1] nvarchar(510) NULL
	,[providerAddress2] nvarchar(510) NULL
	,[providerCity] nvarchar(200) NULL
	,[providerState] nvarchar(50) NULL
	,[providerZip] nvarchar(20) NULL
	,[providerCounty] nvarchar(200) NULL
	,[providerEmail] nvarchar(200) NULL
	,[providerPhone] nvarchar(60) NULL
	,[providerFax] nvarchar(60) NULL
	,[providerType] nvarchar(300) NULL
	,[pcmh] int NULL
	,[currCvgInd] int NULL
	,[providerTaxonomy] nvarchar(200) NULL
	,[providerSpecialty] nvarchar(200) NULL
	,[memberDoNotContact] int NULL
	,[altMemberId9] nvarchar(100) NULL
	,[altMemberIdCurr] nvarchar(100) NULL
	,[sourceLoadDate] datetime2(7) NULL
	,[HashRowKey] int NULL
) 