CREATE TABLE [devidap1].[gold_ma_medicalgoldenclaimdiagnosis]
( 
	 [GeneratedGoldenClaimsUniqueKey] nvarchar(510) NULL
	,[GeneratedMedicalClaimsUniqueKey] nvarchar(510) NULL
	,[ClientID] nvarchar(20) NULL
	,[FileLayoutID] int NULL
	,[FileLayoutDescription] nvarchar(255) NULL
	,[ClaimNumber] nvarchar(200) NULL
	,[OriginalClaimNumber] nvarchar(200) NULL
	,[BeneficiaryID] nvarchar(60) NULL
	,[PlanMemberID] nvarchar(100) NULL
	,[CMSContractNumber] nvarchar(40) NULL
	,[BillTypeCode] nvarchar(10) NULL
	,[ClaimTypeInd] nvarchar(10) NULL
	,[ClaimStatus] nvarchar(10) NULL
	,[ClaimProcessDate] datetime2(7) NULL
	,[ClaimFormType] nvarchar(10) NULL
	,[DetailServiceDate] nvarchar(20) NULL
	,[ClaimEntryDate] nvarchar(20) NULL
	,[ClaimReceivedDate] nvarchar(20) NULL
	,[ClaimTotalChargeAmount] nvarchar(40) NULL
	,[ClaimAllowedAmount] nvarchar(40) NULL
	,[CheckDate] nvarchar(20) NULL
	,[ClaimFinalizedDate] nvarchar(20) NULL
	,[CoinsuranceAmt] nvarchar(40) NULL
	,[DeductibleAmt] nvarchar(40) NULL
	,[CopayAmt] nvarchar(40) NULL
	,[ServiceFacilityID] nvarchar(50) NULL
	,[ServiceFacilityNPI] nvarchar(50) NULL
	,[RenderingProviderID] nvarchar(50) NULL
	,[RenderingProviderNPI] nvarchar(50) NULL
	,[RenderingProviderTIN] nvarchar(40) NULL
	,[RenderingProviderSpecialtyCode] nvarchar(40) NULL
	,[BillingProviderID] nvarchar(40) NULL
	,[BillingProviderTIN] nvarchar(40) NULL
	,[BillingProviderTaxonomy] nvarchar(60) NULL
	,[AttendingProviderNPI] nvarchar(50) NULL
	,[PlaceOfService] nvarchar(10) NULL
	,[StatementFromDate] nvarchar(20) NULL
	,[StatementToDate] nvarchar(20) NULL
	,[ICD] nvarchar(20) NULL
	,[ICDCodeType] nvarchar(4) NULL
	,[isPrimaryCode] int NULL
	,[isAdmitcode] int NULL
	,[IsRiskAdjustable] int NULL
	,[hashKey] int NULL
	,[UniquePersonKey] nvarchar(100) NULL
) 