CREATE TABLE [devidap1].[gold_ma_consolidatedmmr]
( 
	 [PlanID] nvarchar(20) NULL
	,[BeneficiaryID] nvarchar(20) NULL
	,[BeneficiaryIDOriginal] nvarchar(20) NULL
	,[MBIIndicator] nvarchar(20) NULL
	,[EnrollmentMonth] nvarchar(20) NULL
	,[EnrollmentYear] nvarchar(20) NULL
	,[EnrollmentYearMonth] nvarchar(20) NULL
	,[Rundate] date NULL
	,[Lastname] nvarchar(20) NULL
	,[FirstInitial] nvarchar(20) NULL
	,[EnrollmentSource] nvarchar(20) NULL
	,[PersonTotal] nvarchar(20) NULL
	,[PlanBenefitPackage] nvarchar(20) NULL
	,[NewPlanBenefitPackage] nvarchar(20) NULL
	,[SegmentID] nvarchar(20) NULL
	,[EghpFlag] nvarchar(20) NULL
	,[RiskAdjusterFactorA] nvarchar(20) NULL
	,[PartDRAFactor] nvarchar(20) NULL
	,[Gendercode] nvarchar(20) NULL
	,[DOB] date NULL
	,[Agegroup] nvarchar(20) NULL
	,[AgedDisabledIdentifier] nvarchar(20) NULL
	,[StateandCountyCode] nvarchar(20) NULL
	,[OutOfAreaIndicator] nvarchar(20) NULL
	,[Hospice] nvarchar(20) NULL
	,[ESRD] nvarchar(20) NULL
	,[AgedMsp] nvarchar(20) NULL
	,[InstitutionalFlag] nvarchar(20) NULL
	,[NHC] nvarchar(20) NULL
	,[MedicaidBeneficiaryStatusFlag] nvarchar(20) NULL
	,[MedicaidIndicator] nvarchar(20) NULL
	,[CurrentMedicaidStatus] nvarchar(20) NULL
	,[PartCDualStatusFlag] nvarchar(20) NULL
	,[PartDDualStatusFlag] nvarchar(20) NULL
	,[LTIFlag] nvarchar(20) NULL
	,[PartDLowIncomeIndicator] nvarchar(20) NULL
	,[PartDLongTermInstitutionalIndicator] nvarchar(20) NULL
	,[PartCDefaultRiskFactorCode] nvarchar(20) NULL
	,[ESRDMspFlag] nvarchar(20) NULL
	,[RiskAdjusterAgeGroup] nvarchar(20) NULL
	,[PreviousDisableRatio] nvarchar(20) NULL
	,[DeMinimis] nvarchar(20) NULL
	,[RaceCode] nvarchar(20) NULL
	,[PartCRAFactorTypeCode] nvarchar(20) NULL
	,[FrailtyIndicator] nvarchar(20) NULL
	,[OriginalReasonforEntitlement] nvarchar(20) NULL
	,[LagIndicator] nvarchar(20) NULL
	,[EnrolledInPartAIndicator] nvarchar(20) NULL
	,[EnrolledInPartBIndicator] nvarchar(20) NULL
	,[EnrolledInPartCIndicator] nvarchar(20) NULL
	,[EnrolledInPartDIndicator] nvarchar(20) NULL
	,[FinalPartCStatus] nvarchar(120) NULL
	,[FinalPartDStatus] nvarchar(120) NULL
	,[DemographicPaymentAdjustmentRatePartA] nvarchar(20) NULL
	,[DemographicPaymentAdjustmentRatePartB] nvarchar(20) NULL
	,[RiskAdjusterPaymtAdjustmentRateA] nvarchar(20) NULL
	,[RiskAdjusterPaymtAdjustmentRateB] nvarchar(20) NULL
	,[RiskAdjusterPaymtAdjustmentRateAPlusRateB] nvarchar(20) NULL
	,[RiskAdjusterPaymtAdjustmentRateAPlusRateBSeq] nvarchar(20) NULL
	,[LISPremiumSubsidy] nvarchar(20) NULL
	,[PartCBasicPremiumPartAAmount] nvarchar(20) NULL
	,[PartCBasicPremiumPartBAmount] nvarchar(20) NULL
	,[PartCBasicPremiumPartAAmountPlusPartBAmout] nvarchar(20) NULL
	,[RebateCostshareA] nvarchar(20) NULL
	,[RebateCostshareB] nvarchar(20) NULL
	,[RebateforPartAPlusPartBCostSharingReduction] nvarchar(20) NULL
	,[RebateforPartAPlusPartBCostSharingReductionSeq] nvarchar(20) NULL
	,[RebateforOtherPartAMandatorySupplementalBenefits] nvarchar(20) NULL
	,[RebateforOtherPartBMandatorySupplementalBenefits] nvarchar(20) NULL
	,[RebateforOtherPartAPlusPartBMandatorySupplementalBenefits] nvarchar(20) NULL
	,[RebateforOtherPartAPlusPartBMandatorySupplementalBenefitsSeq] nvarchar(20) NULL
	,[RebateforPartBPremiumReductionPartAAmount] nvarchar(20) NULL
	,[RebateforPartBPremiumReductionPartBAmount] nvarchar(20) NULL
	,[RebateforPartBPremiumReductionPartAPlusPartBAmount] nvarchar(20) NULL
	,[RebateforPartBPremiumReductionPartAPlusPartBAmountSeq] nvarchar(20) NULL
	,[RebateforPartDSupplementalBenefitsPartAAmount] nvarchar(20) NULL
	,[RebateforPartDSupplementalBenefitsPartBAmount] nvarchar(20) NULL
	,[RebateforPartDSupplementalBenefitsPartAPlusPartBAmount] nvarchar(20) NULL
	,[RebateforPartDSupplementalBenefitsPartAPlusPartBAmountSeq] nvarchar(20) NULL
	,[TotalPartAPayment] nvarchar(20) NULL
	,[TotalPartBPayment] nvarchar(20) NULL
	,[TotalPartCPayment] nvarchar(20) NULL
	,[RebateForPartDBasicPremiumReduction] nvarchar(20) NULL
	,[RebateForPartDBasicPremiumReductionSeq] nvarchar(20) NULL
	,[PartDBasicPremiumAmount] nvarchar(20) NULL
	,[PartDDirectSubsidyPaymentAmount] nvarchar(20) NULL
	,[PartDDirectSubsidyPaymentAmountSeq] nvarchar(20) NULL
	,[ReinsuranceSubsidyAmount] nvarchar(20) NULL
	,[LowIncomeSubsidyCostSharingAmount] nvarchar(20) NULL
	,[TotalPartDPayment] nvarchar(20) NULL
	,[PacePremiumAddOn] nvarchar(20) NULL
	,[PaceCostSharingAddOn] nvarchar(20) NULL
	,[BeneficiaryDualandPartDEnrollmentStatusFlag] nvarchar(20) NULL
	,[PartCFrailtyScoreFactor] nvarchar(20) NULL
	,[MspFactor] nvarchar(20) NULL
	,[MspMemberMonths] nvarchar(20) NULL
	,[MspReductionAdjustmentAmountPartA] nvarchar(20) NULL
	,[MspReductionAdjustmentAmountPartB] nvarchar(20) NULL
	,[MspReductionAdjustmentPartAPlusPartBAmount] nvarchar(20) NULL
	,[MspReductionAdjustmentPartAPlusPartBAmountSeq] nvarchar(20) NULL
	,[MedicaidDualStatusCode] nvarchar(20) NULL
	,[GapDiscount] nvarchar(20) NULL
	,[GapDiscountSeq] nvarchar(20) NULL
	,[PdRafactype] nvarchar(20) NULL
	,[DefaultPdRa] nvarchar(20) NULL
	,[Finalmedicaidstatus] nvarchar(20) NULL
	,[Plantype] nvarchar(20) NULL
	,[PlanTypeSeparator] nvarchar(20) NULL
	,[BidNoRisk] nvarchar(20) NULL
	,[BidNoRiskSeq] nvarchar(20) NULL
	,[PartCCountyLevelPaymentRate] nvarchar(20) NULL
	,[PartCCountyLevelPaymentRateSeq] nvarchar(20) NULL
	,[RSPTCBIDMedicaidStatus] nvarchar(20) NULL
	,[BeneficiaryPartCDEGroup] nvarchar(20) NULL
	,[BeneficiaryPartCEsrdGroup] nvarchar(20) NULL
	,[BeneficiaryPartCMedicaidStatus] nvarchar(20) NULL
	,[BeneficiaryPartCDualStatus] nvarchar(20) NULL
	,[BeneficiaryPartCRiskScoreBaseUnnormalizedEDS] nvarchar(20) NULL
	,[BeneficiaryPartCRiskScoreProjUnnormalizedEDS] nvarchar(20) NULL
	,[BeneficiaryPartCRiskScoreBaseNormalizedForEDS] nvarchar(20) NULL
	,[BeneficiaryPartCRiskScoreProjNormalizedForEDS] nvarchar(20) NULL
	,[BeneficiaryPartCRiskScoreBaseUnNormalizedForEDS] nvarchar(20) NULL
	,[BeneficiaryPartCRiskScoreProjUnNormalizedForEDS] nvarchar(20) NULL
	,[BeneficiaryPartCRiskScoreBaseUnNormalizedRAPS] nvarchar(20) NULL
	,[BeneficiaryPartCRiskScoreBaseNormalizedForRAPS] nvarchar(20) NULL
	,[BeneficiaryPartCRiskScoreBaseUnNormalizedForRAPS] nvarchar(20) NULL
	,[BeneficiaryPartCRiskcohort] nvarchar(20) NULL
	,[BeneficiaryPartCFlag] nvarchar(20) NULL
	,[BeneficiaryPartCFrailtyMemberMonths] nvarchar(20) NULL
	,[PartDBeneficiaryFileBeneficiaryStatus] nvarchar(20) NULL
	,[PartDBeneficiaryFileEDSRiskScore] nvarchar(20) NULL
	,[PartDBeneficiaryFileRAPSRiskScore] nvarchar(20) NULL
	,[PartDBeneficiaryFileProjEdsRiskScore] nvarchar(20) NULL
	,[BeneficiaryFilePartDStatus] nvarchar(20) NULL
	,[BeneficiaryFilePartDFlag] nvarchar(20) NULL
	,[CMMRFileCreateDate] date NULL
	,[ClientID] nvarchar(20) NULL
	,[LoadDateTime] date NULL
	,[FileID] int NULL
	,[FileLayoutID] int NULL
	,[FileLayoutDescription] nvarchar(20) NULL
	,[SubscriberID] nvarchar(20) NULL
	,[GroupNumber] nvarchar(20) NULL
	,[GroupSuffix] nvarchar(20) NULL	
) 