CREATE TABLE [devidap1].[gold_ma_providerhierarchy]
(  
	 [ClientID] nvarchar(20) NULL
	,[FileID] int NULL
	,[LoadDateTime] date NULL
	,[FileLayoutID] int NULL
	,[FileLayoutDescription] nvarchar(255) NULL
	,[ProviderID] nvarchar(100) NOT NULL PRIMARY KEY NONCLUSTERED ([ProviderID] ASC) NOT ENFORCED
	,[ProviderLastName] nvarchar(300) NULL
	,[ProviderNPI] nvarchar(50) NULL
	,[LocationGroupID] nvarchar(100) NULL
	,[LocationRanking] int NULL
	,[LocationIDType] nvarchar(100) NULL
	,[LocationID] nvarchar(100) NULL
	,[LocationDesc] nvarchar(510) NULL
	,[LocationTIN] nvarchar(50) NULL
	,[LocationAddress1] nvarchar(510) NULL
	,[LocationAddress2] nvarchar(510) NULL
	,[LocationCity] nvarchar(200) NULL
	,[LocationState] nvarchar(20) NULL
	,[LocationZip] nvarchar(20) NULL
	,[CountyCode] nvarchar(20) NULL
	,[PhoneNumber] nvarchar(20) NULL
	,[FaxNumber] nvarchar(20) NULL
	,[ContactPerson] nvarchar(300) NULL
	,[DoNotChase] nvarchar(20) NULL
	,[Tier2IDType] nvarchar(100) NULL
	,[Tier2ID] nvarchar(100) NULL
	,[Tier2Desc] nvarchar(255) NULL
	,[Tier2Address1] nvarchar(510) NULL
	,[Tier2Address2] nvarchar(510) NULL
	,[Tier2City] nvarchar(200) NULL
	,[Tier2State] nvarchar(20) NULL
	,[Tier2Zip] nvarchar(20) NULL
	,[Tier3IDType] nvarchar(100) NULL
	,[Tier3ID] nvarchar(100) NULL
	,[Tier3Desc] nvarchar(255) NULL
	,[Tier3Address1] nvarchar(510) NULL
	,[Tier3Address2] nvarchar(510) NULL
	,[Tier3City] nvarchar(200) NULL
	,[Tier3State] nvarchar(20) NULL
	,[Tier3Zip] nvarchar(20) NULL
	,[Tier4IDType] nvarchar(100) NULL
	,[Tier4ID] nvarchar(100) NULL
	,[Tier4Desc] nvarchar(255) NULL
	,[Tier4Address1] nvarchar(510) NULL
	,[Tier4Address2] nvarchar(510) NULL
	,[Tier4City] nvarchar(200) NULL
	,[Tier4State] nvarchar(20) NULL
	,[Tier4Zip] nvarchar(20) NULL
	,[StartDate] date NULL
	,[EndDate] date NULL
) 