CREATE TABLE [devidap1].[gold_ma_member]
( 
	 [BISInternalPersonID] nvarchar(255) NULL
	,[UniqueRecord] nvarchar(255) 
	,[ClientID] nvarchar(20) NULL
	,[FileID] int NULL
	,[LoadDateTime] date NULL
	,[FileLayoutID] int NULL
	,[FileLayoutDescription] nvarchar(255) NULL
	,[UniquePersonKey] nvarchar(20) NULL
	,[PlanMemberID] nvarchar(20) NULL
	,[SubscriberID] nvarchar(20) NULL
	,[BeneficiaryID] nvarchar(20) NULL
	,[LastName] nvarchar(300) NULL
	,[FirstName] nvarchar(300) NULL
	,[MiddleInitial] nvarchar(255) NULL
	,[EnrolleeUniqueID] nvarchar(20) NULL
	,[DateofBirth] date NULL
	,[DeceasedDate] nvarchar(20) NULL
	,[Gender] nvarchar(20) NULL
	,[PermanentAddressLine1] nvarchar(510) NULL
	,[PermanentAddressLine2] nvarchar(510) NULL
	,[PermanentCity] nvarchar(200) NULL
	,[PermanentCounty] nvarchar(20) NULL
	,[PermanentState] nvarchar(20) NULL
	,[PermanentZipCode] nvarchar(20) NULL
	,[MailingAddressLine1] nvarchar(510) NULL
	,[MailingAddressLine2] nvarchar(510) NULL
	,[MailingCity] nvarchar(200) NULL
	,[MailingState] nvarchar(20) NULL
	,[MailingZipCode] nvarchar(20) NULL
	,[MailingCounty] nvarchar(20) NULL
	,[PhoneNumber] nvarchar(20) NULL
	,[Email] nvarchar(255) NULL
	,[MedicaidID] nvarchar(20) NULL
	,[Fax] nvarchar(20) NULL
	,[RaceCode] nvarchar(20) NULL
	,[RaceDataSource] nvarchar(20) NULL
	,[CaretakerFirstName] nvarchar(300) NULL
	,[CaretakerLastName] nvarchar(300) NULL
	,[CaretakerMiddleInitial] nvarchar(100) NULL
	,[EthnicityCode] nvarchar(20) NULL
	,[EthnicityDatasource] nvarchar(20) NULL
	,[SpokenLanguage] nvarchar(20) NULL
	,[SpokenLanguagesourcecode] nvarchar(20) NULL
	,[WrittenLanguageCode] nvarchar(20) NULL
	,[WrittenLanguageSourcecode] nvarchar(20) NULL
	,[OtherLanguage] nvarchar(20) NULL
	,[OtherLanguageSourcecode] nvarchar(20) NULL
	,[USCitizen] nvarchar(20) NULL
	,[AlternateKey1] nvarchar(200) NULL
	,[AlternateKey2] nvarchar(200) NULL
	,[AlternateKey3] nvarchar(200) NULL
	,[AlternateKey4] nvarchar(200) NULL
	,[AlternateKey5] nvarchar(200) NULL
	,[AlternateKey6] nvarchar(200) NULL
	,[AlternateKey7] nvarchar(200) NULL
	,[AlternateKey8] nvarchar(200) NULL
	,[AlternateKey9] nvarchar(200) NULL
	,[AlternateKey10] nvarchar(200) NULL
	,[MaskedMemberID] nvarchar(20) NULL
	,[EnrolleeEducation] nvarchar(100) NULL
	,[EnrolleeEmployment] nvarchar(100) NULL
	,[PMUP] nvarchar(40) NULL
	,[IsCurrentPMUP] int NULL
	,[HashKey] nvarchar(255) NULL
	,[ProductID] nvarchar(100) NULL
)