/*replace the "devidap1" schema with client names for each environment:
DEV - devidap1, devidap2
QA - qaidap1,qaidap2
STAGE - bcbsks, bcbsm
PROD - bcbsks, bcbsm
*/
CREATE TABLE [devidap1].[MAO004] 
(
	LoadDateTime datetime2(7) NOT NULL DEFAULT '0001-01-01 00:00:00',
	FileID       bigint  NOT NULL,
	ClientID     varchar(20)  NOT NULL,
	FileLayoutID       integer  NOT NULL,
	FileLayoutDescription  	varchar(255)  NOT NULL,	
	ReportDate        varchar(8),
	RecordType        varchar(1),
	ReportID        varchar(7),
	MedicareAdvantageContractID        varchar(5),
	BeneficiaryID        varchar(12),
	EncounterICN        varchar(20),
	EncounterTypeSwitch        varchar(1),
	ICNofEncounterLinkedTo        varchar(20),
	AllowedDisallowedStatusofEncounterLinkedTo        varchar(1),
	EncounterSubmissionDate        date,
	FromDateofService        date,
	ThroughDateofService        date,
	ServiceType        varchar(1),
	AllowedDisallowedflag        varchar(1),
	AllowedDisallowedReasonCode        varchar(1),
	DiagnosesICD        varchar(1),
	DiagnosisCode1        varchar(7),
	AddorDeleteflag1        varchar(1),
	DiagnosisCode2        varchar(7),
	AddorDeleteflag2        varchar(1),
	DiagnosisCode3        varchar(7),
	AddorDeleteflag3        varchar(1),
	DiagnosisCode4        varchar(7),
	AddorDeleteflag4        varchar(1),
	DiagnosisCode5        varchar(7),
	AddorDeleteflag5        varchar(1),
	DiagnosisCode6        varchar(7),
	AddorDeleteflag6        varchar(1),
	DiagnosisCode7        varchar(7),
	AddorDeleteflag7        varchar(1),
	DiagnosisCode8        varchar(7),
	AddorDeleteflag8        varchar(1),
	DiagnosisCode9        varchar(7),
	AddorDeleteflag9        varchar(1),
	DiagnosisCode10        varchar(7),
	AddorDeleteflag10        varchar(1),
	DiagnosisCode11        varchar(7),
	AddorDeleteflag11        varchar(1),
	DiagnosisCode12        varchar(7),
	AddorDeleteflag12        varchar(1),
	DiagnosisCode13        varchar(7),
	AddorDeleteflag13        varchar(1),
	DiagnosisCode14        varchar(7),
	AddorDeleteflag14        varchar(1),
	DiagnosisCode15        varchar(7),
	AddorDeleteflag15        varchar(1),
	DiagnosisCode16        varchar(7),
	AddorDeleteflag16        varchar(1),
	DiagnosisCode17        varchar(7),
	AddorDeleteflag17        varchar(1),
	DiagnosisCode18        varchar(7),
	AddorDeleteflag18        varchar(1),
	DiagnosisCode19        varchar(7),
	AddorDeleteflag19        varchar(1),
	DiagnosisCode20        varchar(7),
	AddorDeleteflag20        varchar(1),
	DiagnosisCode21        varchar(7),
	AddorDeleteflag21        varchar(1),
	DiagnosisCode22        varchar(7),
	AddorDeleteflag22        varchar(1),
	DiagnosisCode23        varchar(7),
	AddorDeleteflag23        varchar(1),
	DiagnosisCode24        varchar(7),
	AddorDeleteflag24        varchar(1),
	DiagnosisCode25        varchar(7),
	AddorDeleteflag25        varchar(1),
	DiagnosisCode26        varchar(7),
	AddorDeleteflag26        varchar(1),
	DiagnosisCode27        varchar(7),
	AddorDeleteflag27        varchar(1),
	DiagnosisCode28        varchar(7),
	AddorDeleteflag28        varchar(1),
	DiagnosisCode29        varchar(7),
	AddorDeleteflag29        varchar(1),
	DiagnosisCode30        varchar(7),
	AddorDeleteflag30        varchar(1),
	DiagnosisCode31        varchar(7),
	AddorDeleteflag31        varchar(1),
	DiagnosisCode32        varchar(7),
	AddorDeleteflag32        varchar(1),
	DiagnosisCode33        varchar(7),
	AddorDeleteflag33        varchar(1),
	DiagnosisCode34        varchar(7),
	AddorDeleteflag34        varchar(1),
	DiagnosisCode35        varchar(7),
	AddorDeleteflag35        varchar(1),
	DiagnosisCode36        varchar(7),
	AddorDeleteflag36        varchar(1),
	DiagnosisCode37        varchar(7),
	AddorDeleteflag37        varchar(1),
	DiagnosisCode38        varchar(7),
	AddorDeleteflag38        varchar(1)
)