/*replace the "devidap1" schema with client names for each environment:
DEV - devidap1, devidap2
QA - qaidap1,qaidap2
STAGE - bcbsks, bcbsm
PROD - bcbsks, bcbsm
*/
CREATE TABLE [devidap1].[MedicalClaimLine]
( 
 [GeneratedMedicalClaimsUniqueKey] varchar(255)  NOT NULL  PRIMARY KEY  NONCLUSTERED ([GeneratedMedicalClaimsUniqueKey] ASC,[LineNumber] ASC) NOT ENFORCED
,[FileID]             	bigint  NOT NULL 
,[LineNumber]  varchar(5)   NOT Null
,[TypeOfService]  varchar(5)   Null
,[PlaceOfService]  varchar(5)   Null
,[StatusCode]  varchar(5)   Null
,[TotalChargeAmt]  varchar(15)   Null
,[AllowedAmt]  varchar(15)   Null
,[PurePaymentAmt]  varchar(15)   Null
,[InterestAmt]  varchar(15)   Null
,[CopayAmt]  varchar(15)   Null
,[DeductibleAmt]  varchar(15)   Null
,[OOPAmt]  varchar(15)   Null
,[CPTTypeService]  varchar(5)   Null
,[ServiceFromDate]  date   Null
,[ServiceToDate]  date   Null
,[ProcCodeOrig]  varchar(10)   Null
,[ProcMod1Orig]  varchar(5)   Null
,[ProcMod2Orig]  varchar(5)   Null
,[ProcMod3Orig]  varchar(5)   Null
,[ProcMod4Orig]  varchar(5)   Null
,[DiagCode1]  varchar(10)   Null
,[DiagCode2]  varchar(10)   Null
,[DiagCode3]  varchar(10)   Null
,[DiagCode4]  varchar(10)   Null
,[DiagCode5]  varchar(10)   Null
,[DiagCode6]  varchar(10)   Null
,[DiagCode7]  varchar(10)   Null
,[DiagCode8]  varchar(10)   Null
,[DiagCode9]  varchar(10)   Null
,[DiagCode10]  varchar(10)   Null
,[DiagCode11]  varchar(10)   Null
,[DiagCode12]  varchar(10)   Null
,[EmergencyInd]  varchar(5)   Null
,[RevenueCode]  varchar(5)   Null
,[NoncoveredChargesTotal]  varchar(15)   Null
,[ProcCode]  varchar(10)   Null
,[ProcCodeType]  varchar(10)   Null
,[ProcMod1]  varchar(5)   Null
,[ProcMod2]  varchar(5)   Null
,[ProcMod3]  varchar(5)   Null
,[ProcMod4]  varchar(5)   Null
,[ProcCode1]  varchar(10)   Null
,[ProcCode1Type]  varchar(10)   Null
,[ProcCode1Mod1]  varchar(5)   Null
,[CategoryNum]  varchar(30)   Null
,[MultiCategoryNum]  varchar(30)   Null
,[Classification]  varchar(25)   Null
,[ClassificationAddtnl]  varchar(25)   Null
,[EDIAdjustCodeList]  varchar(200)   Null
,[EventCode1]  varchar(10)   Null
,[EventCode2]  varchar(10)   Null
,[EventCode3]  varchar(10)   Null
,[EventCode4]  varchar(10)   Null
,[EventCode5]  varchar(10)   Null
,[EventCode6]  varchar(10)   Null
,[EventCode7]  varchar(10)   Null
,[EventCode8]  varchar(10)   Null
,[EventCode9]  varchar(10)   Null
,[EventCode10]  varchar(10)   Null
,[EventCode11]  varchar(10)   Null
,[EventCode12]  varchar(10)   Null
,[EventCode13]  varchar(10)   Null
,[EventCode14]  varchar(10)   Null
,[HIPAAAdjustReasonCode]  varchar(200)   Null
,[RemitAdviceCode]  varchar(100)   Null
,[AuthorizationNum]  varchar(25)   Null
,[AuthorizationOverride]  varchar(25)   Null
,[NDCCodeList]  varchar(255)   Null
,[EncounterFlag]  varchar(5)   Null
,[CEOverride]  varchar(5)   Null
,[CEAction]  varchar(5)   Null
,[CEEventCode]  varchar(10)   Null
,[CELineDisp]  varchar(5)   Null
,[EPSDT]  varchar(25)   Null
,[FamilyPlanInd]  varchar(5)   Null
,[TotalChargeAmtOrig]  varchar(15)   Null
,[AllowedAmtOrig]  varchar(20)   Null
,[ContractAllowedAmt]  varchar(15)   Null
,[Quantity]  varchar(20)   Null
,[UnitType]  varchar(10)   Null
,[UnitRate]  varchar(10)   Null
,[COBSavingsAmt]  varchar(15)   Null
,[COBPaidAmt]  varchar(15)   Null
,[DuplicateInd]  varchar(5)   Null
,[DuplicateOption]  varchar(25)   Null
,[GLCode]  varchar(10)   Null
,[GLDate]  varchar(25)   Null
,[Profile]  varchar(25)   Null
,[AdjustCode1]  varchar(5)   Null
,[AdjustCode2]  varchar(5)   Null
,[AdjustCode3]  varchar(5)   Null
,[AdjustCode4]  varchar(5)   Null
,[AdjustCode5]  varchar(5)   Null
,[AdjustCode6]  varchar(5)   Null
,[AdjustCode7]  varchar(5)   Null
,[AdjustCode8]  varchar(5)   Null
,[AdjustCode9]  varchar(5)   Null
,[AdjustCode10]  varchar(5)   Null
,[AdjustCode11]  varchar(5)   Null
,[AdjustCode12]  varchar(5)   Null
,[AdjustCode13]  varchar(5)   Null
,[AdjustCode14]  varchar(5)   Null
,[AdjustCode15]  varchar(5)   Null
,[AdjustCode16]  varchar(5)   Null
,[AdjustCode17]  varchar(5)   Null
,[AdjustCode18]  varchar(5)   Null
,[AdjustCode19]  varchar(5)   Null
,[AdjustCode20]  varchar(5)   Null
,[MemberObligationAmt]  varchar(15)   Null
,[OriginalLineNum]  varchar(5)   Null
,[PrimaryAllowedAmt]  varchar(15)   Null
,[PrimaryDeductAmt]  varchar(15)   Null
,[PrimaryCopayAmt]  varchar(15)   Null
,[PrimaryCoinsAmt]  varchar(15)   Null
,[PrimaryNoncoveredAmt]  varchar(15)   Null
,[PrimaryPaidAmt]  varchar(15)   Null
,[PrimaryMemberObligation]  varchar(20)   Null
,[PrimaryContractAdjstAmt]  varchar(15)   Null
,[PrimaryEOBCode]  varchar(50)   Null
,[PrimaryDiscount]  varchar(15)   Null
,[PricingScheduleCode]  varchar(5)   Null
,[WithholdAmt]  varchar(15)   Null
,[RebundleAmt]  varchar(15)   Null
,[Rider]  varchar(15)   Null
,[APCCode]  varchar(10)   Null
)
