/*replace the "devidap1" schema with client names for each environment:
DEV - devidap1, devidap2
QA - qaidap1,qaidap2
STAGE - bcbsks, bcbsm
PROD - bcbsks, bcbsm
*/
CREATE TABLE [devidap1].[MedicalClaimHeader]
( 
	[GeneratedMedicalClaimsUniqueKey] varchar(255)  NOT NULL PRIMARY KEY NONCLUSTERED ([GeneratedMedicalClaimsUniqueKey] ASC) NOT ENFORCED,
	[ClientID]			 	varchar(20) NOT NULL ,
	[FileID]             	bigint  NOT NULL ,
	[FileLayoutID]       	integer  NOT NULL ,
	[FileLayoutDescription] varchar(255)  NOT NULL ,
	[LoadDateTime]	datetime2(7)	NULL,
	[ClaimNumber]           varchar(100)  NOT NULL ,
	[OriginalClaimNumber]   varchar(100)  NULL ,
	[BeneficiaryID]         varchar(30)  NULL ,
	[PlanMemberID]          varchar(50)  NULL ,
	[CMSContractNumber]     varchar(20)  NULL ,
	[ClaimFormType]      	varchar(5)  NULL ,
	[BillTypeCode]       	varchar(5)  NULL ,
	[ClaimTypeInd] 	varchar(5)  NULL ,
	[ClaimStatus]        	varchar(5)  NULL ,
	[DetailServiceDate]	 	varchar(25) NULL ,
	[ClaimEntryDate]	 	varchar(25) NULL ,
	--[ClaimUpdatedDate]   	varchar(25) NULL ,
	[ClaimProcessDate] 		varchar(25) NULL ,
	[ClaimReceivedDate]   	varchar(25) NULL ,
	[ClaimTotalChargeAmount]	varchar(15)  NULL ,
	[ClaimAllowedAmount]    varchar(15)  NULL ,
	[CheckDate]          varchar(25)  NULL ,
	[ClaimFinalizedDate]      varchar(25)  NULL ,
	[CoinsuranceAmt]     varchar(15) NULL ,
	[DeductibleAmt]      varchar(15)  NULL ,
	[CopayAmt]           varchar(15) NULL ,
	[OtherPrimaryPayerAllowedAmt] varchar(20)  NULL ,
	[OtherHealthPlan]     varchar(100)  NULL ,
	[ClaimWeight]        bigint  NOT NULL  Default 0,
	[ClaimSource]        varchar(10)  NULL ,
	[AdmissionDate]      varchar(25)  NULL ,
	[ServiceFacilityNPI] varchar(30)  NULL ,
	[ServiceFacilityID]  varchar(50)  NULL ,
	[ServiceFacilityLocation] varchar(100)  NULL ,
	[ServiceFacilityAddress1] varchar(255)  NULL ,
	[ServiceFacilityAddress2] varchar(255)  NULL ,
	[ServiceFacilityCity] varchar(100)  NULL ,
	[ServiceFacilityState] varchar(2)  NULL ,
	[ServiceFacilityZip] varchar(10)  NULL ,
	[ServiceFacilityCountry] varchar(10)  NULL ,
	[RenderingProviderID] varchar(50)  NULL ,
	[RenderingProviderNPI] varchar(20)  NULL ,
	[RenderingProviderTIN] varchar(20)  NULL ,
	[RenderingProviderSpecialtyCode] varchar(20)  NULL ,
	[BillingProviderID]  varchar(50)  NULL ,
	[BillingProviderTIN] varchar(20)  NULL ,
	[BillingProviderTaxonomy] varchar(30)  NULL ,
	[BillingProviderAddress1] varchar(255)  NULL ,
	[BillingProviderAddress2] varchar(255)  NULL ,
	[BillingProviderCity] varchar(100)  NULL ,
	[BillingProviderState] varchar(2)  NULL ,
	[BillingProviderZip] varchar(10)  NULL ,
	[BillingProviderCountry] varchar(10)  NULL ,
	--[AttendingProviderID] varchar(20)  NULL ,
	[AttendingProviderNPI] varchar(20)  NULL ,
	[PlaceOfService]     varchar(5)  NULL ,	
	[DischargeStatusCode] varchar(5)  NULL ,
	[DischargeDate]      varchar(25)  NULL ,
	--[AllowedAmt]         decimal(9,2)  NULL ,
	[MSDRG]           varchar(5)  NULL ,
	[MSDRG2] varchar(5)  NULL ,
	[ICDVersion]         varchar(5)  NULL ,
	[PrimaryDiagCode]    varchar(10)  NULL ,
	[AdmitDiagCode]      varchar(10)  NULL ,
	[DiagCode2]          varchar(10)  NULL ,
	[DiagCode3]          varchar(10)  NULL ,
	[DiagCode4]          varchar(10)  NULL ,
	[DiagCode5]          varchar(10)  NULL ,
	[DiagCode6]          varchar(10)  NULL ,
	[DiagCode7]          varchar(10)  NULL ,
	[DiagCode8]          varchar(10)  NULL ,
	[DiagCode9]          varchar(10)  NULL ,
	[DiagCode10]         varchar(10)  NULL ,
	[DiagCode11]         varchar(10)  NULL ,
	[DiagCode12]         varchar(10)  NULL ,
	[DiagCode13]         varchar(10)  NULL ,
	[DiagCode14]         varchar(10)  NULL ,
	[DiagCode15]         varchar(10)  NULL ,
	[DiagCode16]         varchar(10)  NULL ,
	[DiagCode17]         varchar(10)  NULL ,
	[DiagCode18]         varchar(10)  NULL ,
	[DiagCode19]         varchar(10)  NULL ,
	[DiagCode20]         varchar(10)  NULL ,
	[DiagCode21]         varchar(10)  NULL ,
	[DiagCode22]         varchar(10)  NULL ,
	[DiagCode23]         varchar(10)  NULL ,
	[DiagCode24]         varchar(10)  NULL ,
	[DiagCode25]         varchar(10)  NULL ,
	[DiagCode26]         varchar(10)  NULL ,
	[DiagCode27]         varchar(10)  NULL ,
	[DiagCode28]         varchar(10)  NULL ,
	[DiagCode29]         varchar(10)  NULL ,
	[DiagCode30]         varchar(10)  NULL ,
	[DiagCode31]         varchar(10)  NULL ,
	[DiagCode32]         varchar(10)  NULL ,
	[DiagCode33]         varchar(10)  NULL ,
	[DiagCode34]         varchar(10)  NULL ,
	[DiagCode35]         varchar(10)  NULL ,
	[DiagCode36]         varchar(10)  NULL ,
	[DiagCode37]         varchar(10)  NULL ,
	[DiagCode38]         varchar(10)  NULL ,
	[AdmitPOA]           varchar(5)  NULL ,
	[PrimaryPOA]         varchar(5)  NULL ,
	[PrimaryProcCode]    varchar(10)  NULL ,
	[PrimaryProcCodeDate] varchar(25)  NULL ,
	[ProcCode2]          varchar(10)  NULL ,
	[ProcCode2Date]      varchar(25)  NULL ,
	[ProcCode3]          varchar(10)  NULL ,
	[ProcCode3Date]      varchar(25)  NULL ,
	[ProcCode4]          varchar(10)  NULL ,
	[ProcCode4Date]      varchar(25)  NULL ,
	[ProcCode5]          varchar(10)  NULL ,
	[ProcCode5Date]      varchar(25)  NULL ,
	[ProcCode6]          varchar(10)  NULL ,
	[ProcCode6Date]      varchar(25)  NULL ,
	[ProcCode7]          varchar(10)  NULL ,
	[ProcCode7Date]      varchar(25)  NULL ,
	[ProcCode8]          varchar(10)  NULL ,
	[ProcCode8Date]      varchar(25)  NULL ,
	[ProcCode9]          varchar(10)  NULL ,
	[ProcCode9Date]      varchar(25)  NULL ,
	[ProcCode10]         varchar(10)  NULL ,
	[ProcCode10Date]     varchar(25)  NULL ,
	[ProcCode11]         varchar(10)  NULL ,
	[ProcCode11Date]     varchar(25)  NULL ,
	[ProcCode12]         varchar(10)  NULL ,
	[ProcCode12Date]     varchar(25)  NULL ,
	[ProcCode13]         varchar(10)  NULL ,
	[ProcCode13Date]     varchar(25)  NULL ,
	[ProcCode14]         varchar(10)  NULL ,
	[ProcCode14Date]     varchar(25)  NULL ,
	[ProcCode15]         varchar(10)  NULL ,
	[ProcCode15Date]     varchar(25)  NULL ,
	[ProcCode16]         varchar(10)  NULL ,
	[ProcCode16Date]     varchar(25)  NULL ,
	[ProcCode17]         varchar(10)  NULL ,
	[ProcCode17Date]     varchar(25)  NULL ,
	[ProcCode18]         varchar(10)  NULL ,
	[ProcCode18Date]     varchar(25)  NULL ,
	[ProcCode19]         varchar(10)  NULL ,
	[ProcCode19Date]     varchar(25)  NULL ,
	[ProcCode20]         varchar(10)  NULL ,
	[ProcCode20Date]     varchar(25)  NULL ,
	[ProcCode21]         varchar(10)  NULL ,
	[ProcCode21Date]     varchar(25)  NULL ,
	[ProcCode22]         varchar(10)  NULL ,
	[ProcCode22Date]     varchar(25)  NULL ,
	[ProcCode23]         varchar(10)  NULL ,
	[ProcCode23Date]     varchar(25)  NULL ,
	[ProcCode24]         varchar(10)  NULL ,
	[ProcCode24Date]     varchar(25)  NULL ,
	[ProcCode25]         varchar(10)  NULL ,
	[ProcCode26]         varchar(10)  NULL ,
	[ProcCode27]         varchar(10)  NULL ,
	[ProcCode28]         varchar(10)  NULL ,
	[ProcCode29]         varchar(10)  NULL ,
	[ProcCode30]         varchar(10)  NULL ,
	[ProcCode31]         varchar(10)  NULL ,
	[ProcCode32]         varchar(10)  NULL ,
	[ProcCode33]         varchar(10)  NULL ,
	[ProcCode34]         varchar(10)  NULL ,
	[ProcCode35]         varchar(10)  NULL ,
	[ProcCode36]         varchar(10)  NULL ,
	[ProcCode37]         varchar(10)  NULL ,
	[ProcCode38]         varchar(10)  NULL ,	
	[OccurCode1]         varchar(50)  NULL ,
	[OccurCode2]         varchar(50)  NULL ,
	[OccurCode3]         varchar(50)  NULL ,
	[OccurCode4]         varchar(50)  NULL ,
	[OccurCode5]         varchar(50)  NULL ,
	[OccurCode6]         varchar(50)  NULL ,
	[OccurCode7]         varchar(50)  NULL ,
	[OccurCode8]         varchar(50)  NULL ,
	[OccurCode9]         varchar(50)  NULL ,
	[OccurCode10]        varchar(50)  NULL ,
	[OccurCode11]        varchar(50)  NULL ,
	[OccurCode12]        varchar(50)  NULL ,
	[OccurCode13]        varchar(50)  NULL ,
	[OccurCode14]        varchar(50)  NULL ,
	[OccurCode15]        varchar(50)  NULL ,
	[OccurCode16]        varchar(50)  NULL ,
	[OccurCode17]        varchar(50)  NULL ,
	[OccurCode18]        varchar(50)  NULL ,
	[OccurCode19]        varchar(50)  NULL ,
	[OccurCode20]        varchar(50)  NULL ,
	[OccurCode21]        varchar(50)  NULL ,
	[OccurCode22]        varchar(50)  NULL ,
	[OccurCode23]        varchar(50)  NULL ,
	[OccurCode24]        varchar(50)  NULL ,
	[StatementFromDate]  varchar(25)   NULL,
	[StatementToDate]  	 varchar(25)   NULL,
	[SCCFClaimIdentifier]  varchar(255)   NULL,
	[UniquePersonKey]  varchar(50)   NULL,
	[ProductID]  varchar(50)   NULL,
	[CVX]  varchar(5)   NULL,
	[DaysDenied]  varchar(20)   NULL,
	[RoomBoard]  varchar(5)   NULL,
	[RRUUnitsofService]  varchar(20)   NULL,
	[MajorSurgery]  varchar(5)   NULL,
	[LocationID]  varchar(50)   NULL,
	[PCPIndicator]  varchar(5)   NULL,
	[ClaimSourceInd]  varchar(5)   NULL,
	[EyeExamResult]  varchar(50)   NULL,
	[SourceName]  varchar(100)   NULL,
	[AlternateClaimIdentifier1]  varchar(255)   NULL,
	[PaidDate]  varchar(25)   NULL,
	[PayStatus]  varchar(5)   NULL,
	[IsDeniedDuplicate]  varchar(1)   NULL,
	[IsSplitClaim]  varchar(1)   NULL,
	[BenefitNetworkID]  varchar(25)   NULL,
	[ClaimSubmitterID]  varchar(25)   NULL,
	[BenefitCategoryID]  varchar(10)   NULL,
	[NetworkEligibilityIndicator]  varchar(10)   NULL,
	[BillingProviderNPI]  varchar(30)   NULL,	
	[BillingProviderName]  varchar(100)   NULL,
	[ProviderTaxonamy]  varchar(30)   NULL,
	[PayeeType]  varchar(2)   NULL,
	[BenefitPlanID]  varchar(20)   NULL,
	[ReferringProviderID]  varchar(30)   NULL,
	[ReferringProviderNPI]  varchar(30)   NULL,
	[ReferringProviderTaxonomy]  varchar(30)   NULL,
	[PlanBenefitPackage]  varchar(5)   NULL,
	[LengthOfStay]  varchar(4)   NULL
) 