/*replace the "devidap1" schema with client names for each environment:
DEV - devidap1, devidap2
QA - qaidap1,qaidap2
STAGE - bcbsks, bcbsm, vba, nbnd
PROD - bcbsks, bcbsm, vba, nbnd
*/
CREATE TABLE [devidap1].[Member] (
  [ClientID]	varchar(20)	NULL
 ,[FileID]	bigint	NULL
 ,[LoadDateTime]	datetime2(7)	NULL
 ,[FileLayoutID]	int	NULL
 ,[FileLayoutDescription]	varchar(255)	NULL
 ,[TransactionType]	varchar(255)	NULL
 ,[UniquePersonKey]	varchar(50)	NULL
 ,[PlanMemberID]	varchar(50)	NULL
 ,[SubscriberID]	varchar(50)	NULL
 ,[StartDate]	date	NULL
 ,[EndDate]	date	NULL
 ,[SubscriberFlag]	varchar(1)	NULL
 ,[BeneficiaryID]	varchar(30)	NULL
 ,[FullName]	varchar(255)	NULL
 ,[LastName]	varchar(255)	NULL
 ,[FirstName]	varchar(255)	NULL
 ,[MiddleInitial]	varchar(255)	NULL
 ,[Title]	varchar(25)	NULL
 ,[Suffix]	varchar(25)	NULL
 ,[GateWayMemberStatus]	varchar(40)	NULL
 ,[AlternateMemberID]	varchar(50)	NULL
 ,[EnrolleeUniqueID]	varchar(50)	NULL
 ,[DateofBirth]	date	NULL
 ,[DeceasedDate]	date	NULL
 ,[Gender]	varchar(10)	NULL
 ,[MemberSSN]	varchar(12)	NULL
 ,[PermanentAddressLine1]	varchar(100)	NULL
 ,[PermanentAddressLine2]	varchar(100)	NULL
 ,[PermanentAddressLine3]	varchar(100)	NULL
 ,[PermanentCity]	varchar(100)	NULL
 ,[PermanentCounty]	varchar(100)	NULL
 ,[PermanentState]	varchar(2)	NULL
 ,[PermanentSCC]	varchar(5)	NULL
 ,[PermanentZipCode]	varchar(10)	NULL
 ,[MailingAddressLine1]	varchar(100)	NULL
 ,[MailingAddressLine2]	varchar(100)	NULL
 ,[MailingAddressLine3]	varchar(100)	NULL
 ,[MailingCity]	varchar(100)	NULL
 ,[MailingState]	varchar(2)	NULL
 ,[MailingZipCode]	varchar(10)	NULL
 ,[MailingCounty]	varchar(100)	NULL
 ,[BillingAddressLine1]	varchar(100)	NULL
 ,[BillingAddressLine2]	varchar(100)	NULL
 ,[BillingAddressLine3]	varchar(100)	NULL
 ,[BillingCity]	varchar(100)	NULL
 ,[BillingState]	varchar(2)	NULL
 ,[BillingZipCode]	varchar(10)	NULL
 ,[PhoneNumber]	varchar(30)	NULL
 ,[AlternatePhoneNumber]	varchar(30)	NULL
 ,[Email]	varchar(120)	NULL
 ,[EmergencyContactName]	varchar(200)	NULL
 ,[EmergencyContactRelationship]	varchar(100)	NULL
 ,[EmergencyContactPhoneNumber]	varchar(30)	NULL
 ,[IDCardTriggerflag]	varchar(1)	NULL
 ,[EndangeredMemberFlag]	varchar(1)	NULL
 ,[OOAProcess]	varchar(1)	NULL
 ,[OOASource]	varchar(50)	NULL
 ,[DateofMove]	date	NULL
 ,[MoveDeadline]	date	NULL
 ,[MedicaidID]	varchar(15)	NULL
 ,[MedicarePartAEffDate]	date	NULL
 ,[MedicarePartAEndDate]	date	NULL
 ,[MedicarePartBEffDate]	date	NULL
 ,[MedicarePartBEndDate]	date	NULL
 ,[MedicarePartDEffDate]	date	NULL
 ,[MedicarePartDEndDate]	date	NULL
 ,[Languagecode]	varchar(5)	NULL
 ,[AlternativeFormatLargePrint]	varchar(1)	NULL
 ,[AlternativeFormatBraille]	varchar(1)	NULL
 ,[AlternativeFormatAudioTape]	varchar(1)	NULL
 ,[Fax]	varchar(30)	NULL
 ,[InLEPProcessStatus]	varchar(1)	NULL
 ,[POAName]	varchar(200)	NULL
 ,[POAAddress1]	varchar(100)	NULL
 ,[POAAddress2]	varchar(100)	NULL
 ,[POAAddress3]	varchar(100)	NULL
 ,[POACity]	varchar(100)	NULL
 ,[POACounty]	varchar(100)	NULL
 ,[POAState]	varchar(2)	NULL
 ,[POAZipCode]	varchar(10)	NULL
 ,[POAPhoneNumber]	varchar(30)	NULL
 ,[POARelationShip]	varchar(50)	NULL
 ,[RaceCode]	varchar(255)	NULL
 ,[RaceDataSource]	varchar(2)	NULL
 ,[ikaUniqueID]	varchar(11)	NULL
 ,[FamilyLinkIndicator]	varchar(20)	NULL
 ,[InPremiumDelinquencyProcess]	varchar(1)	NULL
 ,[ThirdPartyLiabilityEffDate]	date	NULL
 ,[ThirdPartyLiabilityTrnDate]	date	NULL
 ,[OwedPremium]	varchar(25)	NULL
 ,[CaretakerFirstName]	varchar(100)	NULL
 ,[CaretakerLastName]	varchar(100)	NULL
 ,[CaretakerMiddleInitial]	varchar(1)	NULL
 ,[EthnicityCode]	varchar(255)	NULL
 ,[EthnicityDatasource]	varchar(2)	NULL
 ,[SpokenLanguage]	varchar(2)	NULL
 ,[SpokenLanguagesourcecode]	varchar(2)	NULL
 ,[WrittenLanguageCode]	varchar(2)	NULL
 ,[WrittenLanguageSourcecode]	varchar(2)	NULL
 ,[OtherLanguage]	varchar(2)	NULL
 ,[OtherLanguageSourcecode]	varchar(2)	NULL
 ,[USCitizen]	varchar(1)	NULL
 ,[AlternateKey1]	varchar(200)	NULL
 ,[AlternateKey2]	varchar(200)	NULL
 ,[AlternateKey3]	varchar(200)	NULL
 ,[AlternateKey4]	varchar(200)	NULL
 ,[AlternateKey5]	varchar(200)	NULL
 ,[AlternateKey6]	varchar(200)	NULL
 ,[AlternateKey7]	varchar(200)	NULL
 ,[AlternateKey8]	varchar(200)	NULL
 ,[AlternateKey9]	varchar(200)	NULL
 ,[AlternateKey10]	varchar(200)	NULL
 ,[MaskedMemberID]	varchar(250)	NULL
 ,[EnrolleeEducation]	varchar(100)	NULL
 ,[EnrolleeEmployment]	varchar(100)	NULL
 ,[FullRowHash]	varchar(255)	NOT NULL DEFAULT('')
 ,[ProductID]	varchar(100)	NULL
)