/*replace the "devidap1" schema with client names for each environment:
DEV - devidap1, devidap2
QA - qaidap1,qaidap2
STAGE - bcbsks, bcbsm
PROD - bcbsks, bcbsm
*/
CREATE TABLE [devidap1].[MMR] 
(
	LoadDateTime datetime2(7) NOT NULL DEFAULT '0001-01-01 00:00:00',
	FileID       bigint  NOT NULL,
	ClientID     varchar(20)  NOT NULL,
	FileLayoutID       integer  NOT NULL,
	FileLayoutDescription  varchar(255)  NOT NULL,	
	ContractNumber varchar(5),
	RunDate int,
	PaymentDate int,
	BeneficiaryID varchar(12),
	Surname varchar(7),
	FirstInitial varchar(1),
	GenderCode varchar(1),
	DateOfBirth int,
	AgeGroup varchar(4),
	StateAndCountyCode varchar(5),
	OutOfAreaIndicator varchar(1),
	PartAEntitlement varchar(1),
	PartBEntitlement varchar(1),
	Hospice varchar(1),
	Esrd varchar(1),
	AgedDisabledMsp varchar(1),
	Institutional varchar(1),
	NHC varchar(1),
	NewMedicareBeneficiaryMedicaidStatusFlag varchar(1),
	LTIFlag varchar(1),
	MedicaidIndicator varchar(1),
	PIPDCG varchar(2),
	DefaultRiskFactorCode varchar(1),
	RiskAdjusterFactorA decimal(6,4),
	RiskAdjusterFactorB decimal(6,4),
	NumberOfPaymentAdjustmentMonthsPartA int,
	NumberOfPaymentAdjustmentMonthsPartB int,
	AdjustmentReasonCode varchar(2),
	PaymentAdjustmentStartDate int,
	PaymentAdjustmentEndDate int,
	DemographicPaymentAdjustmentRatePartA decimal(8,2),
	DemographicPaymentAdjustmentRatePartB decimal(8,2),
	MonthlyPaymentAdjustmentAmountRateA decimal(8,2),
	MonthlyPaymentAdjustmentAmountRateB decimal(8,2),
	LisPremiumSubsidy decimal(7,2),
	EsrdMspFlag varchar(1),
	MtmAddOn decimal(9,2),
	MedicaidFullPartialNondual varchar(1),
	RiskAdjustmentAgeGroup varchar(4),
	PreviousDisableRatio decimal(7,4),
	DeMinimisPartD varchar(1),
	ConcurrentEnrollment varchar(1),
	PlanBenefitPackageID varchar(3),
	RaceCode varchar(1),
	RiskAdjustmentFactorTypeCode varchar(2),
	FrailtyIndicator varchar(1),
	OriginalReasonForEntitlementCode varchar(1),
	LagIndicator varchar(1),
	SegmentNumber varchar(3),
	EnrollmentSource varchar(1),
	EGHPFlag varchar(1),
	PartCBasicPremiumPartAAmount decimal(7,2),
	PartCBasicPremiumPartBAmount decimal(7,2),
	RebateForPartACostSharingReduction decimal(7,2),
	RebateForPartBCostSharingReduction decimal(7,2),
	RebateForOtherPartAMandatorySupplementalBenefits decimal(7,2),
	RebateForOtherPartBMandatorySupplementalBenefits decimal(7,2),
	RebateForPartBPremiumReductionPartAAmount decimal(7,2),
	RebateForPartBPremiumReductionPartBAmount decimal(7,2),
	RebateForPartDSupplementalBenefitsPartAAmount decimal(7,2),
	RebateForPartDSupplementalBenefitsPartBAmount decimal(7,2),
	TotalPartAMAPayment decimal(9,2),
	TotalPartBMAPayment decimal(9,2),
	TotalMAPaymentAmount decimal(10,2),
	PartDRAFactor decimal(6,4),
	PartDLowIncomeIndicator varchar(1),
	PartDLowIncomeMultiplier decimal(6,4),
	PartDLongTermInstitutionalIndicator varchar(1),
	PartDLongTermInstitutionalMultiplier decimal(6,4),
	RebateForPartDBasicPremiumReduction decimal(7,2),
	PartDBasicPremiumAmount decimal(7,2),
	PartDDirectSubsidyMonthlyPaymentAmount decimal(9,2),
	ReinsuranceSubsidyAmount decimal(9,2),
	LowIncomeSubsidyCostSharingAmount decimal(9,2),
	TotalPartDPayment decimal(10,2),
	NumberOfPaymentAdjustmentMonthsPartD int,
	PACEPremiumAddOn decimal(9,2),
	PACECostSharingAddOn decimal(9,2),
	PartCFrailtyScoreFactor decimal(6,4),
	MSPFactor decimal(6,4),
	MSPReductionReductionAdjustmentAmountPartA decimal(9,2),
	MSPReductionReductionAdjustmentAmountPartB decimal(9,2),
	MedicaidDualStatusCode varchar(2),
	PartDCoverageGapDiscountAmount decimal(7,2),
	PartDRiskAdjustmentFactorType varchar(2),
	DefaultPartDRiskAdjustmentFactorCode varchar(1),
	PartARiskAdjustedMonthlyRateAmountForPaymentAdjustment decimal(8,2),
	PartBRiskAdjustedMonthlyRateAmountForPaymentAdjustment decimal(8,2),
	PartDDirectSubsidyMonthlyRateAmountForPaymentAdjustment decimal(8,2),
	CleanupID varchar(10)	
)