CREATE TABLE [devidap1].[platinum_dimprovider] 
(
	 [providerKey] int NULL
	,[providerID] nvarchar(100) NULL
	,[effectiveStartDate] date NULL
	,[effectiveEndDate] date NULL
	,[isCurrent] int NULL
	,[npi] nvarchar(50) NULL
	,[tin] nvarchar(50) NULL
	,[lastName] nvarchar(300) NULL
	,[firstName] nvarchar(300) NULL
	,[middleName] nvarchar(100) NULL
	,[phoneNumber] nvarchar(60) NULL
	,[address1] nvarchar(510) NULL
	,[address2] nvarchar(510) NULL
	,[city] nvarchar(200) NULL
	,[state] nvarchar(4) NULL
	,[zipCode] nvarchar(20) NULL
	,[practiceCode] nvarchar(100) NULL
	,[practiceName] nvarchar(510) NULL
	,[providerOrgCode] nvarchar(100) NULL
	,[providerOrgName] nvarchar(510) NULL
	,[providerSpecialtyDescription] nvarchar(200) NULL
	,[taxonomyCode1] nvarchar(20) NULL
	,[hpSpecialtyCode1] nvarchar(4) NULL
	,[advProviderSpecialtyCode1] nvarchar(20) NULL
	,[taxonomyCode2] nvarchar(20) NULL
	,[hpSpecialtyCode2] nvarchar(4) NULL
	,[advProviderSpecialtyCode2] nvarchar(20) NULL
	,[taxonomyCode3] nvarchar(20) NULL
	,[hpSpecialtyCode3] nvarchar(4) NULL
	,[advProviderSpecialtyCode3] nvarchar(20) NULL
	,[taxonomyCode4] nvarchar(20) NULL
	,[hpSpecialtyCode4] nvarchar(4) NULL
	,[advProviderSpecialtyCode4] nvarchar(20) NULL
	,[taxonomyCode5] nvarchar(20) NULL
	,[hpSpecialtyCode5] nvarchar(4) NULL
	,[advProviderSpecialtyCode5] nvarchar(20) NULL
	,[isPrescribePrivilege] nvarchar(20) NULL
	,[providerDEA] nvarchar(50) NULL
	,[payerID] nvarchar(50) NULL
	,[isContracted] nvarchar(20) NULL
	,[providerHAI] nvarchar(20) NULL
	,[hospitalID] nvarchar(200) NULL
	,[isExcludedFromProviderReporting] nvarchar(20) NULL
	,[altProvReporting1] nvarchar(300) NULL
	,[altProvReporting2] nvarchar(300) NULL
	,[altProvReporting3] nvarchar(300) NULL
	,[altProvReporting4] nvarchar(300) NULL
	,[altProvReporting5] nvarchar(300) NULL
	,[altProvReporting6] nvarchar(300) NULL
	,[altProvReporting7] nvarchar(300) NULL
	,[altProvReporting8] nvarchar(300) NULL
	,[altProvReporting9] nvarchar(300) NULL
	,[altProvReporting10] nvarchar(300) NULL
	,[programType] nvarchar(200) NULL
	,[practiceTargetedStatus] nvarchar(200) NULL
	,[ProductID] nvarchar(100) NULL
	,[ProviderType] nvarchar(100) NULL
)