CREATE TABLE [devidap1].[platinum_dimmember] (
		[memberKey] bigint NULL
		,[BISInternalPersonID] nvarchar(30) NULL
		,[uniquePersonKey] nvarchar(20) NULL
		,[planMemberID] nvarchar(20) NULL
		,[subscriberID] nvarchar(20) NULL
		,[beneficiaryID] nvarchar(30) NULL
		,[lastName] nvarchar(300) NULL
		,[firstName] nvarchar(300) NULL
		,[middleInitial] nvarchar(255) NULL
		,[enrolleeUniqueID] nvarchar(50) NULL
		,[dateofBirth] date NULL
		,[deceasedDate] nvarchar(20) NULL
		,[gender] nvarchar(10) NULL
		,[permanentAddressLine1] nvarchar(600) NULL
		,[permanentAddressLine2] nvarchar(600) NULL
		,[permanentCity] nvarchar(100) NULL
		,[permanentCounty] nvarchar(20) NULL
		,[permanentState] nvarchar(20) NULL
		,[permanentZipCode] nvarchar(20) NULL
		,[mailingAddressLine1] nvarchar(600) NULL
		,[mailingAddressLine2] nvarchar(600) NULL
		,[mailingCity] nvarchar(100) NULL
		,[mailingState] nvarchar(20) NULL
		,[mailingZipCode] nvarchar(20) NULL
		,[mailingCounty] nvarchar(20) NULL
		,[phoneNumber] nvarchar(20) NULL
		,[email] nvarchar(255) NULL
		,[medicaidID] nvarchar(20) NULL
		,[fax] nvarchar(30) NULL
		,[raceCode] nvarchar(20) NULL
		,[raceDataSource] nvarchar(20) NULL
		,[caretakerFirstName] nvarchar(300) NULL
		,[caretakerLastName] nvarchar(300) NULL
		,[caretakerMiddleInitial] nvarchar(100) NULL
		,[ethnicityCode] nvarchar(20) NULL
		,[ethnicityDatasource] nvarchar(20) NULL
		,[spokenLanguage] nvarchar(20) NULL
		,[spokenLanguagesourcecode] nvarchar(20) NULL
		,[writtenLanguageCode] nvarchar(20) NULL
		,[writtenLanguageSourcecode] nvarchar(20) NULL
		,[otherLanguage] nvarchar(20) NULL
		,[otherLanguageSourcecode] nvarchar(20) NULL
		,[isUSCitizen] nvarchar(20) NULL
		,[alternateKey1] nvarchar(200) NULL
		,[alternateKey2] nvarchar(200) NULL
		,[alternateKey3] nvarchar(200) NULL
		,[alternateKey4] nvarchar(200) NULL
		,[alternateKey5] nvarchar(200) NULL
		,[alternateKey6] nvarchar(200) NULL
		,[alternateKey7] nvarchar(200) NULL
		,[alternateKey8] nvarchar(200) NULL
		,[alternateKey9] nvarchar(200) NULL
		,[alternateKey10] nvarchar(200) NULL
		,[maskedMemberID] nvarchar(250) NULL
		,[enrolleeEducation] nvarchar(100) NULL
		,[enrolleeEmployment] nvarchar(100) NULL
		,[effectiveStartDate] date NULL
		,[effectiveEndDate] date NULL
		,[isCurrent] bit NULL
		,[ProductID] nvarchar(100) NULL
)