CREATE TABLE [devidap1].[ProviderRollup] (
	 ClientID VARCHAR(20) NULL
	,LoadDateTime DATETIME2(7) NULL
	,FileID BIGINT NULL
	,FileLayoutID INT NULL
	,FileLayoutDescription VARCHAR(255) NULL
	,RenderingProviderID VARCHAR(50) NULL
	,RenderingProviderNPI VARCHAR(25) NULL
	,Tier1BillingProviderID	VARCHAR(50) NULL
	,Tier1BillingProviderNPI VARCHAR(25) NULL
	,Tier1BillingProviderTIN VARCHAR(25) NULL
	,Tier1Description VARCHAR(255) NULL
	,Tier2ID VARCHAR(255) NULL
	,Tier2Description VARCHAR(255) NULL
	,Tier3ID VARCHAR(255) NULL
	,Tier3Description VARCHAR(255) NULL
	,Tier4ID VARCHAR(255) NULL
	,Tier4Description VARCHAR(255) NULL
	,Tier5ID VARCHAR(255) NULL
	,Tier5Description VARCHAR(255) NULL
	,Tier6ID VARCHAR(255) NULL
	,Tier6Description VARCHAR(255) NULL
	,Tier7ID VARCHAR(255) NULL
	,Tier7Description VARCHAR(255) NULL
	,Tier8ID VARCHAR(255) NULL
	,Tier8Description VARCHAR(255) NULL
	,Tier9ID VARCHAR(255) NULL
	,Tier9Description VARCHAR(255) NULL
	,Tier10ID VARCHAR(255) NULL
	,Tier10Description VARCHAR(255) NULL
	,StartDate DATE NULL
	,EndDate DATE NULL
	,AltProvReporting1 VARCHAR(255) NULL
	,AltProvReporting2 VARCHAR(255) NULL
	,AltProvReporting3 VARCHAR(255) NULL
	,AltProvReporting4 VARCHAR(255) NULL
	,AltProvReporting5 VARCHAR(255) NULL
	,AltProvReporting6 VARCHAR(255) NULL
	,AltProvReporting7 VARCHAR(255) NULL
	,AltProvReporting8 VARCHAR(255) NULL
	,AltProvReporting9 VARCHAR(255) NULL 
	,AltProvReporting10 VARCHAR(255) NULL
)
