/*replace the "devidap1" schema with client names for each environment:
DEV - devidap1, devidap2
QA - qaidap1,qaidap2
STAGE - bcbsks, bcbsm
PROD - bcbsks, bcbsm
*/
CREATE TABLE [devidap1].[RAPSReturn] 
(
	LoadDateTime datetime2(7) NOT NULL DEFAULT '0001-01-01 00:00:00',
	FileID       bigint  NOT NULL,
	ClientID     varchar(20)  NOT NULL,
	FileLayoutID       integer  NOT NULL,
	FileLayoutDescription  	varchar(255)  NOT NULL,	
	RecordType     varchar(5),
	SeqNo     varchar(7),
	SeqErrorCode     varchar(3),
	PatientControlNumber     varchar(40),
	BeneficiaryID     varchar(12),
	MBIErrorCode     varchar(3),
	PatientDOB     date,
	DOBErrorCode     varchar(5),
	ProviderType1     varchar(2),
	FromDate1     date,
	ThruDate1     date,
	DeleteInd1     varchar(1),
	DiagnosisCode1     varchar(7),
	DiagClstrError1     varchar(3),
	DiagClstrError1A     varchar(3),
	ProviderType2     varchar(2),
	FromDate2     date,
	ThruDate2     date,
	DeleteInd2     varchar(1),
	DiagnosisCode2     varchar(7),
	DiagClstrError2     varchar(3),
	DiagClstrError2A     varchar(3),
	ProviderType3     varchar(2),
	FromDate3     date,
	ThruDate3     date,
	DeleteInd3     varchar(1),
	DiagnosisCode3     varchar(7),
	DiagClstrError3     varchar(3),
	DiagClstrError3A     varchar(3),
	ProviderType4     varchar(2),
	FromDate4     date,
	ThruDate4     date,
	DeleteInd4     varchar(1),
	DiagnosisCode4     varchar(7),
	DiagClstrError4     varchar(3),
	DiagClstrError4A     varchar(3),
	ProviderType5     varchar(2),
	FromDate5     date,
	ThruDate5     date,
	DeleteInd5     varchar(1),
	DiagnosisCode5     varchar(7),
	DiagClstrError5     varchar(3),
	DiagClstrError5A     varchar(3),
	ProviderType6     varchar(2),
	FromDate6     date,
	ThruDate6     date,
	DeleteInd6     varchar(1),
	DiagnosisCode6     varchar(7),
	DiagClstrError6     varchar(3),
	DiagClstrError6A     varchar(3),
	ProviderType7     varchar(2),
	FromDate7     date,
	ThruDate7     date,
	DeleteInd7     varchar(1),
	DiagnosisCode7     varchar(7),
	DiagClstrError7     varchar(3),
	DiagClstrError7A     varchar(3),
	ProviderType8     varchar(2),
	FromDate8     date,
	ThruDate8     date,
	DeleteInd8     varchar(1),
	DiagnosisCode8     varchar(7),
	DiagClstrError8     varchar(3),
	DiagClstrError8A     varchar(3),
	ProviderType9     varchar(2),
	FromDate9     date,
	ThruDate9     date,
	DeleteInd9     varchar(1),
	DiagnosisCode9     varchar(7),
	DiagClstrError9     varchar(3),
	DiagClstrError9A     varchar(3),
	ProviderType10     varchar(2),
	FromDate10     date,
	ThruDate10     date,
	DeleteInd10     varchar(1),
	DiagnosisCode10     varchar(7),
	DiagClstrError10     varchar(3),
	DiagClstrError10A     varchar(3),
	CorrectedHICNumber     varchar(25),
	RiskAssessmentCode1     varchar(1),
	RiskAssessmentCodeError1     varchar(3),
	RiskAssessmentCode2     varchar(1),
	RiskAssessmentCodeError2     varchar(3),
	RiskAssessmentCode3     varchar(1),
	RiskAssessmentCodeError3     varchar(3),
	RiskAssessmentCode4     varchar(1),
	RiskAssessmentCodeError4     varchar(3),
	RiskAssessmentCode5     varchar(1),
	RiskAssessmentCodeError5     varchar(3),
	RiskAssessmentCode6     varchar(1),
	RiskAssessmentCodeError6     varchar(3),
	RiskAssessmentCode7     varchar(1),
	RiskAssessmentCodeError7     varchar(3),
	RiskAssessmentCode8     varchar(1),
	RiskAssessmentCodeError8     varchar(3),
	RiskAssessmentCode9     varchar(1),
	RiskAssessmentCodeError9     varchar(3),
	RiskAssessmentCode10     varchar(1),
	RiskAssessmentCodeError10     varchar(3),
	SubmitterID     varchar(6),
	RapsFileID     varchar(10),
	TransactionDate     varchar(8),
	PlanNo     varchar(5)
)