/*replace the "devidap1" schema with client names for each environment:
DEV - devidap1, devidap2
QA - qaidap1,qaidap2
STAGE - bcbsks, bcbsm, vba, nbnd
PROD - bcbsks, bcbsm, vba, nbnd
*/
CREATE TABLE [devidap1].[SpanOther] 
(
	 [ClientID]	varchar(20) NULL
	,[FileID]	bigint NULL
	,[LoadDateTime]	datetime2(7) NULL
	,[FileLayoutID]	int NULL
	,[FileDescription]	varchar(255) NULL
	,[SpanType]	varchar(10) NULL
	,[SubscriberID]	varchar(50) NULL
	,[StartDate]	date NULL
	,[EndDate]	date NULL
	,[BeneficiaryID]  varchar(255) NULL
	,[AddressType]  varchar(25) NULL
	,[MemberPermanentAddress1]	varchar(255) NULL
	,[MemberPermanentAddress2]	varchar(255) NULL
	,[MemberPermanentAddress3]	varchar(255) NULL
	,[MemberPermanentCity]	    varchar(255) NULL
	,[MemberPermanentCounty]	varchar(255) NULL
	,[MemberPermanentState]   	varchar(255) NULL
	,[MemberPermanentSCC]	    varchar(255) NULL
	,[MemberPermanentZipCode]	varchar(255) NULL
	,[MemberMailingAddress1]	varchar(255) NULL
	,[MemberMailingAddress2]    varchar(255) NULL
	,[MemberMailingAddress3]	varchar(255) NULL
	,[MemberMailingCity]        varchar(255) NULL
	,[MemberMailingState]       varchar(255) NULL
	,[MemberMailingZipCode]     varchar(255) NULL
	,[MemberBillingAddress1]    varchar(255) NULL
	,[MemberBillingAddress2]    varchar(255) NULL
	,[MemberBillingAddress3]    varchar(255) NULL
	,[MemberBillingCity]        varchar(255) NULL
	,[MemberBillingState]       varchar(255) NULL
	,[MemberBillingZipCode]     varchar(255) NULL
	,[BrokerName] varchar(255) NULL
	,[BrokerCode] varchar(255) NULL
	,[BrokerAssociation] varchar(255) NULL
	,[CreditableCoverageFlag] varchar(255) NULL
	,[LEPNumberofUncoveredMonths] varchar(255) NULL
	,[PartDLEPAmount] varchar(255) NULL
	,[PartDLEPWaivedAmount] varchar(255) NULL
	,[PartDLEPSubsidyAmount] varchar(255) NULL
	,[LEPSource] varchar(255) NULL
	,[CurrentLISPremiumSubsidy] varchar(255) NULL
	,[PartDLISSubsidyLevel] varchar(255) NULL
	,[PartDLISCopayCategory] varchar(255) NULL
	,[LISSourceCode] varchar(255) NULL
	,[Segment] varchar(255) NULL
	,[GroupID] varchar(255) NULL
	,[Subgroup] varchar(255) NULL
	,[ClassID] varchar(255) NULL
	,[PlanCode] varchar(255) NULL
	,[SuffixStartDate] varchar(255) NULL
	,[SuffixEndDate] varchar(255) NULL
	,[PlanRider] varchar(255) NULL
	,[RiderCode] varchar(255) NULL
	,[PaymentMethodType] varchar(255) NULL
	,[PremiumWithholdOption] varchar(255) NULL
	,[NameofAccountHolder] varchar(255) NULL
	,[AccountNumber] varchar(255) NULL
	,[BankRoutingNumber] varchar(255) NULL
	,[BankAccountType] varchar(255) NULL
	,[CreditCardType] varchar(255) NULL
	,[CreditCardAccountHolderName] varchar(255) NULL
	,[CreditCardNumber] varchar(255) NULL
	,[CreditCardSecurityCode] varchar(255) NULL
	,[CreditCardExpirationDate] varchar(255) NULL
	,[HospiceFlag] varchar(255) NULL
	,[MedicaidFlag] varchar(255) NULL
	,[WorkingAgedFlag] varchar(255) NULL
	,[InstitutionalFlag] varchar(255) NULL
	,[ESRDFlag] varchar(255) NULL
	,[TransplantFlag] varchar(255) NULL
	,[DialysisFlag] varchar(255) NULL
	,[DisabledFlag] varchar(255) NULL
	,[PlanOverrideIndicator] varchar(255) NULL
	,[NHCFlag] varchar(255) NULL
    ,[EGHPFlag] varchar(255) NULL
	,[COBUpdateDate] varchar(255) NULL
	,[NameofOtherCoverage] varchar(255) NULL
	,[SubscriberIDofOtherCoverage] varchar(255) NULL
	,[GroupIDofOtherCoverage] varchar(255) NULL
	,[KindofOtherInsurance] varchar(255) NULL
	,[NameofOtherInsuranceCompany] varchar(255) NULL
	,[PlanMemberID]	varchar(50) NULL
	,[MedicaidID]	varchar(50) NULL
	,[CMSContractNumber]	varchar(50) NULL
	,[ProductLine]	varchar(255) NULL
	,[ProductID]  varchar(255) NULL
	,[SecondProductID]  varchar(255) NULL
	,[Spanvalue]	varchar(20) NULL
	,[AdditionalSpanValue]  varchar(20) NULL
	,[PlanBenefitPackage]  varchar(30) NULL
	,[ECDSFlag] varchar(1) NULL
	,[AlphaPrefix] varchar(30) NULL
	,[Pharmacy] varchar(1) NULL
	,[Dental] varchar(1) NULL
	,[Vision] varchar(1) NULL
	,[MH] varchar(1) NULL
	,[MHIP] varchar(1) NULL
	,[MHDN] varchar(1) NULL
	,[MHAMB] varchar(1) NULL
	,[CD] varchar(1) NULL
    ,[CDIP] varchar(1) NULL
	,[CDDN] varchar(1) NULL
	,[CDAMB] varchar(1) NULL
	,[SNPFlag] varchar(1) NULL
	,[SNPEnrolleeType] INT NULL
	,[IssuerID] varchar(50) NULL
	,[MetalLevel] varchar(15) NULL
	,[CostSharingVariant] varchar(5) NULL
	,[MarketCoverage] varchar(5) NULL
	,[CSREligibilityFlag] varchar(1) NULL
    ,[MemberEnrollmentQHPState] varchar(2) NULL
	,[AlternateMemberKey1] varchar(255) NULL
	,[AlternateMemberKey2] varchar(255) NULL
	,[AlternateMemberKey3] varchar(255) NULL
	,[AlternateMemberKey4] varchar(255) NULL
	,[AlternateMemberKey5] varchar(255) NULL
	,[PlanEmployeeFlag] varchar(5) NULL
	,[SourcefileID] varchar(255) NULL
	,[DualStatusCode] varchar(255) NULL
	,[MedicaidRecordType] varchar(255) NULL
	,[SPAPType] varchar(255) NULL
	,[SPAPID] varchar(255) NULL 
    ,[TransplantFlagType] NVARCHAR(50) NULL
)