/*replace the "devidap1" schema with client names for each environment:
DEV - devidap1, devidap2
QA - qaidap1,qaidap2
STAGE - bcbsks, bcbsm, vba, nbnd
PROD - bcbsks, bcbsm, vba, nbnd
*/
CREATE TABLE [devidap1].[VisionClaimLine] (
  GeneratedVisionClaimsUniqueKey varchar(255) NOT NULL,
  FileID bigint NOT NULL,
  DetailServiceDate varchar(25) NULL,
  ClaimNumber varchar(100) NULL,
  ClaimLineNumber varchar(5) NOT NULL,
  LineServiceFrom date NOT NULL,
  LineServiceToDate date NOT NULL,
  ProcCode varchar(10) NULL,
  ProcCodeType varchar(10) NULL,
  ProcMod1 varchar(5) NULL,
  ProcMod2 varchar(5) NULL,
  ProcMod3 varchar(5) NULL,
  ProcMod4 varchar(5) NULL,
  ProcCode1  varchar(10)   Null,
  ProcCode1Type  varchar(10)   Null,
  ProcCode1Mod1  varchar(5)   Null,
  NDCCodeList varchar(255) NULL,
  Quantity varchar(20) NULL,
  UnitType varchar(10) NULL,
  DiagCode1 varchar(10) NULL,
  DiagCode2 varchar(10) NULL,
  DiagCode3 varchar(10) NULL,
  DiagCode4 varchar(10) NULL,
  DiagCode5 varchar(10) NULL,
  DiagCode6 varchar(10) NULL,
  DiagCode7 varchar(10) NULL,
  DiagCode8 varchar(10) NULL,
  DiagCode9 varchar(10) NULL,
  DiagCode10 varchar(10) NULL,
  DiagCode11 varchar(10) NULL,
  DiagCode12 varchar(10) NULL,
  DiagCode13 varchar(10) NULL,
  DiagCode14 varchar(10) NULL,
  DiagCode15 varchar(10) NULL,
  DiagCode16 varchar(10) NULL,
  DiagCode17 varchar(10) NULL,
  DiagCode18 varchar(10) NULL,
  DiagCode19 varchar(10) NULL,
  DiagCode20 varchar(10) NULL,
  DiagCode21 varchar(10) NULL,
  DiagCode22 varchar(10) NULL,
  DiagCode23 varchar(10) NULL,
  DiagCode24 varchar(10) NULL,
  DiagCode25 varchar(10) NULL,
  DiagCode26 varchar(10) NULL,
  DiagCode27 varchar(10) NULL,
  DiagCode28 varchar(10) NULL,
  DiagCode29 varchar(10) NULL,
  DiagCode30 varchar(10) NULL,
  DiagCode31 varchar(10) NULL,
  DiagCode32 varchar(10) NULL,
  DiagCode33 varchar(10) NULL,
  DiagCode34 varchar(10) NULL,
  DiagCode35 varchar(10) NULL,
  DiagCode36 varchar(10) NULL,
  DiagCode37 varchar(10) NULL,
  DiagCode38 varchar(10) NULL,
  RevenueCode varchar(5) NULL
)