CREATE TABLE #clientCode.consolidated_aca_memberenrollment (
 ClientID  string
,FileID  int
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,UniquePersonKey  string
,PlanMemberID  string
,BeneficiaryID  string
,MedicaidID  string
,StartDate date
,EndDate date
,CMSContractNumber  string
,ProductLine  string
,ProductID  string
,SubscriberID  string
,SecondProductID  string
,AdditionalSpanValue  string
,PBP  string
,ECDSFlag  string
,AlphaPrefix  string
,Pharmacy  string
,Dental  string
,Vision  string
,MH  string
,MHIP  string
,MHDN  string
,MHAMB  string
,CD  string
,CDIP  string
,CDDN  string
,CDAMB  string
,Hospice  string
,SNP  string
,SNPEnrolleeType  int
,IssuerID  string
,MetalLevel  string
,CostSharingVariant  string
,MarketCoverage  string
,CSREligibility  string
,MemberEnrollmentQHPState  string
,LongTermInstitution  string
,PlanEmployee  string
,MedicaidExpansionQHPEnrollee  int
,MemberGroupCode  string
,AltSpanReporting1  string
,AltSpanReporting2  string
,AltSpanReporting3  string
,AltSpanReporting4  string
,AltSpanReporting5  string
,AltSpanReporting6  string
,AltSpanReporting7  string
,AltSpanReporting8  string
,AltSpanReporting9  string
,AltSpanReporting10  string
,Segment  string
,HealthPlanClassID  string
,HealthPlanCode  string
,DisenrollmentReasonCode  string
,SignatureDate  string
,CSNPDisenrollmentEffDate  string
,ElectionType  string
,TermReasonCode  string
,CommPlanID string
,PrimarySubFlag string
,RelationshipToSubscriber string
,RateAreaID string
,PlanPremiumAmt string
,InExchangeFlag string
) USING delta LOCATION '/mnt/#clientCode/consolidated/ACA/Data/MemberEnrollment'