CREATE TABLE #clientCode.consolidated_ma_starsclinicalpharmacy (
    ClientID string
    ,FileID bigint
    ,LoadDateTime timestamp
    ,FileLayoutID int
    ,FileLayoutDescription string
    ,MBI string
    ,MemberID string
    ,DOB date
    ,Gender string
    ,LIS string
    ,EnrollmentStart date
    ,EnrollmentEnd date
    ,DualEligible string
    ,Disability string
    ,DaysInIPDiab string
    ,DaysInSNFDiab string
    ,DiabPDCDenominator string
    ,DiabPDCNumerator string
    ,DiabPDCRate string
    ,DiabPDCDenominatorUnadj string
    ,DiabPDCNumeratorUnadj string
    ,DiabPDCRateUnadj string
    ,DiabNumeratorflag string
    ,DaysInIPRAS string
    ,DaysInSNFRAS string
    ,RASPDCDenominator string
    ,RASPDCNumerator string
    ,RASPDCRate string
    ,RASPDCDenominatorUnadj string
    ,RASPDCNumeratorUnadj string
    ,RASPDCRateUnadj string
    ,RASNumeratorflag string
    ,DaysInIPStatin string
    ,DaysInSNFStatin string
    ,StatinPDCDenominator string
    ,StatinPDCNumerator string
    ,StatinPDCRate string
    ,StatinPDCDenominatorUnadj string
    ,StatinPDCNumeratorUnadj string
    ,StatinPDCRateUnadj string
    ,StatinNumeratorflag string
    ,SUPDNumeratorFlag string
    ,RunID string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/StarsClinicalPharmacy'