CREATE TABLE #clientCode.consolidated_aca_medicalclaimheader (
 GeneratedMedicalClaimsUniqueKey  string
,ClaimNumber  string
,ClaimProcessDate date
,MemberAcctNumber  string
,MemberMedRecNumber  string
,ClaimReceivedDate date
,WithholdAmt  string
,PaidDate date
,ClaimPaidAmt  string
,AdmissionDate date
,DischargeDate date
,StatementCoversFromDt date
,StatementCoversToDt date
,BillTypeCode  string
,DaysDenied  int
,ClaimTypeInd  string
,AdmitDiagCode  string
,ICDVersion  string
,PrimaryDiagCode  string
,DiagCode2  string
,DiagCode3  string
,DiagCode4  string
,DiagCode5  string
,DiagCode6  string
,DiagCode7  string
,DiagCode8  string
,DiagCode9  string
,DiagCode10  string
,DiagCode11 BIGINT
,DiagCode12  string
,DiagCode13  string
,DiagCode14  string
,DiagCode15  string
,DiagCode16  string
,DiagCode17  string
,DiagCode18  string
,DiagCode19  string
,DiagCode20  string
,DiagCode21  string
,DiagCode22  string
,DiagCode23  string
,DiagCode24  string
,DiagCode25  string
,DiagCode26  string
,PrimaryProcCode  string
,PrimaryProcCodeDate date
,PrimaryProcCode2  string
,PrimaryProcCode2Date date
,PrimaryProcCode3  string
,PrimaryProcCode3Date date
,PrimaryProcCode4  string
,PrimaryProcCode4Date  date
,PrimaryProcCode5  string
,PrimaryProcCode5Date date
,PrimaryProcCode6  string
,PrimaryProcCode6Date date
,PrimaryProcCode7  string
,PrimaryProcCode7Date date
,PrimaryProcCode8  string
,PrimaryProcCode8Date date
,PrimaryProcCode9  string
,PrimaryProcCode9Date date
,PrimaryProcCode10  string
,PrimaryProcCode10Date  date
,PrimaryProcCode11  string
,PrimaryProcCode11Date  date
,PrimaryProcCode12  string
,PrimaryProcCode12Date  date
,PrimaryProcCode13  string
,PrimaryProcCode13Date  date
,PrimaryProcCode14  string
,PrimaryProcCode14Date  date
,PrimaryProcCode15  string
,PrimaryProcCode15Date  date
,PrimaryProcCode16  string
,PrimaryProcCode16Date  date
,PrimaryProcCode17  string
,PrimaryProcCode17Date  date
,PrimaryProcCode18  string
,PrimaryProcCode18Date  date
,PrimaryProcCode19  string
,PrimaryProcCode19Date  date
,PrimaryProcCode20  string
,PrimaryProcCode20Date  date
,PrimaryProcCode21  string
,PrimaryProcCode21Date  date
,PrimaryProcCode22  string
,PrimaryProcCode22Date  date
,PrimaryProcCode23  string
,PrimaryProcCode23Date  date
,PrimaryProcCode24  string
,PrimaryProcCode24Date  date
,ClaimTotalChargeAmount  string
,BillingProviderID  string
,BillingProviderNPI  string
,BillingProviderTIN  string
,AttendingProviderNPI  string
,DischargeStatusCode  string
,OriginalClaimNumber  string
,ProductID  string
,ClientID  string
,LoadDateTime date
,FileID  string
,FileLayoutID  string
,FileLayoutDescription  string
,ClaimStatus  string
,UniquePersonKey string
) USING delta LOCATION '/mnt/#clientCode/consolidated/ACA/Data/MedicalClaimHeader'