CREATE TABLE #clientCode.consolidated_ma_rapsreturn (
 ClientID  string
,FileID  int
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,RecordType  string
,SeqNo  string
,SeqErrorCode  string
,PatientControlNumber  string
,BeneficiaryID  string
,MBIErrorCode  string
,PatientDOB date
,DOBErrorCode  string
,ProviderType1  string
,FromDate1 date
,ThruDate1 date
,DeleteInd1  string
,DiagnosisCode1  string
,DiagClstrError1  string
,DiagClstrError1A  string
,ProviderType2  string
,FromDate2 date
,ThruDate2 date
,DeleteInd2  string
,DiagnosisCode2  string
,DiagClstrError2  string
,DiagClstrError2A  string
,ProviderType3  string
,FromDate3 date
,ThruDate3 date
,DeleteInd3  string
,DiagnosisCode3  string
,DiagClstrError3  string
,DiagClstrError3A  string
,ProviderType4  string
,FromDate4  string
,ThruDate4 date
,DeleteInd4 date
,DiagnosisCode4  string
,DiagClstrError4  string
,DiagClstrError4A  string
,ProviderType5  string
,FromDate5 date
,ThruDate5 date
,DeleteInd5  string
,DiagnosisCode5  string
,DiagClstrError5  string
,DiagClstrError5A  string
,ProviderType6  string
,FromDate6 date
,ThruDate6 date
,DeleteInd6  string
,DiagnosisCode6  string
,DiagClstrError6  string
,DiagClstrError6A  string
,ProviderType7  string
,FromDate7 date
,ThruDate7 date
,DeleteInd7  string
,DiagnosisCode7  string
,DiagClstrError7  string
,DiagClstrError7A  string
,ProviderType8  string
,FromDate8 date
,ThruDate8 date
,DeleteInd8  string
,DiagnosisCode8  string
,DiagClstrError8  string
,DiagClstrError8A  string
,ProviderType9  string
,FromDate9 date
,ThruDate9 date
,DeleteInd9  string
,DiagnosisCode9  string
,DiagClstrError9  string
,DiagClstrError9A  string
,ProviderType10  string
,FromDate10 date
,ThruDate10 date
,DeleteInd10  string
,DiagnosisCode10  string
,DiagClstrError10  string
,DiagClstrError10A  string
,CorrectedHICNumber  string
,RiskAssessmentCode1  string
,RiskAssessmentCodeError1  string
,RiskAssessmentCode2  string
,RiskAssessmentCodeError2  string
,RiskAssessmentCode3  string
,RiskAssessmentCodeError3  string
,RiskAssessmentCode4  string
,RiskAssessmentCodeError4  string
,RiskAssessmentCode5  string
,RiskAssessmentCodeError5  string
,RiskAssessmentCode6  string
,RiskAssessmentCodeError6  string
,RiskAssessmentCode7  string
,RiskAssessmentCodeError7  string
,RiskAssessmentCode8  string
,RiskAssessmentCodeError8  string
,RiskAssessmentCode9  string
,RiskAssessmentCodeError9  string
,RiskAssessmentCode10  string
,RiskAssessmentCodeError10  string
,SubmitterID  string
,RapsFileID  string
,TransactionDate  string
,PlanNo  string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/RAPSReturn'