CREATE TABLE #clientCode.consolidated_ma_medicalclaimheader (
 GeneratedMedicalClaimsUniqueKey  string
,ClientID  string
,FileID  int
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,ClaimNumber  string
,OriginalClaimNumber  string
,BeneficiaryID  string
,PlanMemberID  string
,CMSContractNumber  string
,ClaimFormType  string
,BillTypeCode  string
,ClaimTypeInd  string
,ClaimStatus  string
,DetailServiceDate  string
,ClaimEntryDate  string
,ClaimProcessDate timestamp
,ClaimReceivedDate  string
,ClaimTotalChargeAmount  string
,ClaimAllowedAmount  string
,CheckDate  string
,ClaimFinalizedDate  string
,CoinsuranceAmt  string
,DeductibleAmt  string
,CopayAmt  string
,OtherPrimaryPayerAllowedAmt  string
,OtherHealthPlan  string
,ClaimWeight BIGINT
,ClaimSource  string
,AdmissionDate  string
,ServiceFacilityNPI  string
,ServiceFacilityID  string
,ServiceFacilityLocation  string
,ServiceFacilityAddress1  string
,ServiceFacilityAddress2  string
,ServiceFacilityCity  string
,ServiceFacilityState  string
,ServiceFacilityZip  string
,ServiceFacilityCountry  string
,RenderingProviderID  string
,RenderingProviderNPI  string
,RenderingProviderTIN  string
,RenderingProviderSpecialtyCode  string
,BillingProviderID  string
,BillingProviderTIN  string
,BillingProviderTaxonomy  string
,BillingProviderAddress1  string
,BillingProviderAddress2  string
,BillingProviderCity  string
,BillingProviderState  string
,BillingProviderZip  string
,BillingProviderCountry  string
,AttendingProviderNPI  string
,PlaceOfService  string
,DischargeStatusCode  string
,DischargeDate  string
,MSDRG  string
,MSDRG2  string
,ICDVersion  string
,PrimaryDiagCode  string
,AdmitDiagCode  string
,DiagCode2  string
,DiagCode3  string
,DiagCode4  string
,DiagCode5  string
,DiagCode6  string
,DiagCode7  string
,DiagCode8  string
,DiagCode9  string
,DiagCode10  string
,DiagCode11  string
,DiagCode12  string
,DiagCode13  string
,DiagCode14  string
,DiagCode15  string
,DiagCode16  string
,DiagCode17  string
,DiagCode18  string
,DiagCode19  string
,DiagCode20  string
,DiagCode21  string
,DiagCode22  string
,DiagCode23  string
,DiagCode24  string
,DiagCode25  string
,DiagCode26  string
,DiagCode27  string
,DiagCode28  string
,DiagCode29  string
,DiagCode30  string
,DiagCode31  string
,DiagCode32  string
,DiagCode33  string
,DiagCode34  string
,DiagCode35  string
,DiagCode36  string
,DiagCode37  string
,DiagCode38  string
,AdmitPOA  string
,PrimaryPOA  string
,PrimaryProcCode  string
,PrimaryProcCodeDate  string
,ProcCode2  string
,ProcCode2Date  string
,ProcCode3  string
,ProcCode3Date  string
,ProcCode4  string
,ProcCode4Date  string
,ProcCode5  string
,ProcCode5Date  string
,ProcCode6  string
,ProcCode6Date  string
,ProcCode7  string
,ProcCode7Date  string
,ProcCode8  string
,ProcCode8Date  string
,ProcCode9  string
,ProcCode9Date  string
,ProcCode10  string
,ProcCode10Date  string
,ProcCode11  string
,ProcCode11Date  string
,ProcCode12  string
,ProcCode12Date  string
,ProcCode13  string
,ProcCode13Date  string
,ProcCode14  string
,ProcCode14Date  string
,ProcCode15  string
,ProcCode15Date  string
,ProcCode16  string
,ProcCode16Date  string
,ProcCode17  string
,ProcCode17Date  string
,ProcCode18  string
,ProcCode18Date  string
,ProcCode19  string
,ProcCode19Date  string
,ProcCode20  string
,ProcCode20Date  string
,ProcCode21  string
,ProcCode21Date  string
,ProcCode22  string
,ProcCode22Date  string
,ProcCode23  string
,ProcCode23Date  string
,ProcCode24  string
,ProcCode24Date  string
,ProcCode25  string
,ProcCode26  string
,ProcCode27  string
,ProcCode28  string
,ProcCode29  string
,ProcCode30  string
,ProcCode31  string
,ProcCode32  string
,ProcCode33  string
,ProcCode34  string
,ProcCode35  string
,ProcCode36  string
,ProcCode37  string
,ProcCode38  string
,OccurCode1  string
,OccurCode2  string
,OccurCode3  string
,OccurCode4  string
,OccurCode5  string
,OccurCode6  string
,OccurCode7  string
,OccurCode8  string
,OccurCode9  string
,OccurCode10  string
,OccurCode11  string
,OccurCode12  string
,OccurCode13  string
,OccurCode14  string
,OccurCode15  string
,OccurCode16  string
,OccurCode17  string
,OccurCode18  string
,OccurCode19  string
,OccurCode20  string
,OccurCode21  string
,OccurCode22  string
,OccurCode23  string
,OccurCode24  string
,StatementFromDate  string
,StatementToDate  string
,SCCFClaimIdentifier  string
,UniquePersonKey  string
,ProductID  string
,CVX  string
,DaysDenied  string
,RoomBoard  string
,RRUUnitsofService  string
,MajorSurgery  string
,LocationID  string
,PCPIndicator  string
,ClaimSourceInd  string
,EyeExamResult  string
,SourceName  string
,AlternateClaimIdentifier1  string
,PaidDate  string
,PayStatus  string
,IsDeniedDuplicate  string
,IsSplitClaim  string
,BenefitNetworkID  string
,ClaimSubmitterID  string
,BenefitCategoryID  string
,NetworkEligibilityIndicator  string
,BillingProviderNPI  string	
,BillingProviderName  string
,ProviderTaxonamy  string
,PayeeType  string
,BenefitPlanID  string
,ReferringProviderID  string
,ReferringProviderNPI  string
,ReferringProviderTaxonomy  string
,PlanBenefitPackage  string
,LengthOfStay  string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/MedicalClaimHeader'