CREATE TABLE #clientCode.consolidated_aca_pharmacy (
 LoadDateTime string
,FileID string
,FileLayoutID string
,FileLayoutDescription string
,ClientId string
,ClaimNumber string
,ClaimLineNumber string
,UniquePersonKey string
,ClaimProcessDate date
,ClaimStatus string
,ClaimReceivedDate date
,AllowedAmt string
,BillAmt string
,CoInsurance string
,Deductible string
,PaidAmount string
,Quantity double
,PaidDate date
,ClaimPaidAmt string
,LineServiceFrom string
,LineServiceThu string
,ClaimType string
,BillingProviderID string
,BillingProviderNPI string
,RenderingProviderID string
,RenderingProvNPI string
,OriginalClaimNumber string
,PrescriptionReferenceNumber string
,DispensingFee string
,DispensingFeePaid string
,NDCCodeSTD string
,UnitsOfMeasure string
,Units string
,ProductID string
,BeneficiaryID string
,DaysSupply string
,ClaimSourceInd string
,SourceName string
,RXNorm string
,CVX string
,USCCode string
,GPI string
,GPIName string
,DEANumber string
,CoPay string
,DispenseAsWritten string
,MailOrder string
,SalesTax string
,PlaceOfService string
,SuppliesClaim string
,AlternateKey1 string
,AlternateKey2 string
,ProviderSpecialty string
,PlanMemberID string
)  USING delta LOCATION '/mnt/#clientCode/consolidated/ACA/Data/Pharmacy'