CREATE TABLE #clientCode.consolidated_ma_submitted837outboundclaimheader (
    ClientID string
    ,FileID bigint
    ,LoadDateTime date
    ,FileLayoutID integer
    ,FileLayoutDescription string
    ,Submitted837MedicalClaimKey string
    ,EncounterICN string
    ,CMSContractNumber string
    ,BillingProviderLastNameOrOrganizationName string
    ,BillingProviderFirstName string
    ,BillingProviderMiddleName string
    ,BillingProviderNameSuffix string
    ,BillingProviderNPI string
    ,BillingProviderAddressLine1 string
    ,BillingProviderAddressLine2 string
    ,BillingProviderCity string
    ,BillingProviderState string
    ,BillingProviderZip string
    ,BillingProviderTIN string
    ,MemberLastName string
    ,MemberFirstName string
    ,MemberMiddleName string
    ,MemberNameSuffix string
    ,BeneficiaryID string
    ,MemberAddress1 string
    ,MemberAddress2 string
    ,MemberCity string
    ,MemberState string
    ,MemberZip string
    ,MemberCountry string
    ,MemberCountrySubdivision string
    ,MemberDOB string
    ,MemberGender string
    ,PropCasualty string
    ,BilledAmount string
    ,PlaceOfService string
    ,FrequencyTypeCode string
    ,ProviderAcceptAssignmentCode string
    ,BenefitsAssignmentCertIficationIndicator string
    ,ReleaseOfInformationCode string
    ,DelayReasonCode string
    ,HospitalDischargeHour string
    ,PrimaryServiceFromDate string
    ,PrimaryServiceThruDate string
    ,HospitalAdmitDate string
    ,RepricerReceivedDate string
    ,AdmitionTypeCode string
    ,AdmitionSourceCode string
    ,PatientStatusCode string
    ,SuppInfo0101 string
    ,SuppInfo0102 string
    ,SuppInfo0106 string
    ,SuppInfo0201 string
    ,SuppInfo0202 string
    ,SuppInfo0206 string
    ,SuppInfo0301 string
    ,SuppInfo0302 string
    ,SuppInfo0306 string
    ,SuppInfo0401 string
    ,SuppInfo0402 string
    ,SuppInfo0406 string
    ,SuppInfo0501 string
    ,SuppInfo0502 string
    ,SuppInfo0506 string
    ,SuppInfo0601 string
    ,SuppInfo0602 string
    ,SuppInfo0606 string
    ,SuppInfo0701 string
    ,SuppInfo0702 string
    ,SuppInfo0706 string
    ,SuppInfo0801 string
    ,SuppInfo0802 string
    ,SuppInfo0806 string
    ,SuppInfo0901 string
    ,SuppInfo0902 string
    ,SuppInfo0906 string
    ,SuppInfo1001 string
    ,SuppInfo1002 string
    ,SuppInfo1006 string
    ,ContractTypeCd02 string
    ,ContractAmount string
    ,ContractPercentage string
    ,ContractCode string
    ,ContractDiscountPercent string
    ,ContractVersionIdentifier string
    ,ServiceAuthorizationExceptionCode string
    ,ReferralNumber string
    ,AuthorizationNumber string
    ,OriginalClaimNumber string
    ,RepricedClaimReferenceNumber string
    ,AdjustedRepricedReferenceNumber string
    ,InvestigationalDeviceExemptionIdentifier string
    ,TraceNumber string
    ,AutoAccidentState string
    ,ProjectIdentifier string
    ,PeerReviewAuthorizationNumber string
    ,K301 string
    ,K302 string
    ,K303 string
    ,K304 string
    ,K305 string
    ,K306 string
    ,K307 string
    ,K308 string
    ,K309 string
    ,K310 string
    ,Nte0101 string
    ,Nte0102 string
    ,Nte0201 string
    ,Nte0202 string
    ,Nte0301 string
    ,Nte0302 string
    ,Nte0401 string
    ,Nte0402 string
    ,Nte0501 string
    ,Nte0502 string
    ,Nte0601 string
    ,Nte0602 string
    ,Nte0701 string
    ,Nte0702 string
    ,Nte0801 string
    ,Nte0802 string
    ,Nte0901 string
    ,Nte0902 string
    ,Nte1001 string
    ,Nte1002 string
    ,BillNote string
    ,EPSDTReferralConditionIndicator string
    ,EPSDTConditionCode1 string
    ,EPSDTConditionCode2 string
    ,EPSDTConditionCode3 string
    ,PrincipalDiagnosisCode string
    ,PrincDiagPresentOnAdmit string
    ,AdmitDiagnosisCode string
    ,VisitReason01 string
    ,VisitReason02 string
    ,VisitReason03 string
    ,ExternalCauseInjuryDX1 string
    ,ExternalCauseInjuryDXPresent1 string
    ,ExternalCauseInjuryDX2 string
    ,ExternalCauseInjuryDXPresent2 string
    ,ExternalCauseInjuryDX3 string
    ,ExternalCauseInjuryDXPresent3 string
    ,ExternalCauseInjuryDX4 string
    ,ExternalCauseInjuryDXPresent4 string
    ,ExternalCauseInjuryDX5 string
    ,ExternalCauseInjuryDXPresent5 string
    ,ExternalCauseInjuryDX6 string
    ,ExternalCauseInjuryDXPresent6 string
    ,ExternalCauseInjuryDX7 string
    ,ExternalCauseInjuryDXPresent7 string
    ,ExternalCauseInjuryDX8 string
    ,ExternalCauseInjuryDXPresent8 string
    ,ExternalCauseInjuryDX9 string
    ,ExternalCauseInjuryDXPresent9 string
    ,ExternalCauseInjuryDX10 string
    ,ExternalCauseInjuryDXPresent10 string
    ,ExternalCauseInjuryDX11 string
    ,ExternalCauseInjuryDXPresent11 string
    ,ExternalCauseInjuryDX12 string
    ,ExternalCauseInjuryDXPresent12 string
    ,DRGCode string
    ,Diag1 string
    ,PresentOnAdmitInd01 string
    ,Diag2 string
    ,PresentOnAdmitInd02 string
    ,Diag3 string
    ,PresentOnAdmitInd03 string
    ,Diag4 string
    ,PresentOnAdmitInd04 string
    ,Diag5 string
    ,PresentOnAdmitInd05 string
    ,Diag6 string
    ,PresentOnAdmitInd06 string
    ,Diag7 string
    ,PresentOnAdmitInd07 string
    ,Diag8 string
    ,PresentOnAdmitInd08 string
    ,Diag9 string
    ,PresentOnAdmitInd09 string
    ,Diag10 string
    ,PresentOnAdmitInd10 string
    ,Diag11 string
    ,PresentOnAdmitInd11 string
    ,Diag12 string
    ,PresentOnAdmitInd12 string
    ,Diag13 string
    ,PresentOnAdmitInd13 string
    ,Diag14 string
    ,PresentOnAdmitInd14 string
    ,Diag15 string
    ,PresentOnAdmitInd15 string
    ,Diag16 string
    ,PresentOnAdmitInd16 string
    ,Diag17 string
    ,PresentOnAdmitInd17 string
    ,Diag18 string
    ,PresentOnAdmitInd18 string
    ,Diag19 string
    ,PresentOnAdmitInd19 string
    ,Diag20 string
    ,PresentOnAdmitInd20 string
    ,Diag21 string
    ,PresentOnAdmitInd21 string
    ,Diag22 string
    ,PresentOnAdmitInd22 string
    ,Diag23 string
    ,PresentOnAdmitInd23 string
    ,Diag24 string
    ,PresentOnAdmitInd24 string
    ,PrincipalProcedureCode string
    ,PrincipalProcedureDate string
    ,ProcCd01 string
    ,ProcDt01 string
    ,ProcCd02 string
    ,ProcDt02 string
    ,ProcCd03 string
    ,ProcDt03 string
    ,ProcCd04 string
    ,ProcDt04 string
    ,ProcCd05 string
    ,ProcDt05 string
    ,ProcCd06 string
    ,ProcDt06 string
    ,ProcCd07 string
    ,ProcDt07 string
    ,ProcCd08 string
    ,ProcDt08 string
    ,ProcCd09 string
    ,ProcDt09 string
    ,ProcCd10 string
    ,ProcDt10 string
    ,ProcCd11 string
    ,ProcDt11 string
    ,ProcCd12 string
    ,ProcDt12 string
    ,ProcCd13 string
    ,ProcDt13 string
    ,ProcCd14 string
    ,ProcDt14 string
    ,ProcCd15 string
    ,ProcDt15 string
    ,ProcCd16 string
    ,ProcDt16 string
    ,ProcCd17 string
    ,ProcDt17 string
    ,ProcCd18 string
    ,ProcDt18 string
    ,ProcCd19 string
    ,ProcDt19 string
    ,ProcCd20 string
    ,ProcDt20 string
    ,ProcCd21 string
    ,ProcDt21 string
    ,ProcCd22 string
    ,ProcDt22 string
    ,ProcCd23 string
    ,ProcDt23 string
    ,ProcCd24 string
    ,ProcDt24 string
    ,SpanCd01 string
    ,SpanDt01 string
    ,SpanCd02 string
    ,SpanDt02 string
    ,SpanCd03 string
    ,SpanDt03 string
    ,SpanCd04 string
    ,SpanDt04 string
    ,SpanCd05 string
    ,SpanDt05 string
    ,SpanCd06 string
    ,SpanDt06 string
    ,SpanCd07 string
    ,SpanDt07 string
    ,SpanCd08 string
    ,SpanDt08 string
    ,SpanCd09 string
    ,SpanDt09 string
    ,SpanCd10 string
    ,SpanDt10 string
    ,SpanCd11 string
    ,SpanDt11 string
    ,SpanCd12 string
    ,SpanDt12 string
    ,SpanCd13 string
    ,SpanDt13 string
    ,SpanCd14 string
    ,SpanDt14 string
    ,SpanCd15 string
    ,SpanDt15 string
    ,SpanCd16 string
    ,SpanDt16 string
    ,SpanCd17 string
    ,SpanDt17 string
    ,SpanCd18 string
    ,SpanDt18 string
    ,SpanCd19 string
    ,SpanDt19 string
    ,SpanCd20 string
    ,SpanDt20 string
    ,SpanCd21 string
    ,SpanDt21 string
    ,SpanCd22 string
    ,SpanDt22 string
    ,SpanCd23 string
    ,SpanDt23 string
    ,SpanCd24 string
    ,SpanDt24 string
    ,OccurrenceCd01 string
    ,OccurrenceDt01 string
    ,OccurrenceCd02 string
    ,OccurrenceDt02 string
    ,OccurrenceCd03 string
    ,OccurrenceDt03 string
    ,OccurrenceCd04 string
    ,OccurrenceDt04 string
    ,OccurrenceCd05 string
    ,OccurrenceDt05 string
    ,OccurrenceCd06 string
    ,OccurrenceDt06 string
    ,OccurrenceCd07 string
    ,OccurrenceDt07 string
    ,OccurrenceCd08 string
    ,OccurrenceDt08 string
    ,OccurrenceCd09 string
    ,OccurrenceDt09 string
    ,OccurrenceCd10 string
    ,OccurrenceDt10 string
    ,OccurrenceCd11 string
    ,OccurrenceDt11 string
    ,OccurrenceCd12 string
    ,OccurrenceDt12 string
    ,OccurrenceCd13 string
    ,OccurrenceDt13 string
    ,OccurrenceCd14 string
    ,OccurrenceDt14 string
    ,OccurrenceCd15 string
    ,OccurrenceDt15 string
    ,OccurrenceCd16 string
    ,OccurrenceDt16 string
    ,OccurrenceCd17 string
    ,OccurrenceDt17 string
    ,OccurrenceCd18 string
    ,OccurrenceDt18 string
    ,OccurrenceCd19 string
    ,OccurrenceDt19 string
    ,OccurrenceCd20 string
    ,OccurrenceDt20 string
    ,OccurrenceCd21 string
    ,OccurrenceDt21 string
    ,OccurrenceCd22 string
    ,OccurrenceDt22 string
    ,OccurrenceCd23 string
    ,OccurrenceDt23 string
    ,OccurrenceCd24 string
    ,OccurrenceDt24 string
    ,ValueCd01 string
    ,ValueCdAmt01 string
    ,ValueCd02 string
    ,ValueCdAmt02 string
    ,ValueCd03 string
    ,ValueCdAmt03 string
    ,ValueCd04 string
    ,ValueCdAmt04 string
    ,ValueCd05 string
    ,ValueCdAmt05 string
    ,ValueCd06 string
    ,ValueCdAmt06 string
    ,ValueCd07 string
    ,ValueCdAmt07 string
    ,ValueCd08 string
    ,ValueCdAmt08 string
    ,ValueCd09 string
    ,ValueCdAmt09 string
    ,ValueCd10 string
    ,ValueCdAmt10 string
    ,ValueCd11 string
    ,ValueCdAmt11 string
    ,ValueCd12 string
    ,ValueCdAmt12 string
    ,ValueCd13 string
    ,ValueCdAmt13 string
    ,ValueCd14 string
    ,ValueCdAmt14 string
    ,ValueCd15 string
    ,ValueCdAmt15 string
    ,ValueCd16 string
    ,ValueCdAmt16 string
    ,ValueCd17 string
    ,ValueCdAmt17 string
    ,ValueCd18 string
    ,ValueCdAmt18 string
    ,ValueCd19 string
    ,ValueCdAmt19 string
    ,ValueCd20 string
    ,ValueCdAmt20 string
    ,ValueCd21 string
    ,ValueCdAmt21 string
    ,ValueCd22 string
    ,ValueCdAmt22 string
    ,ValueCd23 string
    ,ValueCdAmt23 string
    ,ValueCd24 string
    ,ValueCdAmt24 string
    ,ConditionCd01 string
    ,ConditionCd02 string
    ,ConditionCd03 string
    ,ConditionCd04 string
    ,ConditionCd05 string
    ,ConditionCd06 string
    ,ConditionCd07 string
    ,ConditionCd08 string
    ,ConditionCd09 string
    ,ConditionCd10 string
    ,ConditionCd11 string
    ,ConditionCd12 string
    ,ConditionCd13 string
    ,ConditionCd14 string
    ,ConditionCd15 string
    ,ConditionCd16 string
    ,ConditionCd17 string
    ,ConditionCd18 string
    ,ConditionCd19 string
    ,ConditionCd20 string
    ,ConditionCd21 string
    ,ConditionCd22 string
    ,ConditionCd23 string
    ,ConditionCd24 string
    ,TxCd01 string
    ,TxCd02 string
    ,TxCd03 string
    ,TxCd04 string
    ,TxCd05 string
    ,TxCd06 string
    ,TxCd07 string
    ,TxCd08 string
    ,TxCd09 string
    ,TxCd10 string
    ,TxCd11 string
    ,TxCd12 string
    ,TxCd13 string
    ,TxCd14 string
    ,TxCd15 string
    ,TxCd16 string
    ,TxCd17 string
    ,TxCd18 string
    ,TxCd19 string
    ,TxCd20 string
    ,TxCd21 string
    ,TxCd22 string
    ,TxCd23 string
    ,TxCd24 string
    ,AttendingProviderLastName string
    ,AttendingProviderFirstName string
    ,AttendingProviderMiddleName string
    ,AttendingProviderNameSuffix string
    ,AttendingProviderNPI string
    ,OperatingProviderLastName string
    ,OperatingProviderFirstName string
    ,OperatingProviderMiddleName string
    ,OperatingProviderNameSuffix string
    ,OperatingProviderNPI string
    ,OtherOperatingProviderLastName string
    ,OtherOperatingProviderFirstName string
    ,OtherOperatingProviderMiddleName string
    ,OtherOperatingProviderNameSuffix string
    ,OtherOperatingProviderNPI string
    ,RenderingProviderLastName string
    ,RenderingProviderFirstName string
    ,RenderingProviderMiddleName string
    ,RenderingProviderNameSuffix string
    ,RenderingProviderNPI string
    ,ServiceFacilityName string
    ,ServiceFacilityFirstName string
    ,ServiceFacilityMiddleName string
    ,ServiceFacilityNameSuffix string
    ,ServiceFacilityNPI string
    ,ServiceFacilityAddressLine1 string
    ,ServiceFacilityAddressLine2 string
    ,ServiceFacilityCity string
    ,ServiceFacilityState string
    ,ServiceFacilityZIP string
    ,ReferringProviderLastName string
    ,ReferringProviderFirstName string
    ,ReferringProviderMiddleName string
    ,ReferringProviderNameSuffix string
    ,ReferringProviderNPI string
    ,PayerResponseCd string
    ,PolicyNumber string
    ,PlanName string
    ,ClmAdjGrpCd1 string
    ,ClmAdjReasCd101 string
    ,ClmAdjAmt101 string
    ,ClmAdjQty101 string
    ,ClmAdjReasCd102 string
    ,ClmAdjAmt102 string
    ,ClmAdjQty102 string
    ,ClmAdjReasCd103 string
    ,ClmAdjAmt103 string
    ,ClmAdjQty103 string
    ,ClmAdjReasCd104 string
    ,ClmAdjAmt104 string
    ,ClmAdjQty104 string
    ,ClmAdjReasCd105 string
    ,ClmAdjAmt105 string
    ,ClmAdjQty105 string
    ,ClmAdjReasCd106 string
    ,ClmAdjAmt106 string
    ,ClmAdjQty106 string
    ,ClmAdjGrpCd2 string
    ,ClmAdjReasCd201 string
    ,ClmAdjAmt201 string
    ,ClmAdjQty201 string
    ,ClmAdjReasCd202 string
    ,ClmAdjAmt202 string
    ,ClmAdjQty202 string
    ,ClmAdjReasCd203 string
    ,ClmAdjAmt203 string
    ,ClmAdjQty203 string
    ,ClmAdjReasCd204 string
    ,ClmAdjAmt204 string
    ,ClmAdjQty204 string
    ,ClmAdjReasCd205 string
    ,ClmAdjAmt205 string
    ,ClmAdjQty205 string
    ,ClmAdjReasCd206 string
    ,ClmAdjAmt206 string
    ,ClmAdjQty206 string
    ,ClmAdjGrpCd3 string
    ,ClmAdjReasCd301 string
    ,ClmAdjAmt301 string
    ,ClmAdjQty301 string
    ,ClmAdjReasCd302 string
    ,ClmAdjAmt302 string
    ,ClmAdjQty302 string
    ,ClmAdjReasCd303 string
    ,ClmAdjAmt303 string
    ,ClmAdjQty303 string
    ,ClmAdjReasCd304 string
    ,ClmAdjAmt304 string
    ,ClmAdjQty304 string
    ,ClmAdjReasCd305 string
    ,ClmAdjAmt305 string
    ,ClmAdjQty305 string
    ,ClmAdjReasCd306 string
    ,ClmAdjAmt306 string
    ,ClmAdjQty306 string
    ,ClmAdjGrpCd4 string
    ,ClmAdjReasCd401 string
    ,ClmAdjAmt401 string
    ,ClmAdjQty401 string
    ,ClmAdjReasCd402 string
    ,ClmAdjAmt402 string
    ,ClmAdjQty402 string
    ,ClmAdjReasCd403 string
    ,ClmAdjAmt403 string
    ,ClmAdjQty403 string
    ,ClmAdjReasCd404 string
    ,ClmAdjAmt404 string
    ,ClmAdjQty404 string
    ,ClmAdjReasCd405 string
    ,ClmAdjAmt405 string
    ,ClmAdjQty405 string
    ,ClmAdjReasCd406 string
    ,ClmAdjAmt406 string
    ,ClmAdjQty406 string
    ,ClmAdjGrpCd5 string
    ,ClmAdjReasCd501 string
    ,ClmAdjAmt501 string
    ,ClmAdjQty501 string
    ,ClmAdjReasCd502 string
    ,ClmAdjAmt502 string
    ,ClmAdjQty502 string
    ,ClmAdjReasCd503 string
    ,ClmAdjAmt503 string
    ,ClmAdjQty503 string
    ,ClmAdjReasCd504 string
    ,ClmAdjAmt504 string
    ,ClmAdjQty504 string
    ,ClmAdjReasCd505 string
    ,ClmAdjAmt505 string
    ,ClmAdjQty505 string
    ,ClmAdjReasCd506 string
    ,ClmAdjAmt506 string
    ,ClmAdjQty506 string
    ,PaidAmount string
    ,RemainingPatientLiability string
    ,NonCoveredChargeAmount string
    ,InpatientCoveredDays string
    ,LifetimePsychiatricDays string
    ,ClaimDRGAmount string
    ,MIARemarkCode1 string
    ,ClaimDisproportionateShareAmt string
    ,ClaimMSPPassThroughAmount string
    ,ClaimPPSCapitalAmount string
    ,PPSCapitalFSPDRG string
    ,PPSCapitalHSPDRG string
    ,PPSCapitalDSHDRG string
    ,OldCapitalAmount string
    ,PPSCapitalIMEAmount string
    ,PPSHospitalSpecificDRG string
    ,CostReportDays string
    ,PPSFederalDRG string
    ,PPSCapitalOutlier string
    ,IndirectTeachingAmt string
    ,NonPayableProfCompAmt string
    ,MIARemarkCode2 string
    ,MIARemarkCode3 string
    ,MIARemarkCode4 string
    ,MIARemarkCode5 string
    ,PPSCapitalExceptionAmt string
    ,MOAReimbursementRate string
    ,MOAHCPCSPayableAmt string
    ,MOARemarkCode1 string
    ,MOARemarkCode2 string
    ,MOARemarkCode3 string
    ,MOARemarkCode4 string
    ,MOARemarkCode5 string
    ,ESRDPaymentAmt string
    ,MOANonPayableComponentAmt string
    ,MSPIND string
    ,OtherInsuredLastName string
    ,OtherInsuredFirstName string
    ,OtherInsuredMiddleName string
    ,OtherInsuredSuffix string
    ,OtherSubscriberHICNNumber string
    ,OtherSubscriberAddressLine1 string
    ,OtherSubscriberAddressLine2 string
    ,OtherSubscriberCity string
    ,OtherSubscriberState string
    ,OtherSubscriberZip string
    ,OtherSubscriberCountryCode string
    ,OtherSubscriberCountrySubdivisionCode string
    ,OtherPayerOrganizationName string
    ,OtherPayerPlanID string
    ,OtherPayerAddrLine1 string
    ,OtherPayerAddrLine2 string
    ,OtherPayerCity string
    ,OtherPayerState string
    ,OtherPayerZip string
    ,CheckRemitDt string
    ,OthPayrAdjClaimCtrlNum string
    ,PaidAmountCOB string
    ,RemainPatientLiabilityCOB string
    ,NonCoveredChrargeAmountCOB string
    ,BenefitsAssignmentCertificationIndicatorCOB string
    ,ReleaseOfInformationCodeCOB string
    ,OtherInsuredLastNameCOB string
    ,OtherInsuredFirstNameCOB string
    ,OtherInsuredMiddleNameCOB string
    ,OtherInsuredSuffixCOB string
    ,OtherSubscriberHICNumberCOB string
    ,OtherSubscriberAddressLine1COB string
    ,OtherSubscriberAddressLine2COB string
    ,OtherSubscriberCityCOB string
    ,OtherSubscriberStateCOB string
    ,OtherSubscriberZipCOB string
    ,OtherPayerOrganizationNameCOB string
    ,OtherPayerPayerId string
    ,OtherPayerAddressLine1COB string
    ,OtherPayerAddressLine2COB string
    ,OtherPayerCityCOB string
    ,OtherPayerStateCOB string
    ,OtherPayerZipCOB string
    ,CheckRemitDtCOB string
    ,BillingProviderTaxonomy string
    ,MedicalRecordNumber string
    ,AttendingProviderTaxonomy string
    ,PayToAddressLine1 string
    ,PayToAddressLine2 string
    ,PayToCity string
    ,PayToState string
    ,PayToZip string
    ,BillingProviderContactName string
    ,BillingProviderCommQual1 string
    ,BillingProviderCommNum1 string
    ,BillingProviderCommQual2 string
    ,BillingProviderCommNum2 string
    ,BillingProviderCommQual3 string
    ,BillingProviderCommNum3 string
    ,ProviderSignatureOnFile string
    ,PatientSignatureSourceCode string
    ,AutoAccidentIndicator string
    ,EmploymentAccidentIndicator string
    ,OtherAccidentIndicator string
    ,SpecialProgramCode string
    ,OnsetOfCurrentIllnessOrInjuryDate string
    ,InitialTreatmentDate string
    ,LastSeenDate string
    ,AcuteManifestationDate string
    ,AccidentDate string
    ,LastMenstrualPeriodDate string
    ,LastXRayDate string
    ,HearingAndVisionPrescriptionDate string
    ,DisabilityStartDate string
    ,DisabilityEndDate string
    ,LastWorkedDate string
    ,WorkReturnDate string
    ,AssumedCareDate string
    ,RelinquishedCareDate string
    ,PropertyAndCasualityDateOfFirstCcontact string
    ,MammographyCertificationNumber string
    ,ClinicalLaboratoryImprovementAmendmentNumber string
    ,PatientWeight string
    ,AmbulanceTransportReasonCode string
    ,AmbulanceMiles string
    ,AmbulancePurpose string
    ,AmbulanceStretcher string
    ,PatientConditionCode string
    ,PatientConditionDescription1 string
    ,PatientConditionDescription2 string
    ,AmbulanceCertificationConditionIndicator0102 string
    ,AmbulanceCertificationConditionCode0103 string
    ,AmbulanceCertificationConditionCode0104 string
    ,AmbulanceCertificationConditionCode0105 string
    ,AmbulanceCertificationConditionCode0106 string
    ,AmbulanceCertificationConditionCode0107 string
    ,AmbulanceCertificationConditionIndicator0202 string
    ,AmbulanceCertificationConditionCode0203 string
    ,AmbulanceCertificationConditionCode0204 string
    ,AmbulanceCertificationConditionCode0205 string
    ,AmbulanceCertificationConditionCode0206 string
    ,AmbulanceCertificationConditionCode0207 string
    ,AmbulanceCertificationConditionIndicator0302 string
    ,AmbulanceCertificationConditionCode0303 string
    ,AmbulanceCertificationConditionCode0304 string
    ,AmbulanceCertificationConditionCode0305 string
    ,AmbulanceCertificationConditionCode0306 string
    ,AmbulanceCertificationConditionCode0307 string
    ,Vision0101 string
    ,Vision0102 string
    ,Vision0103 string
    ,Vision0104 string
    ,Vision0105 string
    ,Vision0106 string
    ,Vision0107 string
    ,Vision0201 string
    ,Vision0202 string
    ,Vision0203 string
    ,Vision0204 string
    ,Vision0205 string
    ,Vision0206 string
    ,Vision0207 string
    ,Vision0301 string
    ,Vision0302 string
    ,Vision0303 string
    ,Vision0304 string
    ,Vision0305 string
    ,Vision0306 string
    ,Vision0307 string
    ,HomeboundIndicator string
    ,Anesthesia01 string
    ,Anesthesia02 string
    ,PricingMethodology string
    ,RepriceAllowedAmount string
    ,RepriceSaveAmount string
    ,RepriceOrganizationIndicator string
    ,RepricePerDiemFlat string
    ,RepriceDRGAPGCode string
    ,RepriceDRGAPGAmt string
    ,RejectReasonCode string
    ,PolicyComplianceCode string
    ,ExceptionCode string
    ,SupervisingProviderLastName string
    ,SupervisingProviderFirstName string
    ,SupervisingProviderMiddleName string
    ,SupervisingProviderNameSuffix string
    ,SupervisingProviderNPI string
    ,AmbulancePickupAddressLine1 string
    ,AmbulancePickupAddressLine2 string
    ,AmbulancePickupCity string
    ,AmbulancePickupState string
    ,AmbulancePickupZip string
    ,AmbulanceDropoffAddrLine1 string
    ,AmbulanceDropoffAddrLine2 string
    ,AmbulanceDropoffCity string
    ,AmbulanceDropoffState string
    ,AmbulanceDropoffZip string
    ,CoordinationOfBenefitsCode string
    ,RenderingProviderTaxonomy string
    ,PrimaryCareProviderFirstName string
    ,PrimaryCareProviderMiddleName string
    ,PrimaryCareProviderLastName string
    ,PrimaryCareProviderSuffix string
    ,PrimaryCareProviderNPI string
)  USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/Submitted837OutboundClaimHeader'