CREATE TABLE #clientCode.consolidated_aca_pcpattribution (
 FileId  int
,ClientId  string
,FilelayoutID  int
,FileLayoutDescription  string
,LoadDateTime date
,UniquePersonKey  string
,PlanMemberID  string
,BeneficiaryID  string
,MedicaidID  string
,StartDate date
,EndDate date
,AdditionalSpanValue  string
,ProviderID  string
,LocationID  string
,AltPCPReporting1  string
,AltPCPReporting2  string
,AltPCPReporting3  string
,AltPCPReporting4  string
,AltPCPReporting5  string
,AltPCPReporting6  string
,AltPCPReporting7  string
,AltPCPReporting8  string
,AltPCPReporting9  string
,AltPCPReporting10  string
,SubscriberID  string
,ProviderAddressSuffix  string
,ProviderEffDate date
,ProviderFirstName  string
,ProviderLastName  string
,ProviderMiddleIntial  string
,MemberFirstName  string
,MemberLastName  string
,MemberMiddleIntial  string
,MemberDOB  string
,CMSContractNumber  string
,ProviderNPI  string
,ProviderTaxonomy  string
,ProviderTIN  string
,ProviderAddress1  string
,ProviderAddress2  string
,ProviderCity  string
,ProviderState  string
,ProviderZip  string
,ProviderCounty  string
,ProviderPhone  string
,ProviderFax  string
,ProviderEmail  string
,BillingProviderID  string
,BillingProviderLastName  string
,BillingProviderMiddleInitial  string
,BillingProviderFirstName  string
,BillingNPI  string
,BillingTIN  string
,BillingProviderAddressLine2  string
,BillingProviderCity  string
,BillingProviderState  string
,BillingProviderZip  string
,BillingProviderCountyCode  string
,BillingProviderPhoneNumber  string
,BillingProviderFaxNumber  string
,BillingProviderEmail  string
,Source  string
,FileGenerationDate date
) USING delta LOCATION '/mnt/#clientCode/consolidated/ACA/Data/PCPAttribution'