CREATE TABLE #clientCode.consolidated_ma_mmr (
 ClientID  string
,FileID  int
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,ContractNumber  string
,RunDate  int
,PaymentDate  int
,BeneficiaryID  string
,Surname  string
,FirstInitial  string
,GenderCode  string
,DateOfBirth  int
,AgeGroup  string
,StateAndCountyCode  string
,OutOfAreaIndicator  string
,PartAEntitlement  string
,PartBEntitlement  string
,Hospice  string
,Esrd  string
,AgedDisabledMsp  string
,Institutional  string
,NHC  string
,NewMedicareBeneficiaryMedicaidStatusFlag  string
,LTIFlag  string
,MedicaidIndicator  string
,PIPDCG  string
,DefaultRiskFactorCode  string
,RiskAdjusterFactorA  string
,RiskAdjusterFactorB  string
,NumberOfPaymentAdjustmentMonthsPartA  string
,NumberOfPaymentAdjustmentMonthsPartB  string
,AdjustmentReasonCode  string
,PaymentAdjustmentStartDate  int
,PaymentAdjustmentEndDate  int
,DemographicPaymentAdjustmentRatePartA  string
,DemographicPaymentAdjustmentRatePartB  string
,MonthlyPaymentAdjustmentAmountRateA  string
,MonthlyPaymentAdjustmentAmountRateB  string
,LisPremiumSubsidy  string
,EsrdMspFlag  string
,MtmAddOn  string
,MedicaidFullPartialNondual  string
,RiskAdjustmentAgeGroup  string
,PreviousDisableRatio  string
,DeMinimisPartD  string
,ConcurrentEnrollment  string
,PlanBenefitPackageID  string
,RaceCode  string
,RiskAdjustmentFactorTypeCode  string
,FrailtyIndicator  string
,OriginalReasonForEntitlementCode  string
,LagIndicator  string
,SegmentNumber  string
,EnrollmentSource  string
,EGHPFlag  string
,PartCBasicPremiumPartAAmount  string
,PartCBasicPremiumPartBAmount  string
,RebateForPartACostSharingReduction  string
,RebateForPartBCostSharingReduction  string
,RebateForOtherPartAMandatorySupplementalBenefits  string
,RebateForOtherPartBMandatorySupplementalBenefits  string
,RebateForPartBPremiumReductionPartAAmount  string
,RebateForPartBPremiumReductionPartBAmount  string
,RebateForPartDSupplementalBenefitsPartAAmount  string
,RebateForPartDSupplementalBenefitsPartBAmount  string
,TotalPartAMAPayment  string
,TotalPartBMAPayment  string
,TotalMAPaymentAmount  string
,PartDRAFactor  string
,PartDLowIncomeIndicator  string
,PartDLowIncomeMultiplier  string
,PartDLongTermInstitutionalIndicator  string
,PartDLongTermInstitutionalMultiplier  string
,RebateForPartDBasicPremiumReduction  string
,PartDBasicPremiumAmount  string
,PartDDirectSubsidyMonthlyPaymentAmount  string
,ReinsuranceSubsidyAmount  string
,LowIncomeSubsidyCostSharingAmount  string
,TotalPartDPayment  string
,NumberOfPaymentAdjustmentMonthsPartD  string
,PACEPremiumAddOn  string
,PACECostSharingAddOn  string
,PartCFrailtyScoreFactor  string
,MSPFactor  string
,MSPReductionReductionAdjustmentAmountPartA  string
,MSPReductionReductionAdjustmentAmountPartB  string
,MedicaidDualStatusCode  string
,PartDCoverageGapDiscountAmount  string
,PartDRiskAdjustmentFactorType  string
,DefaultPartDRiskAdjustmentFactorCode  string
,PartARiskAdjustedMonthlyRateAmountForPaymentAdjustment  string
,PartBRiskAdjustedMonthlyRateAmountForPaymentAdjustment  string
,PartDDirectSubsidyMonthlyRateAmountForPaymentAdjustment  string
,CleanupID  string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/MMR'