CREATE TABLE #clientCode.consolidated_ma_medicalclaimline (
 GeneratedMedicalClaimsUniqueKey  string
,FileID  int
,LineNumber  string
,TypeOfService  string
,PlaceOfService  string
,StatusCode  string
,TotalChargeAmt  string
,AllowedAmt  string
,PurePaymentAmt  string
,InterestAmt  string
,CopayAmt  string
,DeductibleAmt  string
,OOPAmt  string
,CPTTypeService  string
,ServiceFromDate date
,ServiceToDate date
,ProcCodeOrig  string
,ProcMod1Orig  string
,ProcMod2Orig  string
,ProcMod3Orig  string
,ProcMod4Orig  string
,DiagCode1  string
,DiagCode2  string
,DiagCode3  string
,DiagCode4  string
,DiagCode5  string
,DiagCode6  string
,DiagCode7  string
,DiagCode8  string
,DiagCode9  string
,DiagCode10  string
,DiagCode11  string
,DiagCode12  string
,EmergencyInd  string
,RevenueCode  string
,NoncoveredChargesTotal  string
,ProcCode  string
,ProcCodeType  string
,ProcMod1  string
,ProcMod2  string
,ProcMod3  string
,ProcMod4  string
,CategoryNum  string
,MultiCategoryNum  string
,Classification  string
,ClassificationAddtnl  string
,EDIAdjustCodeList  string
,EventCode1  string
,EventCode2  string
,EventCode3  string
,EventCode4  string
,EventCode5  string
,EventCode6  string
,EventCode7  string
,EventCode8  string
,EventCode9  string
,EventCode10  string
,EventCode11  string
,EventCode12  string
,EventCode13  string
,EventCode14  string
,HIPAAAdjustReasonCode  string
,RemitAdviceCode  string
,AuthorizationNum  string
,AuthorizationOverride  string
,NDCCodeList  string
,EncounterFlag  string
,CEOverride  string
,CEAction  string
,CEEventCode  string
,CELineDisp  string
,EPSDT  string
,FamilyPlanInd  string
,TotalChargeAmtOrig  string
,AllowedAmtOrig  string
,ContractAllowedAmt  string
,Quantity  string
,UnitType  string
,UnitRate  string
,COBSavingsAmt  string
,COBPaidAmt  string
,DuplicateInd  string
,DuplicateOption  string
,GLCode  string
,GLDate  string
,Profile  string
,AdjustCode1  string
,AdjustCode2  string
,AdjustCode3  string
,AdjustCode4  string
,AdjustCode5  string
,AdjustCode6  string
,AdjustCode7  string
,AdjustCode8  string
,AdjustCode9  string
,AdjustCode10  string
,AdjustCode11  string
,AdjustCode12  string
,AdjustCode13  string
,AdjustCode14  string
,AdjustCode15  string
,AdjustCode16  string
,AdjustCode17  string
,AdjustCode18  string
,AdjustCode19  string
,AdjustCode20  string
,MemberObligationAmt  string
,OriginalLineNum  string
,PrimaryAllowedAmt  string
,PrimaryDeductAmt  string
,PrimaryCopayAmt  string
,PrimaryCoinsAmt  string
,PrimaryNoncoveredAmt  string
,PrimaryPaidAmt  string
,PrimaryMemberObligation  string
,PrimaryContractAdjstAmt  string
,PrimaryEOBCode  string
,PrimaryDiscount  string
,PricingScheduleCode  string
,WithholdAmt  string
,RebundleAmt  string
,Rider  string
,APCCode  string
,ProcCode1  string
,ProcCode1Type  string
,ProcCode1Mod1  string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/MedicalClaimLine'