CREATE TABLE #clientCode.consolidated_ma_visionclaimline (
 GeneratedVisionClaimsUniqueKey  string
,FileID BIGINT
,DetailServiceDate  string
,ClaimNumber  string
,ClaimLineNumber  string
,LineServiceFrom date
,LineServiceToDate date
,ProcCode  string
,ProcCodeType  string
,ProcMod1  string
,ProcMod2  string
,ProcMod3  string
,ProcMod4  string
,NDCCodeList  string
,Quantity  string
,UnitType  string
,DiagCode1  string
,DiagCode2  string
,DiagCode3  string
,DiagCode4  string
,DiagCode5  string
,DiagCode6  string
,DiagCode7  string
,DiagCode8  string
,DiagCode9  string
,DiagCode10  string
,DiagCode11  string
,DiagCode12  string
,DiagCode13  string
,DiagCode14  string
,DiagCode15  string
,DiagCode16  string
,DiagCode17  string
,DiagCode18  string
,DiagCode19  string
,DiagCode20  string
,DiagCode21  string
,DiagCode22  string
,DiagCode23  string
,DiagCode24  string
,DiagCode25  string
,DiagCode26  string
,DiagCode27  string
,DiagCode28  string
,DiagCode29  string
,DiagCode30  string
,DiagCode31  string
,DiagCode32  string
,DiagCode33  string
,DiagCode34  string
,DiagCode35  string
,DiagCode36  string
,DiagCode37  string
,DiagCode38  string
,RevenueCode  string
,ProcCode1  string
,ProcCode1Type  string
,ProcCode1Mod1  string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/VisionClaimLine'