CREATE TABLE #clientCode.consolidated_ma_visionclaimheader (
 GeneratedVisionClaimsUniqueKey  string
,ClientID  string
,FileID BIGINT
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,UniquePersonKey  string
,PlanMemberID  string
,BeneficiaryID  string
,DiagnosisCodesList  string
,ServiceCode  string
,AdmitDiagnosisCode  string
,BillingProviderID  string
,BillingProviderNPI  string
,BillingProviderAddress1  string
,BillingProviderAddress2  string
,BillingProviderCity  string
,BillingProviderState  string
,BillingProviderZip  string
,BillingProviderRef  string
,RenderingProviderSpecialtyCode  string
,RenderingProviderID  string
,RenderingProviderNPI  string
,ServicingProviderAddress1  string
,ServicingProviderAddress2  string
,ServicingProviderCity  string
,ServicingProviderState  string
,ServicingProviderZip  string
,InsuredPayerName  string
,InsuredID  string
,ClaimStatus  string
,BatchControlNumber  string
,ClaimNumber  string
,OriginalClaimNumber  string
,ProductID  string
,GroupBase  string
,PatientFirstName  string
,PatientLastName  string
,PatientDateOfBirth  string
,PatientGender  string
,ITSAccessFeeAmount  string
,ITSHomeHostInd  string
,BeginningDateOfService  string
,DocControlNumber  string
,SubscriberFirstName  string
,SubscriberLastName  string
,SubscriberMiddleName  string
,SubscriberDateOfBirth  string
,SubscriberGender  string
,SubscriberCompanyCode  string
,COBInd  string
,SubscriberPatientRelCode  string
,SecSubscriberInsurPlanName  string
,SecSubscriberInsurPlanID  string
,SecSubscriberFirstName  string
,SecSubscriberLastName  string
,SecSubscriberMiddleName  string
,SecSubscriberDateOfBirth  string
,SecSubscriberGender  string
,SecSubscriberEmployer  string
,SecSubscriberCOBInd  string
,SecSubscriberPatientRelCode  string
,TerSubscriberDateOfBirth  string
,TerSubscriberGender  string
,PatientMiddleName  string
,PatientAddress1  string
,PatientAddress2  string
,PatientCity  string
,PatientZip  string
,PatientState  string
,PatientRlseOfInfoInd  string
,RenderingProviderTypeCode  string
,BillingProviderTypeCode  string
,PatientCondEmployment  string
,PatientCondAutoAccident  string
,PatientCondAutoAccidentState  string
,PatientCondOtherAccident  string
,PatientCurrentIllnessDate  string
,PatientSimilarIllnessDate  string
,PatientLastWorkedDate  string
,PatientReturnWorkDate  string
,ReferringProviderAuthNumber  string
,AmbulatoryGroup  string
,PatientAccountNumber  string
,AcceptAssgnInd1  string
,ClaimSubmitterID  string
,PhysicianSignature  string
,ClaimICDVersionInd  string
,AttendingProviderNPI  string
,AttendingProviderLastName  string
,AttendingProviderFirstName  string
,AttendingProviderMiddleName  string
,AttendingProviderNameSuffix  string
,OperatingProviderNPI  string
,OperatingProviderLastName  string
,OperatingProviderFirstName  string
,OperatingProviderMiddleName  string
,OperatingProviderNameSuffix  string
,OtherOperatingProviderNPI  string
,OtherOperatingProviderLastName  string
,OtherOperatingProviderFirstName  string
,OtherOperatingProviderMiddleName  string
,OtherOperatingProviderNameSuffix  string
,TypeOfService  string
,PlaceOfService  string
,PaidDate  string
,PaidAmount  string
,PayStatus  string
,CVX  string
,ClaimType  string
,ClaimProcessDate  string
,ClaimReceivedDate date
,PrimaryProcCode  string
,ProcCode2  string
,ProcCode3  string
,ProcCode4  string
,ProcCode5  string
,ProcCode6  string
,ProcCode7  string
,ProcCode8  string
,ProcCode9  string
,ProcCode10  string
,ProcCode11  string
,ProcCode12  string
,ProcCode13  string
,ProcCode14  string
,ProcCode15  string
,ProcCode16  string
,ProcCode17  string
,ProcCode18  string
,ProcCode19  string
,ProcCode20  string
,ProcCode21  string
,ProcCode22  string
,ProcCode23  string
,ProcCode24  string
,ProcCode25  string
,ProcCode26  string
,ProcCode27  string
,ProcCode28  string
,ProcCode29  string
,ProcCode30  string
,ProcCode31  string
,ProcCode32  string
,ProcCode33  string
,ProcCode34  string
,ProcCode35  string
,ProcCode36  string
,ProcCode37  string
,ProcCode38  string
,PCPIndicator  string
,RenderingProviderTIN  string
,DaysDenied  string
,RoomBoard  string
,RRUUnitsofService  string
,MajorSurgery  string
,LocationID  string
,BillTypeCode  string
,MSDRG  string
,MSDRG2  string
,DischargeStatusCode  string
,ClaimSourceIndicator  string
,EyeExamResult  string
,SourceName  string
,SCCFClaimIdentifier  string
,AlternateClaimIdentifier1  string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/VisionClaimHeader'