CREATE TABLE #clientCode.consolidated_ma_emrmedicalclaim (
 ClientID  string
,FileID  string
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,UniquePersonKey  string
,PlanMemberID  string
,BeneficiaryID  string
,RenderingProviderID  string
,BillingProviderID  string
,ClaimNumber  string
,ClaimLineNumber  string
,OriginalClaimNumber  string
,ProductID  string
,ClaimReceivedDate  string
,LineServiceFromDate date
,LineServiceToDate date
,ClaimProcessDate  string
,DetailServiceDate  string
,PlaceOfService  string
,PaidDate  string
,PaidAmt  string
,PayStatus  string
,HCPCSCode  string
,HCPCSModifier  string
,CPTCode  string
,CPTModifier1  string
,CPTModifier2  string
,CPTModifier3  string
,CPTModifier4  string
,CVX  string
,ClaimTypeInd  string
,AdmitDiagCode  string
,DiagCode1  string
,DiagCode2  string
,DiagCode3  string
,DiagCode4  string
,DiagCode5  string
,DiagCode6  string
,DiagCode7  string
,DiagCode8  string
,DiagCode9  string
,DiagCode10  string
,DiagCode11  string
,DiagCode12  string
,DiagCode13  string
,DiagCode14  string
,DiagCode15  string
,DiagCode16  string
,DiagCode17  string
,DiagCode18  string
,DiagCode19  string
,DiagCode20  string
,DiagCode21  string
,DiagCode22  string
,DiagCode23  string
,DiagCode24  string
,DiagCode25  string
,DiagCode26  string
,DiagCode27  string
,DiagCode28  string
,DiagCode29  string
,DiagCode30  string
,DiagCode31  string
,DiagCode32  string
,DiagCode33  string
,DiagCode34  string
,DiagCode35  string
,DiagCode36  string
,DiagCode37  string
,DiagCode38  string
,ProcCode1  string
,ProcCode2  string
,ProcCode3  string
,ProcCode4  string
,ProcCode5  string
,ProcCode6  string
,ProcCode7  string
,ProcCode8  string
,ProcCode9  string
,ProcCode10  string
,ProcCode11  string
,ProcCode12  string
,ProcCode13  string
,ProcCode14  string
,ProcCode15  string
,ProcCode16  string
,ProcCode17  string
,ProcCode18  string
,ProcCode19  string
,ProcCode20  string
,ProcCode21  string
,ProcCode22  string
,ProcCode23  string
,ProcCode24  string
,ProcCode25  string
,ProcCode26  string
,ProcCode27  string
,ProcCode28  string
,ProcCode29  string
,ProcCode30  string
,ProcCode31  string
,ProcCode32  string
,ProcCode33  string
,ProcCode34  string
,ProcCode35  string
,ProcCode36  string
,ProcCode37  string
,ProcCode38  string
,PCPIndicator  string
,RenderingProviderTIN  string
,RenderingProviderSpecialtyCode  string
,RevenueCode  string
,DaysDenied  string
,RoomBoard  string
,RRUUnitsofService  string
,MajorSurgery  string
,LocationID  string
,ICDVersion  string
,ClaimStatus  string
,BillTypeCode  string
,MSDRG  string
,MSDRG2  string
,DischargeStatusCode  string
,ClaimSourceInd  string
,EyeExamResult  string
,SourceName  string
,SCCFClaimIdentifier  string
,AlternateClaimIdentifier1  string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/EMRMedicalClaim'