CREATE TABLE #clientCode.consolidated_ma_submitted837outboundclaimline (
    ClientID string
    ,FileID bigint
    ,LoadDateTime date
    ,FileLayoutID integer
    ,FileLayoutDescription string
    ,Submitted837MedicalClaimKey string
    ,ClaimLineEncounterICN string
    ,ClaimLineNumber integer
    ,RevenueCode1 string
    ,ProcedureCodeQualifier string
    ,ProcedureCode string
    ,CPTMod1 string
    ,CPTMod2 string
    ,CPTMod3 string
    ,CPTMod4 string
    ,ProcedureDescription string
    ,BilledAmountLine string
    ,UnitForMeasurementCode string
    ,ServiceUnitCount string
    ,LineItemDeniedCharge string
    ,SuppInfoLine101 string
    ,SuppInfoLine102 string
    ,SuppInfoLine106 string
    ,SuppInfoLine201 string
    ,SuppInfoLine202 string
    ,SuppInfoLine206 string
    ,SuppInfoLine301 string
    ,SuppInfoLine302 string
    ,SuppInfoLine306 string
    ,SuppInfoLine401 string
    ,SuppInfoLine402 string
    ,SuppInfoLine406 string
    ,SuppInfoLine501 string
    ,SuppInfoLine502 string
    ,SuppInfoLine506 string
    ,SuppInfoLine601 string
    ,SuppInfoLine602 string
    ,SuppInfoLine606 string
    ,SuppInfoLine701 string
    ,SuppInfoLine702 string
    ,SuppInfoLine706 string
    ,SuppInfoLine801 string
    ,SuppInfoLine802 string
    ,SuppInfoLine806 string
    ,SuppInfoLine901 string
    ,SuppInfoLine902 string
    ,SuppInfoLine906 string
    ,SuppInfoLine1001 string
    ,SuppInfoLine1002 string
    ,SuppInfoLine1006 string
    ,DetailServiceFromDate string
    ,DetailServiceThruDate string
    ,LineItemControlNumber string
    ,RepricedLineItemReferenceNumber string
    ,AdjustedRepricedLineItemReferenceNumber string
    ,ServiceTaxAmount string
    ,FacilityTaxAmount string
    ,ThirdPartyOrganizationNotes string
    ,NationalDrugCode string
    ,NationalDrugUnitCount string
    ,DrugUnitOfMeasurementQualifier string
    ,DrugPrescriptionQualifier string
    ,DrugPrescriptionNumber string
    ,ClaimLineOperatingProviderLastName string
    ,ClaimLineOperatingProviderFirstName string
    ,ClaimLineOperatingProviderMiddleName string
    ,ClaimLineOperatingProviderNameSuffix string
    ,ClaimLineOperatingProviderNPI string
    ,ClaimLineOtherOperatingProviderLastName string
    ,ClaimLineOtherOperatingProviderFirstName string
    ,ClaimLineOtherOperatingProviderMiddleName string
    ,ClaimLineOtherOperatingProviderNameSuffix string
    ,ClaimLineOtherOperatingProviderNPI string
    ,ClaimLineRenderingProviderLastName string
    ,ClaimLineRenderingProviderFirstName string
    ,ClaimLineRenderingProviderMiddleName string
    ,ClaimLineRenderingProviderNameSuffix string
    ,ClaimLineRenderingProviderNPI string
    ,ClaimLineReferringProviderLastName string
    ,ClaimLineReferringProviderFirstName string
    ,ClaimLineReferringProviderMiddleName string
    ,ClaimLineReferringProviderNameSuffix string
    ,ClaimLineReferringProviderNPI string
    ,OtherPayerPrimaryID string
    ,ClaimLinePaidAmount string
    ,ProcedureCodeQualifierCOB string
    ,CPTCodeLine string
    ,CPTMod1Line string
    ,CPTMod2Line string
    ,CPTMod3Line string
    ,CPTMod4Line string
    ,ProcedureDescriptionLine string
    ,LineRevenueCode string
    ,LinePaidServiceUnitCount string
    ,LineBundledLineNumber string
    ,ClaimAdjustmentGroupCode1 string
    ,ClmAdjLineReasCd101 string
    ,ClmAdjLineAmt101 string
    ,ClmAdjLineQty101 string
    ,ClmAdjLineReasCd102 string
    ,ClmAdjLineAmt102 string
    ,ClmAdjLineQty102 string
    ,ClmAdjLineReasCd103 string
    ,ClmAdjLineAmt103 string
    ,ClmAdjLineQty103 string
    ,ClmAdjLineReasCd104 string
    ,ClmAdjLineAmt104 string
    ,ClmAdjLineQty104 string
    ,ClmAdjLineReasCd105 string
    ,ClmAdjLineAmt105 string
    ,ClmAdjLineQty105 string
    ,ClmAdjLineReasCd106 string
    ,ClmAdjLineAmt106 string
    ,ClmAdjLineQty106 string
    ,ClmAdjLineGrpCd2 string
    ,ClmAdjLineReasCd201 string
    ,ClmAdjLineAmt201 string
    ,ClmAdjLineQty201 string
    ,ClmAdjLineReasCd202 string
    ,ClmAdjLineAmt202 string
    ,ClmAdjLineQty202 string
    ,ClmAdjLineReasCd203 string
    ,ClmAdjLineAmt203 string
    ,ClmAdjLineQty203 string
    ,ClmAdjLineReasCd204 string
    ,ClmAdjLineAmt204 string
    ,ClmAdjLineQty204 string
    ,ClmAdjLineReasCd205 string
    ,ClmAdjLineAmt205 string
    ,ClmAdjLineQty205 string
    ,ClmAdjLineReasCd206 string
    ,ClmAdjLineAmt206 string
    ,ClmAdjLineQty206 string
    ,ClmAdjLineGrpCd3 string
    ,ClmAdjLineReasCd301 string
    ,ClmAdjLineAmt301 string
    ,ClmAdjLineQty301 string
    ,ClmAdjLineReasCd302 string
    ,ClmAdjLineAmt302 string
    ,ClmAdjLineQty302 string
    ,ClmAdjLineReasCd303 string
    ,ClmAdjLineAmt303 string
    ,ClmAdjLineQty303 string
    ,ClmAdjLineReasCd304 string
    ,ClmAdjLineAmt304 string
    ,ClmAdjLineQty304 string
    ,ClmAdjLineReasCd305 string
    ,ClmAdjLineAmt305 string
    ,ClmAdjLineQty305 string
    ,ClmAdjLineReasCd306 string
    ,ClmAdjLineAmt306 string
    ,ClmAdjLineQty306 string
    ,ClmAdjLineGrpCd4 string
    ,ClmAdjLineReasCd401 string
    ,ClmAdjLineAmt401 string
    ,ClmAdjLineQty401 string
    ,ClmAdjLineReasCd402 string
    ,ClmAdjLineAmt402 string
    ,ClmAdjLineQty402 string
    ,ClmAdjLineReasCd403 string
    ,ClmAdjLineAmt403 string
    ,ClmAdjLineQty403 string
    ,ClmAdjLineReasCd404 string
    ,ClmAdjLineAmt404 string
    ,ClmAdjLineQty404 string
    ,ClmAdjLineReasCd405 string
    ,ClmAdjLineAmt405 string
    ,ClmAdjLineQty405 string
    ,ClmAdjLineReasCd406 string
    ,ClmAdjLineAmt406 string
    ,ClmAdjLineQty406 string
    ,ClmAdjLineGrpCd5 string
    ,ClmAdjLineReasCd501 string
    ,ClmAdjLineAmt501 string
    ,ClmAdjLineQty501 string
    ,ClmAdjLineReasCd502 string
    ,ClmAdjLineAmt502 string
    ,ClmAdjLineQty502 string
    ,ClmAdjLineReasCd503 string
    ,ClmAdjLineAmt503 string
    ,ClmAdjLineQty503 string
    ,ClmAdjLineReasCd504 string
    ,ClmAdjLineAmt504 string
    ,ClmAdjLineQty504 string
    ,ClmAdjLineReasCd505 string
    ,ClmAdjLineAmt505 string
    ,ClmAdjLineQty505 string
    ,ClmAdjLineReasCd506 string
    ,ClmAdjLineAmt506 string
    ,ClmAdjLineQty506 string
    ,ClaimLineCheckRemitDt string
    ,ClaimLineRemainPatientLiab string
    ,ClaimLinePaidAmountCOB string
    ,ClaimLineCheckRemitDtCOB string
    ,ClaimLineRemainPatientLiabilityCOB string
    ,PlaceOfServiceLine string
    ,LiDiagcdPtr1 integer
    ,LiDiagcdPtr2 integer
    ,LiDiagcdPtr3 integer
    ,LiDiagcdPtr4 integer
    ,EmergencyIndicator string
    ,EPSDTIndicator string
    ,FamilyPlanningIndicator string
    ,CopayExemptIndicator string
    ,PatientWeightLine string
    ,AmbulanceTransportReasonCode string
    ,AmbulanceMilesLine string
    ,AmbulancePurposeLine string
    ,AmbulanceStretcherLine string
    ,AmbulCert0102Line string
    ,AmbulCertCond0103Line string
    ,AmbulCertCond0104Line string
    ,AmbulCertCond0105Line string
    ,AmbulCertCond0106Line string
    ,AmbulCertCond0107Line string
    ,AmbulCert0202Line string
    ,AmbulCertCond0203Line string
    ,AmbulCertCond0204Line string
    ,AmbulCertCond0205Line string
    ,AmbulCertCond0206Line string
    ,AmbulCertCond0207Line string
    ,AmbulCert0302Line string
    ,AmbulCertCond0303Line string
    ,AmbulCertCond0304Line string
    ,AmbulCertCond0305Line string
    ,AmbulCertCond0306Line string
    ,AmbulCertCond0307Line string
    ,HospiceEmployedProviderIndicator string
    ,HvpDateLine string
    ,CertDateLine string
    ,TherDateLine string
    ,LastSeenLine string
    ,Test1DateLine string
    ,Test2DateLine string
    ,ShipDateLine string
    ,LastXrayLine string
    ,InitialTxDateLine string
    ,AmbulPtCnt string
    ,ObAddUnt string
    ,Result101 string
    ,Result102 string
    ,Result103 string
    ,Result201 string
    ,Result202 string
    ,Result203 string
    ,Result301 string
    ,Result302 string
    ,Result303 string
    ,Result401 string
    ,Result402 string
    ,Result403 string
    ,Result501 string
    ,Result502 string
    ,Result503 string
    ,ContractAmtLine string
    ,ContractPrcntLine string
    ,ContractCodeLine string
    ,ContractDiscntLine string
    ,ContractVerLine string
    ,AuthNumLine string
    ,MamCertNumLine string
    ,CliaNumLine string
    ,CliaFacNumLine string
    ,ImmBtchNumLine string
    ,ReferralNumLine string
    ,SalesTax string
    ,Postage string
    ,K301Line string
    ,K302Line string
    ,K303Line string
    ,K304Line string
    ,K305Line string
    ,K306Line string
    ,K307Line string
    ,K308Line string
    ,K309Line string
    ,K310Line string
    ,LiNoteTextRefCd string
    ,LiNoteText string
    ,LiTpoNoteText string
    ,PurchAmt string
    ,PriceMethodLine string
    ,RepriceAllowedAmtLine string
    ,RepriceSaveAmtLine string
    ,RepriceOrgIdLine string
    ,RepriceDiemFlatLine string
    ,RepriceDrgApgCodeLine string
    ,RepriceDrgApgAmtLine string
    ,RepriceHcpcsCode string
    ,RepriceHcpcsCodeLine string
    ,RepriceBasisLine string
    ,RepriceUnitCntLine string
    ,RejReasonCodeLine string
    ,CompCodeLine string
    ,ExceptCodeLine string
    ,PurchasedServiceProviderLastName string
    ,PurchasedServiceProviderFirstName string
    ,PurchasedServiceProviderMiddleName string
    ,PurchasedServiceProviderNameSuffix string
    ,PurchasedServiceProviderNPI string
    ,ClaimLineSvcFacName string
    ,SvcFacNpiLine string
    ,ClaimLineSvcFacAddressLine1 string
    ,ClaimLineSvcFacAddressLine2 string
    ,ClaimLineSvcFacCity string
    ,ClaimLineSvcFacState string
    ,ClaimLineSvcFacZIPA string
    ,ClaimLineSupervisingProviderLastName string
    ,ClaimLineSupervisingProviderFirstName string
    ,ClaimLineSupervisingProviderMiddleName string
    ,ClaimLineSupervisingProviderNameSuffix string
    ,ClaimLineSupervisingProviderNPI string
    ,OrderingProviderLastName string
    ,OrderingProviderFirstName string
    ,OrderingProviderMiddleName string
    ,OrderingProviderSuffix string
    ,OrderingProviderNPI string
    ,OrderingProviderAddressLine1 string
    ,OrderingProviderAddressLine2 string
    ,OrderingProviderCity string
    ,OrderingProviderState string
    ,OrderingProviderZIP string
    ,OrderingProviderContactName string
    ,OrderingProviderCommQual1 string
    ,OrderingProviderCommNum1 string
    ,OrderingProviderCommQual2 string
    ,OrderingProviderCommNum2 string
    ,OrderingProviderCommQual3 string
    ,OrderingProviderCommNum3 string
    ,BilledAmountLineCOB string
    ,DMECertType string
    ,DMEDuration string
    ,DMEConditionIndicator string
    ,DMEConditionCode1 string
    ,DMEConditionCode2 string
)  USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/Submitted837OutboundClaimLine'