CREATE TABLE #clientCode.consolidated_ma_spanother (
 ClientID  string
,FileID  int
,LoadDateTime date
,FileLayoutID  int
,FileDescription  string
,SpanType  string
,SubscriberID  string
,StartDate date
,EndDate date
,BeneficiaryID  string
,AddressType  string
,MemberPermanentAddress1  string
,MemberPermanentAddress2  string
,MemberPermanentAddress3  string
,MemberPermanentCity  string
,MemberPermanentCounty  string
,MemberPermanentState  string
,MemberPermanentSCC  string
,MemberPermanentZipCode  string
,MemberMailingAddress1  string
,MemberMailingAddress2  string
,MemberMailingAddress3  string
,MemberMailingCity  string
,MemberMailingState  string
,MemberMailingZipCode  string
,MemberBillingAddress1  string
,MemberBillingAddress2  string
,MemberBillingAddress3  string
,MemberBillingCity  string
,MemberBillingState  string
,MemberBillingZipCode  string
,BrokerName  string
,BrokerCode  string
,BrokerAssociation  string
,CreditableCoverageFlag  string
,LEPNumberofUncoveredMonths  string
,PartDLEPAmount  string
,PartDLEPWaivedAmount  string
,PartDLEPSubsidyAmount  string
,LEPSource  string
,CurrentLISPremiumSubsidy  string
,PartDLISSubsidyLevel  string
,PartDLISCopayCategory  string
,LISSourceCode  string
,Segment  string
,GroupID  string
,Subgroup  string
,ClassID  string
,PlanCode  string
,SuffixStartDate  string
,SuffixEndDate  string
,PlanRider  string
,RiderCode  string
,PaymentMethodType  string
,PremiumWithholdOption  string
,NameofAccountHolder  string
,AccountNumber  string
,BankRoutingNumber  string
,BankAccountType  string
,CreditCardType  string
,CreditCardAccountHolderName  string
,CreditCardNumber  string
,CreditCardSecurityCode  string
,CreditCardExpirationDate  string
,HospiceFlag  string
,MedicaidFlag  string
,WorkingAgedFlag  string
,InstitutionalFlag  string
,ESRDFlag  string
,TransplantFlag  string
,DialysisFlag  string
,DisabledFlag  string
,PlanOverrideIndicator  string
,NHCFlag  string
,EGHPFlag  string
,COBUpdateDate  string
,NameofOtherCoverage  string
,SubscriberIDofOtherCoverage  string
,GroupIDofOtherCoverage  string
,KindofOtherInsurance  string
,NameofOtherInsuranceCompany  string
,PlanMemberID  string
,MedicaidID  string
,CMSContractNumber  string
,ProductLine  string
,ProductID  string
,SecondProductID  string
,Spanvalue  string
,AdditionalSpanValue  string
,PlanBenefitPackage  string
,ECDSFlag  string
,AlphaPrefix  string
,Pharmacy  string
,Dental  string
,Vision  string
,MH  string
,MHIP  string
,MHDN  string
,MHAMB  string
,CD  string
,CDIP  string
,CDDN  string
,CDAMB  string
,SNPFlag  string
,SNPEnrolleeType  int
,IssuerID  string
,MetalLevel  string
,CostSharingVariant  string
,MarketCoverage  string
,CSREligibilityFlag  string
,MemberEnrollmentQHPState  string
,AlternateMemberKey1  string
,AlternateMemberKey2  string
,AlternateMemberKey3  string
,AlternateMemberKey4  string
,AlternateMemberKey5  string
,PlanEmployeeFlag  string
,SourcefileID  string
,DualStatusCode  string
,MedicaidRecordType  string
,SPAPType string
,SPAPID string
,TransplantFlagType string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/SpanOther'