CREATE TABLE #clientCode.consolidated_ma_mao004 (
 ClientID  string
,FileID  int
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,ReportDate  string
,RecordType  string
,ReportID  string
,MedicareAdvantageContractID  string
,BeneficiaryID  string
,EncounterICN  string
,EncounterTypeSwitch  string
,ICNofEncounterLinkedTo  string
,AllowedDisallowedStatusofEncounterLinkedTo  string
,EncounterSubmissionDate date
,FromDateofService date
,ThroughDateofService date
,ServiceType  string
,AllowedDisallowedflag  string
,AllowedDisallowedReasonCode  string
,DiagnosesICD  string
,DiagnosisCode1  string
,AddorDeleteflag1  string
,DiagnosisCode2  string
,AddorDeleteflag2  string
,DiagnosisCode3  string
,AddorDeleteflag3  string
,DiagnosisCode4  string
,AddorDeleteflag4  string
,DiagnosisCode5  string
,AddorDeleteflag5  string
,DiagnosisCode6  string
,AddorDeleteflag6  string
,DiagnosisCode7  string
,AddorDeleteflag7  string
,DiagnosisCode8  string
,AddorDeleteflag8  string
,DiagnosisCode9  string
,AddorDeleteflag9  string
,DiagnosisCode10  string
,AddorDeleteflag10  string
,DiagnosisCode11  string
,AddorDeleteflag11  string
,DiagnosisCode12  string
,AddorDeleteflag12  string
,DiagnosisCode13  string
,AddorDeleteflag13  string
,DiagnosisCode14  string
,AddorDeleteflag14  string
,DiagnosisCode15  string
,AddorDeleteflag15  string
,DiagnosisCode16  string
,AddorDeleteflag16  string
,DiagnosisCode17  string
,AddorDeleteflag17  string
,DiagnosisCode18  string
,AddorDeleteflag18  string
,DiagnosisCode19  string
,AddorDeleteflag19  string
,DiagnosisCode20  string
,AddorDeleteflag20  string
,DiagnosisCode21  string
,AddorDeleteflag21  string
,DiagnosisCode22  string
,AddorDeleteflag22  string
,DiagnosisCode23  string
,AddorDeleteflag23  string
,DiagnosisCode24  string
,AddorDeleteflag24  string
,DiagnosisCode25  string
,AddorDeleteflag25  string
,DiagnosisCode26  string
,AddorDeleteflag26  string
,DiagnosisCode27  string
,AddorDeleteflag27  string
,DiagnosisCode28  string
,AddorDeleteflag28  string
,DiagnosisCode29  string
,AddorDeleteflag29  string
,DiagnosisCode30  string
,AddorDeleteflag30  string
,DiagnosisCode31  string
,AddorDeleteflag31  string
,DiagnosisCode32  string
,AddorDeleteflag32  string
,DiagnosisCode33  string
,AddorDeleteflag33  string
,DiagnosisCode34  string
,AddorDeleteflag34  string
,DiagnosisCode35  string
,AddorDeleteflag35  string
,DiagnosisCode36  string
,AddorDeleteflag36  string
,DiagnosisCode37  string
,AddorDeleteflag37  string
,DiagnosisCode38  string
,AddorDeleteflag38  string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/MAO004'