CREATE TABLE #clientCode.consolidated_aca_member (
 ClientID  string
,FileID  int
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,TransactionType  string
,UniquePersonKey  string
,PlanMemberID  string
,SubscriberID  string
,StartDate  string
,EndDate  string
,SubscriberFlag  string
,BeneficiaryID  string
,FullName  string
,LastName  string
,FirstName  string
,MiddleInitial  string
,Title  string
,Suffix  string
,GateWayMemberStatus  string
,AlternateMemberID  string
,EnrolleeUniqueID  string
,DateofBirth date
,DeceasedDate date
,Gender  string
,MemberSSN  string
,PermanentAddressLine1  string
,PermanentAddressLine2  string
,PermanentAddressLine3  string
,PermanentCity  string
,PermanentCounty  string
,PermanentState  string
,PermanentSCC  string
,PermanentZipCode  string
,MailingAddressLine1  string
,MailingAddressLine2  string
,MailingAddressLine3  string
,MailingCity  string
,MailingState  string
,MailingZipCode  string
,MailingCounty  string
,BillingAddreessLine1  string
,BillingAddreessLine2  string
,BillingAddreessLine3  string
,BillingCity  string
,BillingState  string
,BillingZipCode  string
,PhoneNumber  string
,AlternatePhoneNumber  string
,Email  string
,EmergencyContactName  string
,EmergencyContactRelationship  string
,EmergencyContactPhoneNumber  string
,IDCardTriggerflag  string
,EndangeredMemberFlag  string
,OOAProcess  string
,OOASource  string
,DateofMove  string
,MoveDeadline  string
,MedicaidID  string
,MedicarePartAEffDate  string
,MedicarePartAEndDate  string
,MedicarePartBEffDate  string
,MedicarePartBEndDate  string
,MedicarePartDEffDate  string
,MedicarePartDEndDate  string
,Languagecode  string
,AlternativeFormatLargePrint  string
,AlternativeFormatBraille  string
,AlternativeFormatAudioTape  string
,Fax  string
,InLEPProcessStatus  string
,POAName  string
,POALastName  string
,POAFirstName  string
,POAMiddleInitial  string
,POAAddress1  string
,POAAddress2  string
,POAAddress3  string
,POACity  string
,POACounty  string
,POAState  string
,POAZipCode  string
,POAPhoneNumber  string
,POARelationShip  string
,RaceCode  string
,RaceDataSource  string
,ikaUniqueID  string
,FamilyLinkIndicator  string
,InPremiumDelinquencyProcess  string
,ThirdPartyLiabilityEffDate  string
,ThirdPartyLiabilityTrnDate  string
,OwedPremium  string
,CaretakerFirstName  string
,CaretakerLastName  string
,CaretakerMiddleInitial  string
,EthnicityCode  string
,EthnicityDataSource  string
,SpokenLanguage  string
,SpokenLanguageSourceCode  string
,WrittenLanguageCode  string
,WrittenLanguageSourceCode  string
,OtherLanguage  string
,OtherLanguageSourceCode  string
,USCitizen  string
,AlternateKey1  string
,AlternateKey2  string
,AlternateKey3  string
,AlternateKey4  string
,AlternateKey5  string
,AlternateKey6  string
,AlternateKey7  string
,AlternateKey8  string
,AlternateKey9  string
,AlternateKey10  string
,MaskedMemberID  string
,EnrolleeEducation  string
,EnrolleeEmployment  string
,FullRowHash  string
) USING delta LOCATION '/mnt/#clientCode/consolidated/ACA/Data/Member'