CREATE TABLE #clientCode.consolidated_ma_pharmacy  (
 ClientID  string
,LoadDateTime date
,FileID  int
,FileLayoutID  int
,FileLayoutDescription  string
,UniquePersonKey  string
,PlanMemberID  string
,BeneficiaryID  string
,ProviderID  string
,ProviderNPI  string
,ClaimNumber  string
,ProductID  string
,AmountCharged  string
,AmtEligible  string
,AmountPaid  string
,NDCCodeSTD  string
,RxFillDate date
,RxDaysSupply  int
,RXNorm  string
,CVX  string
,RxCodeType  string
,USCCode  string
,GPI  string
,GPIName  string
,Quantity DOUBLE
,UnitsOfMeasure  string
,PrescriberNumber  string
,PrescriberID  string
,DEANumber  string
,ClaimStatus  string
,AdjudicationDate  string
,DispensingFee  string
,CoPay  string
,CoInsurance  string
,Deductible  string
,DispenseAsWritten  string
,MailOrder  string
,SalesTax  string
,PharmacyNPI  string
,PrescriptionReferenceNumber  string
,PlaceOfService  string
,SuppliesClaim  string
,ClaimSourceIndicator  string
,AlternateKey1  string
,AlternateKey2  string
,ProviderSpecialty  string
,SourceName  string
,BackoutIndicator string
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/Pharmacy'