CREATE TABLE #clientCode.consolidated_ma_fefd (
 BeneficiaryID  string
,Surname  string
,FirstName  string
,MiddleInitial  string
,GenderCode  int
,DateofBirth date
,MedicaidIndicator  string
,ContractNumber  string
,StateCode  string
,CountyCode  string
,DisabilityIndicator  string
,HospiceIndicator  string
,InstitutionalIndicator  string
,ESRDIndicator  string
,TransactionReplyCode  string
,TransactionCode  string
,EntitlementTypeCode  string
,EffectiveDate date
,WAIndicator  string
,PlanBenefitPackageID  string
,RaceCode  string
,TransactionDate date
,SubsidyEndDate  string
,DistrictOfficeCode  string
,SourceID  string
,PriorPlanBenefitPackageID  string
,ApplicationDate  string
,OutofAreaFlag  string
,SegmentNumber  string
,PartCBeneficiaryPremium  string
,PartDBeneficiaryPremium  string
,ElectionType  string
,EnrollmentSourceCode  string
,PartDOptOutFlag  string
,NumberofUncoveredMonths  string
,CreditableCoverageFlag  string
,EmployerSubsidyOverrideFlag  string
,RxID  string
,RxGroup  string
,SecondaryDrugInsuranceFlag  string
,SecondaryRxID  string
,SecondaryRxGroup  string
,EGHP  string
,PartDLIPSLevel  string
,LowIncomeCoPayCategory  string
,LowIncomeCoPayEffectiveDate  string
,PartDLEPAmount  string
,PartDLEPWaivedAmount  string
,PartDLEPSubsidyAmount  string
,LowIncomePartDPremiumSubsidyAmount  string
,FileID  int
,FileLayoutID  int
,FileLayoutDescription  string
,ClientID  string
,LoadDateTime date
) USING delta LOCATION '/mnt/#clientCode/consolidated/MA/Data/FEFD'