CREATE TABLE #clientCode.consolidated_comm_chaselist (
 ClientID string
,LoadDateTime date
,FileID bigint
,FileLayoutID int
,FileLayoutDescription string
,PlanMemberID string
,MemberMasterID string
,CMSRADVMemberID string
,BeneficiaryID string
,CMSContractNumber string
,MemberFirstName string
,MemberLastName string
,MemberGender string
,MemberDOB date
,EnrolleeID string
,RRBHICID string
,Source string
,ClientCode string
,LOB string
,FacilityType string
,ProviderNPI string
,ProviderSpecialty string
,ProviderFirstName string
,ProviderLastName string
,ProviderAddress1 string
,ProviderAddress2 string
,ProviderCity string
,ProviderState string
,ProviderZip string
,ProviderPhone string
,ProviderFax string
,ProviderContact string
,ProviderGroupName string
,ProviderGroupTIN string
,ProjectID string
,ProjectName string
,ClaimNumber string
,ClientChartID string
,ImageFileName string
,HCCList string
,HCCModel string
,ICDList string
,ICDVersion string
,SiteID string
,ProviderType string
,TargetYearVisits string
,RetrievalMethod string
,LastServiceDate string
,RAF string
,RAGain string
,BegDOS date
,EndDOS date
,OldCMSContractNumber string
,ClientDefinedText1 string
,ClientDefinedText2 string
,ClientDefinedNumber1 string
,ClientDefinedNumber2 string
,ClientDefinedDate1 string
,ClientDefinedDate2 string
,Identifier  string
,SubscriberID string
,FacilityName  string
,BillType  string
,ClientPractitionerID  string
,ProviderID  string
,CommercialPlanID  string
,MemberPhoneNumber  string
,SubID  string
,MemberMI  string
,ProviderSpecialtyCode  string
,HIOSID  string
,Priority  string
,EMRFlag  string
,ProviderOrganizationName  string
,ProviderOrganizationCode  string
,Membership  string
,RiskLevel  string
,ProviderGroupCode  string
,PlaceOfService  string
,FlagForRetroPhase  string
,MCEMatch  string
)  USING delta LOCATION '/mnt/#clientCode/consolidated/COMM/Data/ChaseList'