CREATE TABLE #clientCode.gold_ma_pcpattribution (
 FilelayoutID int
,BISInternalPersonID string
,UniquePersonKey string
,PlanMemberID string
,BeneficiaryID string
,MedicaidID string
,StartDate date
,EndDate date
,AdditionalSpanValue string
,ProviderID string
,AltPCPReporting1 string
,AltPCPReporting2 string
,AltPCPReporting3 string
,AltPCPReporting4 string
,AltPCPReporting5 string
,AltPCPReporting6 string
,AltPCPReporting7 string
,AltPCPReporting8 string
,AltPCPReporting9 string
,AltPCPReporting10 string
,SubscriberID string
,ProviderAddressSuffix string
,ProviderEffDate date
,ProviderFirstName string
,ProviderLastName string
,ProviderMiddleIntial string
,MemberFirstName string
,MemberLastName string
,MemberMiddleIntial string
,MemberDOB string
,ContractNumber string
,ProviderNPI string
,ProviderTaxonomy string
,ProviderTIN string
,ProviderAddress1 string
,ProviderAddress2 string
,ProviderCity string
,ProviderState string
,ProviderZip string
,ProviderCounty string
,ProviderPhone string
,ProviderFax string
,ProviderEmail string
,BillingProviderID string
,BillingProviderLastName string
,BillingProviderMiddleInitial string
,BillingProviderFirstName string
,BillingProviderNPI string
,BillingProviderTIN string
,BillingProviderAddressLine1 string
,BillingProviderAddressLine2 string
,BillingProviderCity string
,BillingProviderState string
,BillingProviderZipCode string
,BillingProviderCountyCode string
,BillingProviderPhoneNumber string
,BillingProviderFaxNumber string
,BillingProviderEmail string
,Source string
,IsActive int
,ErrorVoidStatus string
,FileGenerationDateTime timestamp
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Client/PCPAttribution'