CREATE TABLE #clientCode.gold_ma_q360monthlymembershipdetail (
 ContractNumber  string
,RunDate  integer
,PaymentDate  integer
,BeneficiaryID  string
,Surname  string
,FirstInitial  string
,GenderCode  string
,DateOfBirth  integer
,Filler  string
,StateCountyCode  string
,OutOfAreaIndicator  string
,PartAEntitlement  string
,PartBEntitlement  string
,Hospice  string
,ESRD  string
,AgedDisabledMSP  string
,Filler1  string
,Filler2  string
,NewMedicareBeneficiaryMedicaidStatusFlag  string
,LTIFlag  string
,MedicaidAddOnFactorIndicator  string
,Filler3  string
,DefaultRiskFactorCode  string
,RiskAdjustmentFactorA  string
,RiskAdjustmentFactorB  string
,NumberOfPaymentAdjustmentMonthsPartA  string
,NumberOfPaymentAdjustmentMonthsPartB  string
,AdjustmentReasonCode  string
,PaymentAdjustmentStartDate  integer
,PaymentAdjustmentEndDate  integer
,Filler4  string
,Filler5  string
,MonthlyRiskAdjustedAmountPartA  string
,MonthlyRiskAdjustedAmountPartB  string
,LISPremiumSubsidy  string
,ESRDMSPFlag  string
,MedicationTherapyManagementAddOn  string
,Filler6  string
,MedicaidFullPartialNondual  string
,RiskAdjustmentAgeGroup  string
,Filler7  string
,Filler8  string
,Filler9  string
,PlanBenefitPackageID  string
,Filler10  string
,RiskAdjustmentFactorTypeCode  string
,FrailtyIndicator  string
,OriginalReasonForEntitlementCode  string
,Filler11  string
,SegmentNumber  string
,Filler12  string
,EGHPFlag  string
,PartCBasicPremiumPartAAmount  string
,PartCBasicPremiumPartBAmount  string
,RebateForPartACostSharingReduction  string
,RebateForPartBCostSharingReduction  string
,RebateForOtherPartAMandatorySupplementalBenefits  string
,RebateForOtherPartBMandatorySupplementalBenefits  string
,RebateForPartBPremiumReductionPartAAmount  string
,RebateForPartBPremiumReductionPartBAmount  string
,RebateForPartDSupplementalBenefitsPartAAmount  string
,RebateForPartDSupplementalBenefitsPartBAmount  string
,TotalPartAMAPayment  string
,TotalPartBMAPayment  string
,TotalMAPaymentAmount  string
,PartDRAFactor  string
,PartDLowIncomeIndicator  string
,PartDLowIncomeMultiplier  string
,PartDLongTermInstitutionalIndicator  string
,PartDLongTermInstitutionalMultiplier  string
,RebateForPartDBasicPremiumReduction  string
,PartDBasicPremiumAmount  string
,PartDDirectSubsidyMonthlyPaymentAmount  string
,ReinsuranceSubsidyAmount  string
,LowIncomeSubsidyCostSharingAmount  string
,TotalPartDPayment  string
,NumberOfPaymentAdjustmentMonthsPartD  string
,PACEPremiumAddOn  string
,PACECostSharingAddOn  string
,PartCFrailtyScoreFactor  string
,MSPFactor  string
,MSPReductionReductionAdjustmentAmountPartA  string
,MSPReductionReductionAdjustmentAmountPartB  string
,MedicaidDualStatusCode  string
,PartDCoverageGapDiscountAmount  string
,PartDRiskAdjustmentFactorType  string
,DefaultPartDRiskAdjustmentFactorCode  string
,PartARiskAdjustedMonthlyRateAmountForPaymentAdjustment  string
,PartBRiskAdjustedMonthlyRateAmountForPaymentAdjustment  string
,PartDDirectSubsidyMonthlyRateAmountForPaymentAdjustment  string
,CleanupID  string
,LoadDateTime  timestamp
,FileId  int
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Q360/q360monthlymembershipdetail'