CREATE TABLE #clientCode.gold_ma_q360membershipstars (
 YEAR_MTH_KEY  int
,MEMBER_ID  string
,MBI  string
,MEMBER_LAST_NAME  string
,MEMBER_FIRST_NAME  string
,MEMBER_GENDER  string
,MEMBER_DOB  string
,MEMBER_DOD  string
,MEMBER_DEATH_IND  int
,MEMBER_ADDRESS1  string
,MEMBER_ADDRESS2  string
,MEMBER_CITY  string
,MEMBER_STATE  string
,MEMBER_ZIP  string
,MEMBER_COUNTY  string
,MEMBER_PHONE  string
,MEMBER_EMAIL  string
,PLAN_ID  string
,PRODUCT_NAME  string
,PBP  string
,MEMBER_GROUP_NUMBER  string
,MEMBER_GROUP_NAME  string
,MEMBER_GROUP_CATEGORY  string
,ATTRIBUTION_CLASS  string
,ENRL_MIN_BEGIN_DATE  string
,ENRL_BEGIN_DT  string
,ENRL_END_DT  string
,HOSPICE_IND  int
,ESRD_IND  int
,INSTL_IND  int
,RISK_SCORE_cMMR  string
,LIS_IND  int
,RX_FLAG  int
,PO_ID  string
,PO_NAME  string
,PU_ID  string
,PU_NAME  string
,PROVIDER_ID  string
,NPI  string
,TIN  string
,PROVIDER_LAST_NAME  string
,PROVIDER_FIRST_NAME  string
,PROVIDER_ADDRESS1  string
,PROVIDER_ADDRESS2  string
,PROVIDER_CITY  string
,PROVIDER_STATE  string
,PROVIDER_ZIP  string
,PROVIDER_COUNTY  string
,PROVIDER_EMAIL  string
,PROVIDER_PHONE  string
,PROVIDER_FAX  string
,PROVIDER_TYPE  string
,PCMH  int
,CURR_CVG_IND  int
,PROVIDER_TAXONOMY  string
,PROVIDER_SPECIALTY  string
,MEMBER_DO_NOT_CONTACT  int
,ALT_MEMBER_ID9  string
,ALT_MEMBER_ID_CURR  string
,MEMBER_ADDRESS_TYPE  string
,ALT_PROVIDER_REPORTING_01  string
,BILLING_PROVIDER_TIN  string
,ATTRIBUTION_SOURCE  string
,LOAD_DATE  timestamp
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Quality/Q360MembershipStars'