CREATE TABLE #clientCode.gold_ma_mamembershipstars (
 yearMonth  int
,planMemberID  string
,beneficiaryID  string
,memberLastName  string
,memberFirstName  string
,memberGender  string
,memberDOB date
,memberDOD date
,memberDeathInd  int
,memberAddress1  string
,memberAddress2  string
,memberCity  string
,memberState  string
,memberZip  string
,memberCounty  string
,memberPhone  string
,memberEmail  string
,planID  string
,productName  string
,pbp  string
,memberGroupNumber  string
,memberGroupName  string
,memberGroupCategory  string
,attributionClass  string
,enrlMinBeginDate date
,enrlBeginDate date
,enrlEndDate date
,hospiceInd  int
,esrdInd  int
,instlInd  int
,riskScoreCMMR DOUBLE
,lisInd  int
,rxFlag  int
,poCode  string
,poName  string
,practiceCode  string
,practiceName  string
,providerID  string
,providerNPI  string
,providerTIN  string
,providerLastName  string
,providerFirstName  string
,providerAddress1  string
,providerAddress2  string
,providerCity  string
,providerState  string
,providerZip  string
,providerCounty  string
,providerEmail  string
,providerPhone  string
,providerFax  string
,providerType  string
,pcmh  int
,currCvgInd  int
,providerTaxonomy  string
,providerSpecialty  string
,memberDoNotContact  int
,altMemberId9  string
,altMemberIdCurr  string
,sourceLoadDate timestamp
,HashRowKey  int
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Quality/MAMembershipStars'