CREATE TABLE #clientCode.gold_ma_consolidatedmmr (
 PlanID  string
,BeneficiaryID  string
,BeneficiaryIDOriginal  string
,MBIIndicator  string
,EnrollmentMonth  string
,EnrollmentYear  string
,EnrollmentYearMonth string
,Rundate date
,Lastname  string
,FirstInitial  string
,EnrollmentSource  string
,PersonTotal  string
,PlanBenefitPackage  string
,NewPlanBenefitPackage  string
,SegmentID  string
,EghpFlag  string
,RiskAdjusterFactorA  string
,PartDRAFactor  string
,Gendercode  string
,DOB date
,Agegroup  string
,AgedDisabledIdentifier  string
,StateandCountyCode  string
,OutOfAreaIndicator  string
,Hospice  string
,ESRD  string
,AgedMsp  string
,InstitutionalFlag  string
,NHC  string
,MedicaidBeneficiaryStatusFlag  string
,MedicaidIndicator  string
,CurrentMedicaidStatus  string
,PartCDualStatusFlag  string
,PartDDualStatusFlag  string
,LTIFlag  string
,PartDLowIncomeIndicator  string
,PartDLongTermInstitutionalIndicator  string
,PartCDefaultRiskFactorCode  string
,ESRDMspFlag  string
,RiskAdjusterAgeGroup  string
,PreviousDisableRatio  string
,DeMinimis  string
,RaceCode  string
,PartCRAFactorTypeCode  string
,FrailtyIndicator  string
,OriginalReasonforEntitlement  string
,LagIndicator  string
,EnrolledInPartAIndicator  string
,EnrolledInPartBIndicator  string
,EnrolledInPartCIndicator  string
,EnrolledInPartDIndicator  string
,FinalPartCStatus  string
,FinalPartDStatus  string
,DemographicPaymentAdjustmentRatePartA  string
,DemographicPaymentAdjustmentRatePartB  string
,RiskAdjusterPaymtAdjustmentRateA  string
,RiskAdjusterPaymtAdjustmentRateB  string
,RiskAdjusterPaymtAdjustmentRateAPlusRateB  string
,RiskAdjusterPaymtAdjustmentRateAPlusRateBSeq  string
,LISPremiumSubsidy  string
,PartCBasicPremiumPartAAmount  string
,PartCBasicPremiumPartBAmount  string
,PartCBasicPremiumPartAAmountPlusPartBAmout  string
,RebateCostshareA  string
,RebateCostshareB  string
,RebateforPartAPlusPartBCostSharingReduction  string
,RebateforPartAPlusPartBCostSharingReductionSeq  string
,RebateforOtherPartAMandatorySupplementalBenefits  string
,RebateforOtherPartBMandatorySupplementalBenefits  string
,RebateforOtherPartAPlusPartBMandatorySupplementalBenefits  string
,RebateforOtherPartAPlusPartBMandatorySupplementalBenefitsSeq  string
,RebateforPartBPremiumReductionPartAAmount  string
,RebateforPartBPremiumReductionPartBAmount  string
,RebateforPartBPremiumReductionPartAPlusPartBAmount  string
,RebateforPartBPremiumReductionPartAPlusPartBAmountSeq  string
,RebateforPartDSupplementalBenefitsPartAAmount  string
,RebateforPartDSupplementalBenefitsPartBAmount  string
,RebateforPartDSupplementalBenefitsPartAPlusPartBAmount  string
,RebateforPartDSupplementalBenefitsPartAPlusPartBAmountSeq  string
,TotalPartAPayment  string
,TotalPartBPayment  string
,TotalPartCPayment  string
,RebateForPartDBasicPremiumReduction  string
,RebateForPartDBasicPremiumReductionSeq  string
,PartDBasicPremiumAmount  string
,PartDDirectSubsidyPaymentAmount  string
,PartDDirectSubsidyPaymentAmountSeq  string
,ReinsuranceSubsidyAmount  string
,LowIncomeSubsidyCostSharingAmount  string
,TotalPartDPayment  string
,PacePremiumAddOn  string
,PaceCostSharingAddOn  string
,BeneficiaryDualandPartDEnrollmentStatusFlag  string
,PartCFrailtyScoreFactor  string
,MspFactor  string
,MspMemberMonths  string
,MspReductionAdjustmentAmountPartA  string
,MspReductionAdjustmentAmountPartB  string
,MspReductionAdjustmentPartAPlusPartBAmount  string
,MspReductionAdjustmentPartAPlusPartBAmountSeq  string
,MedicaidDualStatusCode  string
,GapDiscount  string
,GapDiscountSeq  string
,PdRafactype  string
,DefaultPdRa  string
,Finalmedicaidstatus  string
,Plantype  string
,PlanTypeSeparator  string
,BidNoRisk  string
,BidNoRiskSeq  string
,PartCCountyLevelPaymentRate  string
,PartCCountyLevelPaymentRateSeq  string
,RSPTCBIDMedicaidStatus  string
,BeneficiaryPartCDEGroup  string
,BeneficiaryPartCEsrdGroup  string
,BeneficiaryPartCMedicaidStatus  string
,BeneficiaryPartCDualStatus  string
,BeneficiaryPartCRiskScoreBaseUnnormalizedEDS  string
,BeneficiaryPartCRiskScoreProjUnnormalizedEDS  string
,BeneficiaryPartCRiskScoreBaseNormalizedForEDS  string
,BeneficiaryPartCRiskScoreProjNormalizedForEDS  string
,BeneficiaryPartCRiskScoreBaseUnNormalizedForEDS  string
,BeneficiaryPartCRiskScoreProjUnNormalizedForEDS  string
,BeneficiaryPartCRiskScoreBaseUnNormalizedRAPS  string
,BeneficiaryPartCRiskScoreBaseNormalizedForRAPS  string
,BeneficiaryPartCRiskScoreBaseUnNormalizedForRAPS  string
,BeneficiaryPartCRiskcohort  string
,BeneficiaryPartCFlag  string
,BeneficiaryPartCFrailtyMemberMonths  string
,PartDBeneficiaryFileBeneficiaryStatus  string
,PartDBeneficiaryFileEDSRiskScore  string
,PartDBeneficiaryFileRAPSRiskScore  string
,PartDBeneficiaryFileProjEdsRiskScore  string
,BeneficiaryFilePartDStatus  string
,BeneficiaryFilePartDFlag  string
,CMMRFileCreateDate date
,ClientID  string
,LoadDateTime date
,FileID  int
,FileLayoutID  int
,FileLayoutDescription  string
,SubscriberID  string
,GroupNumber  string
,GroupSuffix  string
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Client/ConsolidatedMMR'