CREATE TABLE #clientCode.gold_ma_gapsincarerr (
 gapsInCareID BIGINT
,yearMonth  int
,planMemberID  string
,measureID BIGINT
,subMeasureID  int
,measureCode  string
,measureName  string
,numerCnt  int
,denomCnt  int
,eventName  string
,dateOfService date
,providerID  string
,providerName  string
,dataLoadName  string
,dataFileName  string
,expectedRate string
,serviceNeededByDate date
,PDC string
,lastHBVal string
,lastHBDate date
,lastBPDia  int
,lastBPSys  int
,lastBPDate date
,category  string
,memberServiceMeasureID  int
,memberMeasureID  int
,serviceMeasureID  int
,flaggedEventID  int
,pharmacyQualGapID  int
,pharmacyQualGapSUPDID  int
,claimNumber  string
,creationDateTime timestamp
,HashRowKey  int
,hbTest int
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Quality/GapsInCareRR'