CREATE TABLE #clientCode.gold_ma_member (
 BISInternalPersonID string
,UniqueRecord string 
,ClientID  string
,FileID  int
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,UniquePersonKey  string
,PlanMemberID  string
,SubscriberID  string
,BeneficiaryID  string
,LastName  string
,FirstName  string
,MiddleInitial  string
,EnrolleeUniqueID  string
,DateofBirth date
,DeceasedDate date
,Gender  string
,PermanentAddressLine1  string
,PermanentAddressLine2  string
,PermanentCity  string
,PermanentCounty  string
,PermanentState  string
,PermanentZipCode  string
,MailingAddressLine1  string
,MailingAddressLine2  string
,MailingCity  string
,MailingState  string
,MailingZipCode  string
,MailingCounty  string
,PhoneNumber  string
,Email  string
,MedicaidID  string
,Fax  string
,RaceCode  string
,RaceDataSource  string
,CaretakerFirstName  string
,CaretakerLastName  string
,CaretakerMiddleInitial  string
,EthnicityCode  string
,EthnicityDatasource  string
,SpokenLanguage  string
,SpokenLanguagesourcecode  string
,WrittenLanguageCode  string
,WrittenLanguageSourcecode  string
,OtherLanguage  string
,OtherLanguageSourcecode  string
,USCitizen  string
,AlternateKey1  string
,AlternateKey2  string
,AlternateKey3  string
,AlternateKey4  string
,AlternateKey5  string
,AlternateKey6  string
,AlternateKey7  string
,AlternateKey8  string
,AlternateKey9  string
,AlternateKey10  string
,MaskedMemberID  string
,EnrolleeEducation  string
,EnrolleeEmployment  string
,PMUP  string
,IsCurrentPMUP  int
,HashKey  string
,ProductID string
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Client/Member'