CREATE TABLE #clientCode.gold_ma_cdialertline (
 reportMonth  string
,attributedPOCode  string
,attributedPOName  string
,attributedPracticeCode  string
,attributedPracticeName  string
,attributedMarket  string
,attributedEngagement  string
,attributedNPI  string
,attributedProviderID  string
,attributedProviderName  string
,alertID  BIGINT
,clientCode  string
,LOB  string
,snapshotDate  date
,cdiAlertEntityDetailID  BIGINT
,cdiAlertEntityID  BIGINT
,planMemberID  string
,memberName  string
,memberDateOfBirth  date
,pcpProviderID  string
,apptProviderID  string
,queriesDistributed  BIGINT
,queriesReturned  BIGINT
,appointmentDate  date
,appointmentTypeID  int
,cdiReceivedDate  date
,initialMedicalRecordReviewID  BIGINT
,mrrReviewDate  date
,alertResponseOptionID  int
,isApptDateCurrentYear  int
,isReceivedDateCurrentYear  int
,deliveryDate  date
,queryReceivedFromCoderDate  date
,queryForwardedToDoctorDate  date
,queryResponseReceivedDate  date
,alertLineText  string
,alertGroupID  int
,hcc  string
,icd  string
,isConditionIdentified  int
,isConditionAddressed  int
,cdiAlertWorkflowStatusID  int
,cdiAlertWorkflowExceptionOptionID  int
,cdiAlertWorkflowID  int
,cdiAlertQueryCodeID  int
,cdiAlertQueryResponseID  int
,alertResponseOptionText  string
,alertResponseType  string
,filterDate  date
,appointmentTypeDesc  string
,cdiAlertStatusDesc  string
,cdiStatus  string
,currentMonthFlag  int
,currentlyActive  boolean
,alertsDistributedFlag  int
,alertsReturnedFlag  int
,alertsReturnedCompliantFlag  int
,alertsReturnedCompliant100pctFlag  int
,umarQualifiedFlag  int
,incentiveQualifiedFlag  int
,memberApptCDIReceivedNumber  string
,duplicateFlag  int
,hashKey  string
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/PEC/cdiAlertLine'