CREATE TABLE #clientCode.gold_ma_q360provider (
ProviderID string
,PCPFlag string
,OBGYNFlag string
,MHProviderFlag string
,EyeCareProviderFlag string
,DentistFlag string
,NephrologistFlag string
,AnesthesiologistFlag string
,NPRProviderFlag string
,PASProviderFlag string
,ProviderPrescribingPrivilegesFlag string
,ClinicalPharmacistFlag string
,HospitalFlag string
,SNFFlag string
,SurgeonFlag string
,RegisteredNurseFlag string
,PediatricianFlag string
,DiabetologistFlag string
,DieticianFlag string
,PhysiotherapistFlag string
,NutritionistFlag string
,Endocrinologist string
,Urologist string
,Cardiologist string
,Radiologist string
,Oncologist string
,PainSpecialist string
,MedicalLabTechnician string
,ClinicalLabTechnician string
,ProviderNPI string
,AdditionalColumn1 string
,AdditionalColumn2 string
,AdditionalColumn3 string
,AdditionalColumn4 string
,AdditionalColumn5 string
,Filler string
,LoadDateTime timestamp
,InNetworkFlag string
,FirstName string
,LastName string
,LocationID string
,LocationName string
,LocationType string
,ServiceLocation string
,Address1 string
,Address2 string
,City string
,State string
,Zip string
,Country string
,AddressType string
,Phone1 string
,Phone2 string
,Fax string
,Email string
,TIN string
,ProviderGroupName string
,ProviderType string
,DEA string
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Q360/Q360Provider'