CREATE TABLE #clientCode.gold_ma_q360membership (
 MemberID  string
,Gender  string
,DateOfBirth  string
,MemberLastName  string
,MemberFirstName  string
,MemberMiddleInitial  string
,SubscriberID  string
,Address1  string
,Address2  string
,City  string
,State  string
,Zip  string
,TelephoneNumber  string
,CaretakerFirstName  string
,CaretakerMiddleInitial  string
,CaretakerLastName  string
,SpokenLanguage  string
,SpokenLanguageSource  string
,WrittenLanguage  string
,WrittenLanguageSource  string
,OtherLanguage  string
,OtherLanguageSource  string
,MBI  string
,ContractID  string
,Race  string
,Ethnicity  string
,RaceDataSource  string
,EthnicityDataSource  string
,QHPIssuerLegalName  string
,EnrolleeEducation  int
,EnrolleeEmployment  int
,IssuerID  bigint
,QHPState  string
,MetalLevel  int
,VariantID  string
,APTCEligibilityFlag  int
,PlanMarketingName  string
,MedicaidExpansionQHPEnrollee  int
,ReportingStatus  string
,EnrolleeEmailAddress  string
,EnrolleePhone2  int
,TotalEnrollment  int
,CaretakerEmailAddress  string
,DeceasedDate  string
,AdditionalColumn1  string
,AdditionalColumn2  string
,AdditionalColumn3  string
,AdditionalColumn4  string
,AdditionalColumn5  string
,Filler  string
,LoadDateTime  timestamp
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Q360/q360membership'