CREATE TABLE #clientCode.gold_ma_providerhierarchy (
 ClientID  string
,FileID  int
,LoadDateTime date
,FileLayoutID  int
,FileLayoutDescription  string
,ProviderID  string
,ProviderLastName  string
,ProviderNPI  string
,LocationGroupID  string
,LocationRanking  int
,LocationIDType  string
,LocationID  string
,LocationDesc  string
,LocationTIN  string
,LocationAddress1  string
,LocationAddress2  string
,LocationCity  string
,LocationState  string
,LocationZip  string
,CountyCode  string
,PhoneNumber  string
,FaxNumber  string
,ContactPerson  string
,DoNotChase  string
,Tier2IDType  string
,Tier2ID  string
,Tier2Desc  string
,Tier2Address1  string
,Tier2Address2  string
,Tier2City  string
,Tier2State  string
,Tier2Zip  string
,Tier3IDType  string
,Tier3ID  string
,Tier3Desc  string
,Tier3Address1  string
,Tier3Address2  string
,Tier3City  string
,Tier3State  string
,Tier3Zip  string
,Tier4IDType  string
,Tier4ID  string
,Tier4Desc  string
,Tier4Address1  string
,Tier4Address2  string
,Tier4City  string
,Tier4State  string
,Tier4Zip  string
,StartDate date
,EndDate date
) USING delta LOCATION '/mnt/#clientCode/Gold/MA/Client/ProviderHierarchy'