CREATE TABLE #clientCode.gold_ma_membership (
 ClientCode	string
,SnapshotDate 	date
,ReportMonth	string
,ServiceYear	int
,MemberID	string
,EnrollmentStartDate	date
,EnrollmentEndDate	date
,MemberDOB	date
,MemberGender	string
,BeneficiaryID	string
,CMSContractnumber	string
,PlanDescription	string
,MemberFirstName	string
,MemberLastName	string
,ProviderID	string
,ProviderEffectiveStartDate	date
,ProviderEffectiveEndDate	date
,MemberAge	int
,PermanentAddressLine1	string
,PermanentAddressLine2	string
,PermanentAddressLine3	string
,PermanentCity	string
,PermanentCounty	string
,PermanentState	string
,PermanentZIPCode	string
,PBP	string
,ProviderNPI	string
,ProviderName	string
,ProviderTIN	string
,ProviderOrganization	string
,PracticeUnit	string
,PoolID	string
,Rafactortypecode	string
,RafactortypecodeDrived	string
,DefaultIndicator	string
,MedicaidDualStatusCode	string
,MedicaidIndicator  	string
,OriginalReasonforEntitlement	string
,RiskAdjusterFactorA	string
,RiskAdjusterFactorB 	string
,Hospice	string
,ESRD	string
,LowIncomeSubsidyMMRNonzero	string
,LowIncomeSubsidy	string
,MinimumEffectiveDate	date
,TotalMemberMonths	int
,Segment	string
,Memberstatus	string
,IsLatest	boolean
,MinimumStartDate	date
,MaximumEndDate	date
,AttributedProviderOffice	string
,DemographicRiskAdjustmentFactor	string
)  USING delta LOCATION '/mnt/#clientCode/Gold/MA/Risk/Membership'