CREATE TABLE #clientCode.platinum_dimprovider (
 providerKey  int
,providerID  string
,effectiveStartDate date
,effectiveEndDate date
,isCurrent  int
,npi  string
,tin  string
,lastName  string
,firstName  string
,middleName  string
,phoneNumber  string
,address1  string
,address2  string
,city  string
,state  string
,zipCode  string
,practiceCode  string
,practiceName  string
,providerOrgCode  string
,providerOrgName  string
,providerSpecialtyDescription  string
,taxonomyCode1  string
,hpSpecialtyCode1  string
,advProviderSpecialtyCode1  string
,taxonomyCode2  string
,hpSpecialtyCode2  string
,advProviderSpecialtyCode2  string
,taxonomyCode3  string
,hpSpecialtyCode3  string
,advProviderSpecialtyCode3  string
,taxonomyCode4  string
,hpSpecialtyCode4  string
,advProviderSpecialtyCode4  string
,taxonomyCode5  string
,hpSpecialtyCode5  string
,advProviderSpecialtyCode5  string
,isPrescribePrivilege  string
,providerDEA  string
,payerID  string
,isContracted  string
,providerHAI  string
,hospitalID  string
,isExcludedFromProviderReporting  string
,altProvReporting1  string
,altProvReporting2  string
,altProvReporting3  string
,altProvReporting4  string
,altProvReporting5  string
,altProvReporting6  string
,altProvReporting7  string
,altProvReporting8  string
,altProvReporting9  string
,altProvReporting10  string
,programType  string
,practiceTargetedStatus  string
,ProductID  string
,ProviderType  string
) USING delta LOCATION '/mnt/#clientCode/Platinum/dimProvider'