CREATE TABLE #clientCode.platinum_factmonthlymembercdialert (
	 factMonthlyMemberCDIAlertHash int
	,monthKey string
	,clientKey int
	,memberKey bigint
	,planID string
	,isMemberActive int
	,lineOfBusiness string
	,isInReportBase int
	,pcpProviderKey int
	,apptProviderKey int
	,alertsDistributedCnt bigint
	,alertsReturnedCnt bigint
	,alertsReturnedCompliantCnt bigint
	,isIncentiveUMARQualified bigint
	,isIncentiveQualifiedAlerts bigint
	,droppedConditionsIdentifiedCnt bigint
	,droppedConditionsAddressedCnt bigint
	,droppedConditionsYesResponseCnt bigint
	,droppedConditionsNoResponseCnt bigint
	,droppedConditionsNullResponseCnt bigint
	,opportunitiesIdentifiedCnt bigint
	,opportunitiesAddressedCnt bigint
	,opportunitiesYesResponseCnt bigint
	,opportunitiesNoResponseCnt bigint
	,opportunitiesnullResponseCnt bigint
	,starsIdentifiedCnt bigint
	,starsAddressedCnt bigint
	,alertsDistributedWithQueriesCnt bigint
	,alertsReturnedCompliantWithQueriesCnt bigint
	,queriesDistributedCnt bigint
	,queriesReturnedCnt bigint
	,queriesReturnedAddendedMRCnt bigint
	,queriesReturnedNoUpdateMRCnt bigint
	,alertsDistributedWithStarsCnt bigint
	,alertsReturnedWithStarsCnt bigint
	,alertsReturnedCompliantWithStarsCnt bigint
	,starsReturnedCompliantCnt bigint
	,starsAddressedReturnedCompliantCnt bigint
	,createdDatetime timestamp
	,updatedDatetime timestamp
) USING delta LOCATION '/mnt/#clientCode/Platinum/factMonthlyMemberCDIAlert'