CREATE TABLE #clientCode.platinum_dimmember (
 memberKey  bigint
,BISInternalPersonID  string
,uniquePersonKey  string
,planMemberID  string
,subscriberID  string
,beneficiaryID  string
,lastName  string
,firstName  string
,middleInitial  string
,enrolleeUniqueID  string
,dateofBirth  date
,deceasedDate  string
,gender  string
,permanentAddressLine1  string
,permanentAddressLine2  string
,permanentCity  string
,permanentCounty  string
,permanentState  string
,permanentZipCode  string
,mailingAddressLine1  string
,mailingAddressLine2  string
,mailingCity  string
,mailingState  string
,mailingZipCode  string
,mailingCounty  string
,phoneNumber  string
,email  string
,medicaidID  string
,fax  string
,raceCode  string
,raceDataSource  string
,caretakerFirstName  string
,caretakerLastName  string
,caretakerMiddleInitial  string
,ethnicityCode  string
,ethnicityDatasource  string
,spokenLanguage  string
,spokenLanguagesourcecode  string
,writtenLanguageCode  string
,writtenLanguageSourcecode  string
,otherLanguage  string
,otherLanguageSourcecode  string
,isUSCitizen  string
,alternateKey1  string
,alternateKey2  string
,alternateKey3  string
,alternateKey4  string
,alternateKey5  string
,alternateKey6  string
,alternateKey7  string
,alternateKey8  string
,alternateKey9  string
,alternateKey10  string
,maskedMemberID  string
,enrolleeEducation  string
,enrolleeEmployment  string
,effectiveStartDate  date
,effectiveEndDate  date
,isCurrent  boolean
,ProductID string
) USING delta LOCATION '/mnt/#clientCode/Platinum/dimMember'